### ISSUE TITLE
Some target platforms which work in 2023-09 fail to load in 2023-12

### ISSUE THREAD

**Issue by pcdavid** [eclipse-pde/eclipse.pde#1014]
The Sirius Desktop target platform files ([here](https://github.com/eclipse-sirius/sirius-desktop/tree/master/releng/org.eclipse.sirius.targets)) fail to load in Eclipse 2023-12. They resolve without issue at build time (Tycho 4.0.4), and I can load them in 2023-09.

For some reason I don't understand, this seems related to the ELK 0.7.1 part of the target (https://download.eclipse.org/elk/updates/releases/0.7.1/). At least there is something specific to how this particular repo is packaged that triggers the issue.

Steps to reproduce:
1. Unzip a fresh Eclipse for Commiters 2023-09 package.
2. Create an empty project and place the `test.target` file from below in it.
3. Open the file with the Target Editor and wait for it to load.
4. It loads successfully.
5. Repeat the same operations on a fresh Eclipse for Commiters **2023-12** package.
6. The target fails to load:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/10608/d458a404-7015-41ec-8db3-fad675355d43)

The full errors from the workspace log:
```

!ENTRY org.eclipse.pde.core 4 0 2023-12-15 14:31:59.055
!MESSAGE No repository found at http://guava-osgi.googlecode.com/svn/trunk/repository/.
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://guava-osgi.googlecode.com/svn/trunk/repository/.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:409)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:674)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.addReferences(P2TargetUtils.java:1048)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.getQueryableMetadata(P2TargetUtils.java:1025)
	at org.eclipse.pde.internal.core.target.IUBundleContainer.getRootIUs(IUBundleContainer.java:768)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.getRootIUs(P2TargetUtils.java:1519)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.resolveWithPlanner(P2TargetUtils.java:1073)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.synchronize(P2TargetUtils.java:832)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:401)
	at org.eclipse.pde.internal.ui.editor.targetdefinition.TargetEditor$TargetChangedListener$1.run(TargetEditor.java:651)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2023-12-15 14:31:59.055
!MESSAGE No repository found at http://guava-osgi.googlecode.com/svn/trunk/repository/.

!ENTRY org.eclipse.equinox.p2.engine 4 4 2023-12-15 14:31:59.760
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2023-12-15 14:31:59.760
!MESSAGE session context was:(profile=TARGET_DEFINITION:resource:/org.eclipse.sirius.targets/test.target, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2023-12-15 14:31:59.760
!MESSAGE No repository found containing: osgi.bundle,org.eclipse.emf.emfstore.common,1.7.0.v20160209-0511
```

The test file:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde?>
<target name="test" sequenceNumber="1700730918">
  <locations>
    <location includeMode="planner" includeAllPlatforms="false" includeSource="true" includeConfigurePhase="false" type="InstallableUnit">
      <unit id="org.eclipse.elk.sdk.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.sdk.feature.source.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.feature.source.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.algorithms.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.algorithms.feature.source.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.graphviz.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.graphviz.feature.source.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.ui.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.elk.ui.feature.source.feature.group" version="0.0.0"/>
      <repository id="ELK-0.7" location="https://download.eclipse.org/elk/updates/releases/0.7.1/"/>
    </location>
    <location includeMode="planner" includeAllPlatforms="false" includeSource="true" includeConfigurePhase="false" type="InstallableUnit">
      <unit id="com.google.guava" version="0.0.0"/>
      <unit id="org.eclipse.emf.common.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.emf.ecore.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.emf.edit.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.emf.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.emf.mwe.sdk.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.emf.mwe2.language.sdk.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.emf.sdk.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.equinox.sdk.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.platform.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.sdk.feature.group" version="0.0.0"/>
      <repository id="Eclipse-2023-09" location="https://download.eclipse.org/releases/2023-09/"/>
    </location>
  </locations>
</target>
```

**Comment by ewillink** [comment]
There have been at least a couple of incompatible evolutions in the infrastructure lately.
- Orbit has reduced content
- javax.annotation/inject handling is changing again
- hamcrest has gone to 2.x and needs both hamcrest and hamcrest.core
You need to make very sure that you are not mixing and matching across releases. e.g only a very recent Tycho/tycho-surefire works on 2023-12.
For my OOMPHs, I have to configure Orbit very carefully on a per-release basis. For the 2023-12 release there is a chance that Orbit now has everything, and so correct versions can be found in Orbit latest. For recent releases it may well be necessary to get most things from the corresponding Orbit and a few things from the last CVS-defined Orbit.
2023-12 introduces a warning that javax.annotation/inject are going obsolete. Unfortunately this seemed to create a false dependency requiring that a build that did not use javax.annotation must now supply it.

**Comment by laeubi** [comment]
It says 

> No repository found at http://guava-osgi.googlecode.com/svn/trunk/repository/

as far as I know http is blocked for security reasons and I can't validate that the repository is accessible at all using the "common names"....

**Comment by pcdavid** [comment]
So... the ELK 0.7.1 repo mentioned includes this in its `artifacts.jar`:
```xml
  <references size='2'>
    <repository uri='http://guava-osgi.googlecode.com/svn/trunk/repository/' url='http://guava-osgi.googlecode.com/svn/trunk/repository/' type='0' options='1'/>
    <repository uri='http://download.eclipse.org/releases/mars' url='http://download.eclipse.org/releases/mars' type='0' options='1'/>
  </references>
```
The first one is explicitly in the stack, and is ignored for security reasons as mentioned by @laeubi.

In the Mars repo's `artifacts.jar` I find:

```xml
    <artifact classifier='osgi.bundle' id='org.eclipse.emf.emfstore.common' version='1.7.0.v20160209-0511'>
      <processing size='1'>
        <step id='org.eclipse.equinox.p2.processing.Pack200Unpacker' required='true'/>
      </processing>
      <properties size='8'>
        <property name='artifact.size' value='1979575'/>
        <property name='download.size' value='1949526'/>
        <property name='format' value='packed'/>
        <property name='maven-extension' value='jar.pack.gz'/>
        <property name='maven-artifactId' value='org.eclipse.emf.emfstore.common'/>
        <property name='maven-version' value='1.7.0-SNAPSHOT'/>
        <property name='maven-groupId' value='org.eclipse.emf.emfstore'/>
        <property name='maven-classifier' value='pack200'/>
      </properties>
    </artifact>
```

Which I suppose fails to load and causes the "crash" because of the `Pack200Unpacker` step which, AFAIK, has been removed from p2?

**Comment by laeubi** [comment]
I don't know what ELK provides to Sirius, but if it is anything important I think you should help them to upgrade their dependency chains, if I found out correctly Mars was released 2015 that means > 8 years ago....

**Comment by pcdavid** [comment]
We had planned to update to a more recent ELK... but https://github.com/eclipse/elk/blob/master/build/org.eclipse.elk.repository/category.xml still contains the references.

Clearly they should remove/update that, but still, PDE should *not* refuse to load a .target file just because some artefact that nobody in the TP depends on but is in a *referenced* repo from a *referenced* location mentions a step that current p2 does not support.

**Comment by laeubi** [comment]
I'll check if we can cover that case but don't expect anything to work with such old versions, if you need to support them you also need to use old toolchains and tools.

**Comment by ewillink** [comment]
> I'll check if we can cover that case but don't expect anything to work with such old versions,

OOMPH itself has a version limit. IIRC it failed for Oxygen, but was ok for Photon. Mars - no way.

**Comment by laeubi** [comment]
I have checked this and the not found repository seems correctly being ignored (but logged), the rest just creates something that can't be resolved by P2 maybe because `org.eclipse.emf.emfstore.common` is only available as packed from that is no longer supported by P2 itself.

**Comment by pcdavid** [comment]
> We had planned to update to a more recent ELK... but https://github.com/eclipse/elk/blob/master/build/org.eclipse.elk.repository/category.xml still contains the references.
> 
> Clearly they should remove/update that

Done in the new ELK 0.9.0 repo: https://github.com/eclipse/elk/pull/983
