### ISSUE TITLE
Error message indicates the minor version needs to be incremented because of a BREE change, but one that happened long ago

### ISSUE THREAD

**Issue by merks** [eclipse-pde/eclipse.pde#1016]
I see this in my Oomphed Eclipse SDK IDE today:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/c708b7c7-5dd9-4b2a-85ef-bd8ee985addb)

I saw the same type of problem with GEF, also where the BREE change happened really quite long ago.

Is the error message correct?  Why does it show up several releases later?

**Comment by iloveeclipse** [comment]
Typically "unexpected" errors disappear after few times clean building or restartt.

**Comment by merks** [comment]
Typically I delete the API baseline completely so the problem goes away for a while, and then we see what crops of the next time.

It's still a question of whether the error is bogus on not too though.  I.e., does a BREE change require a minor version increment?

**Comment by iloveeclipse** [comment]
> does a BREE change require a minor version increment?

Yes

**Comment by merks** [comment]
Indeed, and now I see it was property done at that time!

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/d669a70a-cfd8-43c4-855f-6a27484ecb88)

**Comment by HannesWell** [comment]
> Typically I delete the API baseline completely so the problem goes away for a while, and then we see what crops of the next time.

I also often have unexpected API errors, usually shortly before and after a GA release. But deleting the baseline is a workaround that also worked for me in the past.



> Indeed, and now I see it was properly done at that time!

So can we close this as completed?

**Comment by merks** [comment]
Yes, we can close it, except of course that API tools are quite unreliable.  😱 

Refresh the baseline re-build and then there are these:

![image](https://github.com/eclipse-equinox/p2/assets/208716/f3aed906-d7db-4a10-a6cf-ea3539c14b8a)

I think these are real errors though, right?  Shouldn't this fail the build?

**Comment by iloveeclipse** [comment]
> I think these are real errors though, right? Shouldn't this fail the build?

Can you please create SWT bug to fix that? That is clearly a problem.
