### ISSUE TITLE
Stop building and publishing api.tools.ee.feature

### ISSUE THREAD

**Issue by akurtakov** [eclipse-pde/eclipse.pde#102]
If one looks at https://github.com/eclipse-pde/eclipse.pde/blob/master/apitools/org.eclipse.pde.api.tools.ee.feature/feature.xml it contains only osgiminimum and cdc profiles that are totally useless now. Thus I propose to stop building and publishing the feature.
@vik-chand what do you think?

**Comment by vogella** [comment]
Can we also delete the osgiminimum and cdc profiles?

**Comment by vik-chand** [comment]
These EEs are present in Installed JREs-> Execution Environment. We should remove this together.  ( @SarikaSinha for jdt debug) .Also I think 4.25M1 may be a good milestone to do this assuming there are no objections.

**Comment by vogella** [comment]
@vik-chand can you do the deletion in PDE and coordinate with @SarikaSinha?

**Comment by akurtakov** [comment]
It's Java 1.3 in the newest versions of these profiles, javac can no longer even build such bytecode anymore. I don't see anyone doing any 1.3 development anymore thus I consider it useless. The far more likely to be used ones like JavaSE 1.2....9 are already removed via https://github.com/eclipse-pde/eclipse.pde/commit/cecda9b81e0c60294ebd496c5921b454ade82b41 with no one noticing but keeping the even more ancient ones are needed by someone?

**Comment by akurtakov** [comment]
@merks Do I get it correct that your concern is more that Oomph setup files will have to be changed to no longer require that feature? EEs are completely usable without that feature for a good number of releases already.

**Comment by akurtakov** [comment]
I'll take care of removing it from the repos I have access to (aka everything but JDT).

**Comment by vogella** [comment]
I can take PDE and https://github.com/vogellacompany/eclipse.platform.ui/pull/new/api.tools.ee.feature

**Comment by vogella** [comment]
> I can take PDE and https://github.com/vogellacompany/eclipse.platform.ui/pull/new/api.tools.ee.feature

@akurtakov already did it for PDE. Fast are you Jedi.....

**Comment by merks** [comment]
@vogella  Thanks!  @akurtakov You're the best!!
