### ISSUE TITLE
How can I hide the Object and Enum methods from code completion?

### ISSUE THREAD

**Issue by ProperNovice** [eclipse-pde/eclipse.pde#1044]
Hello everyone,

I am using Eclipse 23-12 (4.30.0) version and it seems that I can't hide anymore the Object and Enum default methods from code completion.

Up to now, I got it working by using the Type Filters preferences, adding the java.lang.Object and java.lang.Enum* filter names. It was working brilliantly, only showing the new methods I was adding in each class and enum.

But with the last couple updates this doesn't seem to work. I have included photos to have a visualization aspect as well.

Can you enlighten me?

Thank you

P.S. This is a duplicate post from r/Eclipse I made earlier. I was prompt to open an issue here.

![q](https://github.com/eclipse-pde/eclipse.pde/assets/11249537/4a290cc2-72de-4d74-8d1a-e1917fdc18de)
![qq](https://github.com/eclipse-pde/eclipse.pde/assets/11249537/fb98a3e7-bf43-48c7-aaa5-5913f01d9686)

**Comment by HannesWell** [comment]
This looks like a JDT issue, probably `jdt.ui`:
https://github.com/eclipse-jdt/eclipse.jdt.ui

Please open this issue there. Unfortunately I cannot just move it there and therefore have to close it here.
