### ISSUE TITLE
Target Platform fails to resolve with `org.apache.commons:commons-configuration2`

### ISSUE THREAD

**Issue by guw** [eclipse-pde/eclipse.pde#1050]
Trying to resolve the following entry fails:
```
<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-configuration2 -->
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-configuration2</artifactId>
    <version>2.9.0</version>
</dependency>
```

when done using:
```
maven MavenDependencies scope=compile dependencyDepth=infinite missingManifest=generate includeSources {
...
	dependency {
		groupId="org.apache.commons"
		artifactId="commons-configuration2"
		version="2.9.0"
	}
...
}
```

The error message is:
```
!ENTRY org.eclipse.equinox.p2.engine 4 4 2024-01-14 07:25:33.812
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2024-01-14 07:25:33.812
!MESSAGE session context was:(profile=TARGET_DEFINITION:resource:/bazel-eclipse/releng/target-platform/target-platform-dev.target, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2024-01-14 07:25:33.812
!MESSAGE No repository found containing: osgi.bundle,wrapped.xml-resolver.xml-resolver,1.2.0
```

`osgi.bundle,wrapped.xml-resolver.xml-resolver,1.2.0` should be coming from Maven Central. Thus, it's unclear why this is exposing the problem.

However, the problem is only exposed in [this TP file](https://github.com/salesforce/bazel-eclipse/blob/e70a1f12bfed711ee0eb6bb10cb1241c10453c0d/releng/target-platform/target-platform-dev.target) but not in [this](https://github.com/salesforce/bazel-eclipse/blob/e70a1f12bfed711ee0eb6bb10cb1241c10453c0d/releng/target-platform/target-platform.target).

**Comment by laeubi** [comment]
> osgi.bundle, **wrapped.** xml-resolver.xml-resolver,1.2.0 should be coming from Maven Central

I highlighted the important part here so it is very unlikely its part of Maven Central, please try the latest I build if the issue is still present there.

**Comment by merks** [comment]
Maybe a network problem.  It works for me:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/7ca6312d-3296-499a-b9da-a73495e62af4)

Even it shows this:

**Comment by laeubi** [comment]
@merks it also depends on the PDE version ...

**Comment by merks** [comment]
It works for me launched from my SDK workspace with the latest clone content.

**Comment by guw** [comment]
I wonder if this was a missing dependency the TP now resolves fine for me as well (after a couple Eclipse restarts, though).
I did add org.jdom because the CI/Tycho build faild without it (ignore the accidental removal)

https://github.com/salesforce/bazel-eclipse/commit/d1b4ab581c1713f5b900caf247482f1ea824941f
