### ISSUE TITLE
Make "Run API analysis as Job" default again

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1082]
Regression from https://github.com/eclipse-pde/eclipse.pde/pull/568 for https://github.com/eclipse-pde/eclipse.pde/issues/307.
The point of the issue was to remove the preference from UI, but **not** change default value of "Run API analysis as Job".

However, default was changed and I've only realized that after playing with a new workspace trying to debug https://github.com/eclipse-pde/eclipse.pde/issues/1073. 
Since I've used old workspace with the preference set, I haven't realized the fix was wrong.
I will restore default now.

**Comment by merks** [comment]
Good catch!  👍

**Comment by iloveeclipse** [comment]
Was easy. Once I've started in a new workspace build was slower & I saw "API analysis" in the build task reported...
