### ISSUE TITLE
Support for automatic Manifest generation: Cleanup on jar files in target folder

### ISSUE THREAD

**Issue by mikerumpf** [eclipse-pde/eclipse.pde#1139]
Whennever a version number increased bnd will create a new jar file (including source jar) of a bundle in the target folder. But old ones are never removed. Of course this can be done manually. But in larger projects/workspaces this may be quite cumbersome.

It would be good if every creation of a bundle jar in a new jar would yield in old versions being removed from the target folder.

**Comment by laeubi** [comment]
@mikerumpf can you explain where exactly the jar is generated and how the instructions look like? Could it be reproduced with a simple project?

**Comment by mikerumpf** [comment]
Sorry, I was wrong. This is not a defect.
