### ISSUE TITLE
Retire "Update Site" project wizard and related editor

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#114]
Based on https://github.com/eclipse-pde/eclipse.pde/discussions/113#discussioncomment-2765717 we should retire the wizard and related editor.

We may also want to deprecated its support in p2 but that would be a different issue in a different repo.

**Comment by SarikaSinha** [comment]
Based on https://github.com/eclipse-pde/eclipse.pde/discussions/113#discussioncomment-2766261 we should not retires this wizard as it is very convenient and people who have created update sites with this wizard will need it for maintaining it.

**Comment by vogella** [comment]
You should be able to use the category.xml wizard to this. Please test and see if something is missing for your use case.

**Comment by vik-chand** [comment]
As discussed across issues, there is no 1:1 mapping and there are few things that can be only done by "Update Site". Closing this as not planned for now.
