### ISSUE TITLE
Migration of PDE wiki pages

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#1142]
I migrated https://github.com/eclipse-pde/eclipse.pde/blob/master/docs/API_Tools.md to markdown from the wiki. Do we have more PDE pages that are worthy migrating from the wiki to the PDE repo?

Wiki will disappear in a while.

cc @HannesWell @laeubi

**Comment by HannesWell** [comment]
> I migrated https://github.com/eclipse-pde/eclipse.pde/blob/master/docs/API_Tools.md to markdown from the wiki. Do we have more PDE pages that are worthy migrating from the wiki to the PDE repo?

Thanks for that! I have to admit I have not really an overview. But after a quick look I wonder if the following sites are still relevant and/or already migrated:
- https://wiki.eclipse.org/PDE/User_Guide
- https://wiki.eclipse.org/PDE/FAQ

> 
> Wiki will disappear in a while.

As far as I understood it and the banner seems to confirm this, the wiki will not disappear, it will just become read-only:
`Notice: this Wiki will be going read only early in 2024 and edits will no longer be possible. Please see: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/Wiki-shutdown-plan for the plan.`

With that I don't think we are in a rush since we can still migrate content later. Nevertheless a more consolidated wiki/documentation would still be good and I appreciate all work done in this area.

**Comment by gireeshpunathil** [comment]
@vogella - do you have any tips / best practices for wiki to markdown conversion that can be reused? like `tag X in wiki` becomes `tag Y in markdown` etc. ? thanks.

**Comment by vogella** [comment]
@gireeshpunathil I think the best reference is the Github markdown page https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by vogella** [comment]
Migration work:

https://github.com/eclipse-pde/eclipse.pde/pull/1165 from @jonahgraham 
https://github.com/eclipse-pde/eclipse.pde/pull/1169
https://github.com/eclipse-pde/eclipse.pde/pull/1170

**Comment by vogella** [comment]
Also migrated https://github.com/eclipse-equinox/equinox/blob/master/docs/Where_Is_My_Bundle.md and it is referred to by the PDE FAQ

**Comment by vogella** [comment]
Added comments to the wiki pages that they have been migrated:

https://wiki.eclipse.org/PDE/API_Tools/User_Guide
https://wiki.eclipse.org/PDE/FAQ
https://wiki.eclipse.org/PDE/User_Guide
https://wiki.eclipse.org/Execution_Environments

**Comment by vogella** [comment]
All pages have been migrated and there links have been adjusted. Wiki references have also been updated. 

Please re-open or open a new ticket in case you see more PDE content which should be migrated.

**Comment by merks** [comment]
@vogella

It's so awesome that all this is getting done!  ❤️ 

I'll need to do this for a bunch wiki content for other projects.  I'm curious if there is documentation about how this migration being performed?

**Comment by vogella** [comment]
@merks We started manually but as the scope constantly increased we used use a bunch of Dart scripts doing the download and some re-ex replacements. (Dart is my favorite get in done language, as it is simple fast). I plan to clean these up a bit  and write to the cross mailing how to use them.

**Comment by merks** [comment]
> I plan to clean these up a bit and write to the cross mailing how to use them.

That would be totally awesome.  Thanks, thanks, thanks!!

**Comment by vogella** [comment]
> Just noticed that the page https://wiki.eclipse.org/PDE/UI/SourceReferences, is not migrated yet. At least I didn't find it. It's referenced from the Repo Reports overview page, so ideally we have a replacement: https://download.eclipse.org/eclipse/downloads/drops4/R-4.39-202602260420/buildlogs/reporeports/index.html

https://github.com/eclipse-pde/eclipse.pde/pull/2285

**Comment by vogella** [comment]
Page migrated. @HannesWell you can adjust the references if you like
