### ISSUE TITLE
Add a new "Upgrade" button to EE

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#1178]
Currently PDE only support adding and removing EEs:

![grafik](https://github.com/eclipse-pde/eclipse.pde/assets/1331477/5c829f5e-117c-4cb8-bae9-8039275d228d)

but a more common thing is to *upgrade* to a new EE, currently this requires:

1. remove the old EE
2. add the new EE
3. press the "Update Classpath settings"

There should be a new "Upgrade" button that allows to select the new EE, removes all old ones and updates the classpath in one go.

As part of this, this dialog should then be sorted by EE in descending order (highest EE first):
![grafik](https://github.com/eclipse-pde/eclipse.pde/assets/1331477/edfe3ec0-5503-474e-a598-78002271b632)

**Comment by akurtakov** [comment]
Even simpler from end user POV could be double click on the EE and be able to edit directly.

**Comment by laeubi** [comment]
Yes but "discover" this might be problematic, so there should always be a "visible way" (aka button/link) to do this as well

**Comment by lathapatil** [comment]
> As part of this, this dialog should then be sorted by EE in descending order (highest EE first):

@laeubi Should the contents of the dialog be sorted as below ?

[JavaSE-21, JavaSE-20, JavaSE-19, JavaSE-18, JavaSE-17, JavaSE-16, JavaSE-15, JavaSE-14, JavaSE-13, JavaSE-12, JavaSE-11, JavaSE-10, JavaSE-9, JavaSE-1.8, JavaSE-1.7, JavaSE-1.6, J2SE-1.5, J2SE-1.4, J2SE-1.3-NO-SOUND, J2SE-1.3, OSGi/Minimum-1.2, J2SE-1.2, OSGi/Minimum-1.1, JRE-1.1, CDC-1.1/Foundation-1.1, OSGi/Minimum-1.0, CDC-1.0/Foundation-1.0]

**Comment by laeubi** [comment]
@lathapatil yes that's correct, so "highest" java should be on top.

**Comment by lathapatil** [comment]
@laeubi 

There is a confusion in implementing this in the specified order (Highest Java to lowest). Which Approach is preferred ?

Problem :  Even if we sort the list in the desired order and set the elements to dialog, the parent class (FilteredList) is sorting it back to its original form.

Approach 1: 
Can I make changes in org.eclipse.ui.workbench where FilteredList and dialog's code is located to handle sorting based on the user's choice of comparator (In this case I might have to create 2 PRs for each repo)

Approach 2:
 should I handle this within PDE itself by overriding the behavior from multiple classes of the UI workbench?

**Comment by laeubi** [comment]
@lathapatil I think the best would be to enhance `FilteredList` first as it looks like something usefull for other consumers as well.

**Comment by lathapatil** [comment]
> @lathapatil I think the best would be to enhance `FilteredList` first as it looks like something usefull for other consumers as well.

My mistake. We already have the option to set our own comparator to FilteredList. The only thing missing was the ability to sort in descending order, which I managed to achieve within my comparator itself!

![image](https://github.com/eclipse-pde/eclipse.pde/assets/130035155/10d2d374-d7c3-41e3-8871-59fcf776e5f0)

**Comment by laeubi** [comment]
I would say yes, but if it makes any complications we can simply disable the functionality if multiple EEs are currently defined, that's a really rare case anyways and most likely incorrect anyways if one upgrades one of them..

**Comment by lathapatil** [comment]
> if it makes any complications we can simply disable the functionality if multiple EEs are currently defined,

@laeubi, Thanks for the clarification. I will consider this.

 Could there be a scenario where either `OSGi/Minimum-1.0` or `CDC-1.0/Foundation-1.0` is exclusively present, and if a user is permitted to upgrade, it should be to the highest available version of either OSGi/Minimum or CDC?

I Just referred https://wiki.eclipse.org/Execution_Environments#What_are_Execution_Environments.3F, and if I'm not mistaken, OSGi or CDC cannot exist independently within the execution environment section.

**Comment by lathapatil** [comment]
@laeubi I have received some concerns from my colleagues regarding the EEs displayed here, which are not grouped based on EE's name like before and are now scattered, especially the OSGI and CDC ones.

> ![image](https://private-user-images.githubusercontent.com/130035155/323928014-10d2d374-d7c3-41e3-8871-59fcf776e5f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MTQ2MDEsIm5iZiI6MTcxNDcxNDMwMSwicGF0aCI6Ii8xMzAwMzUxNTUvMzIzOTI4MDE0LTEwZDJkMzc0LWQ3YzMtNDFlMy04ODcxLTU5ZmNmNzc2ZTVmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNTMxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODg5MzYxMjJhYjA5YTg3YTcxM2VjNTVhYWIwZDFhNmYwMGQ0ZTc0MzJmNmQwNjAzNmU2OGYyOWE0MTJmOTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kUNAlZ4HgHGiDQsh1fG6GGBonznpK4zJ5OUFH5mNVhs)


Can we have the sorted list as below or as shown in image above ?

> CDC-1.1/Foundation-1.1
> CDC-1.0/Foundation-1.0
> JavaSE-23
> JavaSE-22
> JavaSE-21
> JavaSE-20
> JavaSE-19
> JavaSE-18
> JavaSE-17
> JavaSE-16
> JavaSE-15
> JavaSE-14
> JavaSE-13
> JavaSE-12
> JavaSE-11
> JavaSE-10
> JavaSE-9
> JavaSE-1.8
> JavaSE-1.7
> JavaSE-1.6
> J2SE-1.5
> J2SE-1.4
> J2SE-1.3-NO-SOUND
> J2SE-1.3
> J2SE-1.2
> JRE-1.1
> OSGi/Minimum-1.2
> OSGi/Minimum-1.1
> OSGi/Minimum-1.0

**Comment by laeubi** [comment]
@lathapatil can you explain what concerns are expressed?

- [CDC](https://de.wikipedia.org/wiki/Connected_Device_Configuration)-1.1/Foundation-1.1
- [CDC](https://de.wikipedia.org/wiki/Connected_Device_Configuration)-1.0/Foundation-1.0

are almost always useless today showing them on the top feels not right.

**Comment by merks** [comment]
I agree, they'd be better listed last probably.

**Comment by lathapatil** [comment]
> are almost always useless today showing them on the top feels not right.

Yes. Not necessarily listing CDC on top, but the concern was to group similar EEs together. To reduce complexity, we can proceed as agreed before, sorting versions in descending order regardless of the names of EEs.
