### ISSUE TITLE
README.md / contribute out of date.

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#12]
references https://wiki.eclipse.org/PDE/Contributor_Guide which still references git.eclipse.org instead of github

**Comment by vik-chand** [comment]
Hannes had mentioned on pde-dev list "Furthermore I noticed that most of the links in the README.md at g.c/eclipse-pde/eclipse.pde.ui are outdated or point to targets that should be updated, too."

**Comment by vik-chand** [comment]
@HannesWell

**Comment by vogella** [comment]
https://github.com/eclipse-pde/eclipse.pde.ui/blob/master/CONTRIBUTING is also wrong
