### ISSUE TITLE
Unload target definition / Fallback to "Running Platform" or preference shortcut

### ISSUE THREAD

**Issue by thahnen** [eclipse-pde/eclipse.pde#1281]
I find myself working with different target platform definitions quite often and noticed some possible improvements.

When working inside the target definition editor it is nice to have the button **Set as Active Target Platform** / **Reload Target Platform** but I also need to *unload* the  target platform quite often. When switching to another target platform I just navigate to to it and open it and then click on **Set as Active Target Platform** but when I want to go back to the clean state of the *Running Platform* target definition I have to manually open the [preferences](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Fpreference_pages%2Ftarget_platform.htm) and activate it there.

It would be great if the target definition editor would feature a **Unload Target Platform** button for when this very target definition is loaded.
The other option which would maybe fit even more is to have a shortcut inside the target definition editor as well as the **Target Platform State** view that opens the preferences right at the *Plug-in Development -> Target Platform* page.
This would also be beneficial for switching between target definitions as following the shortcut would be simpler than navigating to the file, opening it and then setting it as active target platform.

**Comment by laeubi** [comment]
I think "unload" does not really make sense in the editor as it is unclear why / what it will perform, e.g. I maybe would expect it to use the previous chosen target, have no target at all or ...

But adding a button to open the preference would likely not harm and seems like a first simple improvement, do you want to propose a PR?

**Comment by thahnen** [comment]
Hey @laeubi, thanks for the response, I've created a PR for you to review it, please.
