### ISSUE TITLE
New entries for Import-Package get a version range which breaks semantic versioning

### ISSUE THREAD

**Issue by mwgmnn** [eclipse-pde/eclipse.pde#1297]
This is a result of issue #401, which solves more that was initially asked (strip micro version). It's ok from my point of view to add an upper version limit. But i suggest to exclude the next major version by replacing the ] by a ) in the returning version range to properly follow semantic versioning.

**Comment by laeubi** [comment]
@mwgmnn what version do you use? I think this was already fixed by @HannesWell recently.

**Comment by mwgmnn** [comment]
> @mwgmnn what version do you use? I think this was already fixed by @HannesWell recently.

It's Version 2024-03 (4.31.0), Build id: 20240307-1437.

Ok, sorry, i missed the pull request #1007. The actual code looks fine, so looking forward to the next eclipse version release.

https://github.com/eclipse-pde/eclipse.pde/blob/master/ui/org.eclipse.pde.core/text/org/eclipse/pde/internal/core/text/bundle/ImportPackageObject.java

**Comment by merks** [comment]
FYI, the 2024-06 / 4.32 release is now available.

**Comment by HannesWell** [comment]
> @mwgmnn what version do you use? I think this was already fixed by @HannesWell recently.

All said is correct, but for the record: This was fixed with https://github.com/eclipse-pde/eclipse.pde/pull/1212.
