### ISSUE TITLE
osgi.extender=osgi.serviceloader.registrar not found

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#1305]
My target platform has the following entries:		

````
<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location=" https://download.eclipse.org/releases/2024-06"/>
			<unit id="org.eclipse.equinox.core.sdk.feature.group" version="0.0.0"/>
			<unit id="org.eclipse.equinox.executable.feature.group" version="0.0.0"/>
			<unit id="org.eclipse.e4.rcp.feature.group" version="0.0.0"/>
			<unit id="org.eclipse.pde.spies.feature.group" version="0.0.0"/>
		</location>
````

If I start my RCP app with this target platform I get:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/a62f1b9d-165c-4ca4-8aa2-e1831c6269c8)

If I add 	org.eclipse.platform.feature.group  as a feature this error is gone but this also adds jetty to the target platform which is not desired.

How could I find out which plug-in contains the osgi.serviceloader.registrar?

**Comment by merks** [comment]
That's a bit tricky.  You can search for thing sin a profile with the repository explore.  The profile of the running IDE itself is always there and then you can search the different namespace and double click on the version to see which IU has that capability.

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/5f842888-5cb4-4035-b5d7-490adc129443)

The CBI Aggregation Analyzer also lets you use Ctrl-F to find things:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/50fdf3ba-d9a3-45a2-ac9b-b9dce54f254d)

It's all quite tricky for sure...

**Comment by laeubi** [comment]
@vogella you can leverage the new [Bundle Repositories View](https://eclipse.dev/eclipse/news/4.32/pde.php#osgirepositories) recently added:


https://github.com/eclipse-pde/eclipse.pde/assets/1331477/e34394c9-c38e-4cce-b7b0-4a7d70a9a1e0

**Comment by vogella** [comment]
Thanks @merks and @laeubi for the information and help.
