### ISSUE TITLE
E4 editr use inconsitent style for boolean parameters

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#1308]
Currently the E4 Editor looks like this:

![grafik](https://github.com/eclipse-pde/eclipse.pde/assets/1331477/32616c1f-b9e3-4d21-988a-6e1767087a5e)

Also in contrast to other things the colon `:` is missing.

I think this should be unified to always use 

`Label: [ ]`

instead of 

`[ ] Label`

**Comment by emyuans** [comment]
I'm working on this

**Comment by HannesWell** [comment]
Great. You are one of the students from CodeDays, aren't you?

Much success on this task and don't hesitate to ask for help if you need any.

**Comment by basonbang** [comment]
Hello, I had some confusion on how to access this part of the Eclipse development environment. How would we get to the E4 Editor within the UI as well as within the code itself?
