### ISSUE TITLE
Installing Execution Environment Descriptions as described in https://github.com/eclipse-pde/eclipse.pde/blob/master/docs/Execution_Environments.md not possible

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#1329]
Just tested https://github.com/eclipse-pde/eclipse.pde/blob/master/docs/Execution_Environments.md#installing-execution-environment-descriptions and this is not possible.

We should either:

- [ ] Fix whatever is broken
- [ ] Remove this part oft the documentation

@HannesWell or @akurtakov are these Execution Environment Descriptions  still used?

**Comment by akurtakov** [comment]
IIRC this has been gradually reduced till finally removed via https://github.com/eclipse-pde/eclipse.pde/issues/102
