### ISSUE TITLE
Bogus API errors reported in jdt.core workspace

### ISSUE THREAD

**Issue by jarthana** [eclipse-pde/eclipse.pde#1391]
I am seeing seemingly bogus API errors about new APIs being added in jdt.core. API baseline is set to 4.33 RC2a and the code is from  https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2887. None of the API changes the error is reporting has happened.

![image](https://github.com/user-attachments/assets/c2167a51-2695-4ded-b502-bd287812cc81)

**Comment by jarthana** [comment]
@gireeshpunathil @vik-chand

**Comment by iloveeclipse** [comment]
This is being discussed here : https://github.com/eclipse-pde/eclipse.pde/issues/1386
It is a PDE bug...

**Comment by iloveeclipse** [comment]
Workaround for now: close `org.eclipse.jdt.core.tests.builder.mockcompiler` project and clean build jdt.core.

**Comment by iloveeclipse** [comment]
Should be fixed in the next nightly build.

**Comment by HannesWell** [comment]
@iloveeclipse could you verify that this is fixed now?

**Comment by merks** [comment]
Yes, it's fixed after updating just now.
