### ISSUE TITLE
Content of org.eclipse.pde.doc.user is unstable

### ISSUE THREAD

**Issue by HannesWell** [eclipse-pde/eclipse.pde#1419]
After each new I-build and before the first change of the `org.eclipse.pde.doc.user` the pde build currently fails with:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:4.0.9:p2-metadata-default (default-p2-metadata-default) on project org.eclipse.pde.doc.user: baseline and build artifacts have same version but different contents
 [ERROR]    no-classifier: different
 [ERROR]       reference/api/index-files/index-16.html: different
 [ERROR]       reference/api/index-files/index-3.html: different
 [ERROR]       reference/api/index-files/index-5.html: different
 [ERROR]       reference/api/org/eclipse/pde/core/plugin/VersionMatchRule.html: different
```

Comparing the content shows a difference in the following lines

Local:
```
<script type="text/javascript" src="../script-dir/jquery-3.6.1.min.js"></script>
[...]
 which is the case if that version has the same <a href="https://docs.osgi.org/javadoc/osgi.core/8.0.0/org/osgi/framework/Version.html#getMajor--" title="class or interface in org.osgi.framework" class="external-link"><code>major</code></a> component and apart from that is greater than or equal to the
```
I-build:
```


<script type="text/javascript" src="../script-dir/jquery-3.5.1.min.js"></script>
[...]
 which is the case if that version has the same <a href="https://docs.osgi.org/javadoc/osgi.core/8.0.0/org/osgi/framework/Version.html#getMajor()" title="class or interface in org.osgi.framework" class="external-link"><code>major</code></a> component and apart from that is greater than or equal to the
```

The difference is `jquery-3.6.1.min.js` vs `jquery-3.5.1.min.js` and `#getMajor--"` vs `#getMajor()"`.

@akurtakov or @laeubi can you tell what's causing the difference?
Some different tooling installed on the build machines? Ubuntu vs Centos images?

[i-build-index3.html.txt](https://github.com/user-attachments/files/17156011/i-build-index3.html.txt)
[local-index-3.html.txt](https://github.com/user-attachments/files/17156012/local-index-3.html.txt)

**Comment by akurtakov** [comment]
This is different version of the javadoc tool used. According to https://bugs.openjdk.org/browse/JDK-8296619 we need 17.0.7+ Java to be used for I-build to fix that.

**Comment by laeubi** [comment]
Actually al script + CSS should be dropped before comparison for the javadoc part see:

- https://github.com/eclipse-tycho/tycho/blob/e0526b9f28d57b915ba921dec65ed5212e20a765/tycho-artifactcomparator/src/main/java/org/eclipse/tycho/zipcomparator/internal/HtmlComparator.java#L71

so either this don't work or the files are [not detected as javadoc](https://github.com/eclipse-tycho/tycho/blob/e0526b9f28d57b915ba921dec65ed5212e20a765/tycho-artifactcomparator/src/main/java/org/eclipse/tycho/zipcomparator/internal/HtmlComparator.java#L91) files.

but regarding

> and #getMajor--" vs #getMajor()".

this is not handled and we need some kind of equivalence here.

**Comment by akurtakov** [comment]
The fact that I-build shows exactly the same comparator issues https://download.eclipse.org/eclipse/downloads/drops4/I20240927-0310/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt is promising. New I-build is running with touched pde.doc to get clean build.
