### ISSUE TITLE
Compilation errors in `org.eclipse.tools.layout.spy` and `org.eclipse.ui.editors` bundles in the IDE

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1424]
Not sure whether this is related to the [split package issue](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3027) or not, but using I20240929-1800 I see compilation errors in `org.eclipse.tools.layout.spy` and `org.eclipse.ui.editors` bundles.

The reason is that the compiler can't resolve `org.eclipse.jdt.annotation` anymore.

The only way to "fix" the errors is to add `additional.bundles = org.eclipse.jdt.annotation` line to the `build.properties` for each not compilable bundle.

Without looking into PDE / JDT code I can't understand why that is needed, as both affected bundles require the bundle in question in manifests via `org.eclipse.jdt.annotation;resolution:=optional` and I have the annotation bundle in both the workspace / target platform.

For me it looks like some PDE hard-coded hack, however, I don't understand why did it work last week with build `I20240923-1800` but doesn't work this week with the new `I20240929-1800  SDK version.

I will provide patches for both bundle build files, but it would be better to understand why do we have such change first.

**Comment by laeubi** [comment]
Don't use additional bundles for this, it is a completely different purpose see:
- https://github.com/eclipse-pde/eclipse.pde/issues/1407
- https://github.com/eclipse-pde/eclipse.pde/issues/1403
- https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Feditors%2Fmanifest_editor%2Feditor.htm

**Comment by iloveeclipse** [comment]
> Don't use additional bundles for this

Which solution do you propose?

**Comment by iloveeclipse** [comment]
I mean, which **currently available** solution exists to get an error free workspace?

**Comment by laeubi** [comment]
> I mean, which **currently available** solution exists to get an error free workspace?

`jars.extra.classpath` is available "since ever" ...

**Comment by iloveeclipse** [comment]
Could you be so kind and provide the patch please? If I understand the linked ticket, currently it requires bundle file name, which is not nice as it has to be updated on every change.

**Comment by laeubi** [comment]
`jars.extra.classpath = platform:/plugin/org.eclipse.jdt.annotation` should work

**Comment by laeubi** [comment]
I [found this example](https://github.com/eclipse-pde/eclipse.pde/blob/3f973e87fd7ede513388e8ed870d1b65de438947/apitools/org.eclipse.pde.api.tools/build.properties#L27) that uses

```
jars.extra.classpath=platform:/plugin/org.apache.ant/lib/ant.jar,
   platform:/plugin/org.objectweb.asm
```
the first references a jar *inside* a bundle, the second only the bundle itself... still its odd that only you seem to seeing issues with that, the optional import is even not nice at all but should work (regardless of split packages).

**Comment by iloveeclipse** [comment]
OK, in this particular case in `org.eclipse.ui.editors` **nothing** using `jars.extra.classpath` works:

```
jars.extra.classpath=platform:/plugin/org.eclipse.jdt.annotation_2.3.0.v20240111-2306.jar
jars.extra.classpath=platform:/plugin/org.eclipse.jdt.annotation
jars.extra.classpath=platform:/org.eclipse.jdt.annotation_2.3.0.v20240111-2306.jar
jars.extra.classpath=platform:/org.eclipse.jdt.annotation
```

Only `additional.bundles = org.eclipse.jdt.annotation` works.

**Comment by laeubi** [comment]
`jars.extra.classpath=platform:/plugin/org.eclipse.jdt.annotation` is correct, you probably need to trigger update of the classpath container manually as I'm not sure this will taken automatically. If it does not work it needs to be fixed in PDE as this is used in other platform projects as well.

**Comment by merks** [comment]
Funny I don't see such an error.  Aren't the two bundles in the target platform?

![image](https://github.com/user-attachments/assets/3636d5a6-beb0-48fd-90ba-e10b7cbcbfe9)

**Comment by iloveeclipse** [comment]
> you probably need to trigger update of the classpath container manually

Tried to rebuild / close + rebuild, no way. Only IDE restart helped!

> If it does not work it needs to be fixed in PDE as this is used in other platform projects as well.

The question is still: why it worked before and why it doesn't now?

**Comment by merks** [comment]
Indeed.  Another question, why does it work for me and not for you?  The error suggests it's not in your target platform.

**Comment by iloveeclipse** [comment]
> Indeed. Another question, why does it work for me and not for you? The error suggests it's not in your target platform.

I have both annotation projects in my workspace. However, I've also tried to close them one by one, with no changes. Probably one need to restart IDE every time one changes here something...

**Comment by laeubi** [comment]
I have now updated everything to the latest but the project compiles fine and annotation project is resolved
![grafik](https://github.com/user-attachments/assets/feb16265-f5b4-46ad-bfc5-9248d6d9e95b)

> Probably one need to restart IDE every time one changes here something...

`Right Click` > `Plugin Tools` > `Update Classpath...` should be enough.

**Comment by merks** [comment]
A freshly oomph IDE with the latest SDK installed and PDE and platform UI has no errors:

![image](https://github.com/user-attachments/assets/1167ca6d-be89-4774-b4fb-84fb1ddbf26e)

**Comment by HannesWell** [comment]
> Without looking into PDE / JDT code I can't understand why that is needed, as both affected bundles require the bundle in question in manifests via `org.eclipse.jdt.annotation;resolution:=optional` and I have the annotation bundle in both the workspace / target platform.

Have you tried what happens if you require the bundle non optionally?

> > Indeed. Another question, why does it work for me and not for you? The error suggests it's not in your target platform.
> 
> I have both annotation projects in my workspace. However, I've also tried to close them one by one, with no changes. Probably one need to restart IDE every time one changes here something...

Did you change the annotation projects in any way that they maybe don't resolve anymore?
Are they listed in the `Target Platform State` view? Bundles from the workspace are shown there too:
![grafik](https://github.com/user-attachments/assets/52707c56-3221-4e85-a1e1-daae5d07051a)

Because for me everything works as well using `Build id: I20240929-1800` with the annotations in the TP.

**Comment by iloveeclipse** [comment]
Another day, another issue. I couldn't reproduce with I20240930-1800 anymore.
