### ISSUE TITLE
Unanticipated comparator errors in pde.doc in I20241002-1800

### ISSUE THREAD

**Issue by jarthana** [eclipse-pde/eclipse.pde#1427]
The report is here:

https://download.eclipse.org/eclipse/downloads/drops4/I20241002-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

Noticed we had just touched the affected bundles last week. Not sure if this is similar.
First few lines of the report:
```
Comparator differences from current build
	/home/jenkins/agent/workspace/Builds/I-build-4.34/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20241002-1800
compared to reference repo at 
	https://download.eclipse.org/eclipse/updates/4.34-I-builds

1.  eclipse.pde/org.eclipse.pde.doc.user/pom.xml
   no-classifier: different
      reference/api/deprecated-list.html: different
      reference/api/index-files/index-18.html: different
      reference/api/index-files/index-3.html: different
      reference/api/index-files/index-7.html: different
      reference/api/index-files/index-9.html: different
```

**Comment by merks** [comment]
Here are details of the differences:

[diff.txt](https://github.com/user-attachments/files/17241189/diff.txt)

**Comment by akurtakov** [comment]
That's weird so they are no longer links?

**Comment by merks** [comment]
Yes, no longer links it appears.  Maybe this change to the javadoc caused a problem/change?

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/203abf071e01c6d8f6ecd26110711457d79ec918

**Comment by merks** [comment]
It's like these offline links are not being processed properly:

![image](https://github.com/user-attachments/assets/256089ca-d9dc-4040-ac55-c04a0efdecb2)

**Comment by akurtakov** [comment]
It's another problem https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.34-I-builds/I20241002-1800/plugins/org.eclipse.platform.doc.isv_4.34.0.v20241002-0922.jar doesn't contain reference/api thus it's impossible to make it offlineLink.  Now, it's up to find why building it failed silently.

**Comment by merks** [comment]
I see.  Good we investigated and didn't just bump the version blindly!

**Comment by HannesWell** [comment]
> It's another problem https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.34-I-builds/I20241002-1800/plugins/org.eclipse.platform.doc.isv_4.34.0.v20241002-0922.jar doesn't contain reference/api thus it's impossible to make it offlineLink. Now, it's up to find why building it failed silently.

Reminds me of https://github.com/eclipse-pde/eclipse.pde/pull/1402. Maybe the output directory changed again? Maybe we should set it explicitly.

**Comment by akurtakov** [comment]
It didn't change again but the fix went only pde.docs and there were no changes in platform so it wasn't caught by now.

**Comment by HannesWell** [comment]
> It didn't change again but the fix went only pde.docs and there were no changes in platform so it wasn't caught by now.

Yes. When doing this change it was mentioned that it would probably be necessary for the other ones as well:
- https://github.com/eclipse-pde/eclipse.pde/pull/1402#issuecomment-2341976685

But since no error was shown I assumed it works in the other doc-bundles for some other magic reason.
I really wonder why this only surfaced three weeks later?
The update to `maven-javadoc-plugin` 3.10 was actually globally:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2266

Anyways. Thanks for the fix!

**Comment by akurtakov** [comment]
I-build succeeded https://download.eclipse.org/eclipse/downloads/drops4/I20241003-0820/
