### ISSUE TITLE
Prefer usage of dialogs without ? for confirmation dialogs in PDE

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#149]
Using a ? icon for confirmation dialogs is not recommended in the lateset UI guidelines for Mac and Linux and I do not see that used in Windows.

![image](https://user-images.githubusercontent.com/139910/172815016-b54120b2-72b3-4ce7-b7dc-a4b97a19ce35.png)

References: 
https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts/
https://developer.gnome.org/hig/patterns/feedback/dialogs.html

I suggest we do not use ? icons anymore in our PDE dialogs whenever possible.

**Comment by merks** [comment]
I'm not sure I follow what these links are suggesting nor what changes you are actually suggesting.  

I do wonder how those recommendations correspond to these guidelines

https://wiki.eclipse.org/User_Interface_Guidelines

Will this approach/change make PDE different from say JDT or the Platform and all the other projects?

**Comment by vogella** [comment]
The way we currently work is that we start somewhere and continue improving.

**Comment by merks** [comment]
That doesn't answer the question though.   Could you explain the improvement, perhaps with a specific example of what you plan to change so that someone other than you can understand what you plan to do and what you consider an improvement.   After all, if it's an improvement, everyone should do it and then everyone is likely to have an opinion about it...

**Comment by merks** [comment]
This is pure native Windows 10:

![image](https://user-images.githubusercontent.com/208716/172810861-2cf04a7a-b05d-43e1-ba81-7b65018ea823.png)

This uses a question mark.  So if this were PDE, it would be changed how?   One doesn't normally say yes/no in response to a statement but rather in response to a question, which is generally terminated by a question mark.  So is just the question mark removed or is a yes/no dialog deprecated?

**Comment by vogella** [comment]
The issue is only to remove the ? mark from the dialog which is not included in the WIndows UI guidelines (I finally found it): https://docs.microsoft.com/en-us/windows/apps/design/controls/dialogs-and-flyouts/dialogs

Yes / No dialogs are still fine even though I think action orientated buttons are preferrable.

**Comment by akurtakov** [comment]
The goal should be to use SWT's MessageBox directly as it already follows the underlying OS guidelines and thus Eclipse shows dialog that doesn't differ from what rest of the apps on the system show.

**Comment by vogella** [comment]
Screenshot from the UI guidelines of Microsoft.

![image](https://user-images.githubusercontent.com/139910/172813320-91d1c25a-c4d7-465d-bb60-3f9f87268e0b.png)

**Comment by merks** [comment]
That dialog has three question marks. Is that bad?

**Comment by akurtakov** [comment]
Our goal should be to defer to the OS as SWT was initially designed - "The primary design goals are high performance, native look and feel, and deep platform integration. "

**Comment by merks** [comment]
I see now where the wires got crossed! Thanks for clarifying.

**Comment by vogella** [comment]
Done for all dialogs I regulary see, will open new PR if I see others which can be updated.
