### ISSUE TITLE
Feature is not loaded with latest PDE

### ISSUE THREAD

**Issue by azoitl** [eclipse-pde/eclipse.pde#1507]
I wanted to upgrade the target platform of the RCP 4diac IDE of the Eclipse 4diac project to the latest Eclipse release. However when I then load the target platform the org.eclipse.platform feature and several of its plugins are missing in the .bundle pool directory. As I do this every 3 months I didn't expect that to happen. Please find attached my target file. Any tip what is wrong here would be greatly appreciated. 

For completeness I was using Eclipse 2024-12.

[org.eclipse.fordiac.ide.product.target.txt](https://github.com/user-attachments/files/18030910/org.eclipse.fordiac.ide.product.target.txt)

**Comment by azoitl** [comment]
I'm sorry I fear I just used the target editor wrong. Today I started from scratch with a more correct and cleaner setup. Especially using the code completion features of the source tab of the target editor (which is by the way amazing) and now everything works as it should.

**Comment by vogella** [comment]
In training sessions I see frequently the target platform state not updating and as a last resort advice to restart the IDE, which enforces the update of the target platform. Unfortunately I was never successful to create a reproducible example for missing target platform updates but my clients report that this happens on a regular basis to them.

**Comment by azoitl** [comment]
@vogella maybe as a learning that I had is that we had mixed features and products as entries in our target platform. This somehow broke things or at least broke my expectation. I just changed everything to features and cleaned up more. This helped a lot.
