### ISSUE TITLE
Adding twice --add-opens in product launch parameter is not correct transferred to the launch configuration

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#1508]
Adding the following to the product launch configuration is not taken over correctly to the launch configuration:

````
--add-opens java.base/java.util=ALL-UNNAMED
--add-opens java.base/java.lang.reflect=ALL-UNNAMED
````
![image](https://github.com/user-attachments/assets/3331bbff-f22d-4691-89b6-da07207f2050)

This ends up as the following in the runtime configuration:

````
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true --add-opens java.base/java.util=ALL-UNNAMED java.base/java.lang.reflect=ALL-UNNAMED
````
While is should be:

````
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED
````

**Comment by merks** [comment]
I expect it's much better to use this variation (without spaces but rather with =) so that nothing thinks there are two duplicate `--add-opens` arguments where one should be removed to eliminate that duplication:
```
--add-opens=java.base/java.lang=ALL-UNNAMED
```

**Comment by vogella** [comment]
Thanks @merks, that works for me.
