### ISSUE TITLE
Bundle-RequiredExecutionEnvironment is deprecated and should not be used

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#152]
Bundle-RequiredExecutionEnvironment is deprecated in the OSGi spec (see http://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module.bree) but PDE still actively adds this and uses it for the creation of new plug-ins. 

Should be update PDE to use the non-deprecated version or is this just to much work with additional value?

**Comment by HannesWell** [comment]
Isn't this a duplicate of https://github.com/eclipse-pde/eclipse.pde/issues/140?

Before a discussion is started I suggest to choose one of both issues to not split it up.

**Comment by vogella** [comment]
Marking a dup of #140
