### ISSUE TITLE
Target Editor UI freeze / taking very long when refresh a target file

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#1523]
I added an example [test.zip](https://github.com/user-attachments/files/18150360/test.zip) file which is somehow similar to our internal target file, just for the sake of reproducing the described problem.

1. Start Eclipse
2. Open the Progress View
3. Open test.target with Target Editor
4. wait until all is resolved (takes for e about 2 minutes)
5. press Refresh Button (if you click somewhere you see the ui is frozen)
6. i see the above described dialog, which then disappears
7. the more you click, the more you see the dialog
8. now i have this "ui freeze state" for about 4:30 minutes (i guess the repositories are resolved in the background)
9. after that the target platform is resolved again (which is shown in the Progress View)
10. all in all the refresh takes about 5min vs 2min of the initial resoving

_Originally posted by @phermsdorf in https://github.com/eclipse-pde/eclipse.pde/discussions/1513#discussioncomment-11580987_

**Comment by phermsdorf** [comment]
Great! Thanks a lot @laeubi .
I'll try it out next week with the nightly build.

**Comment by phermsdorf** [comment]
I tried it with the last nightly build and now the refresh button works as expected and there is no ui freeze anymore.
Thanks a lot and merry x-mas!
