### ISSUE TITLE
Starting a runtime Eclipse shows a validation error for org.apache.xml.resolver

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#158]
I'm using Eclipse SDK
Version: 2022-06 (4.25)
Build id: I20220613-1800
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.3+7
Java version: 17.0.3

and starting a runtime Eclipse via org.eclispe.pde.ui show the following validation error

![image](https://user-images.githubusercontent.com/139910/173821263-746725b3-2630-4a0b-9813-529694e39549.png)

**Comment by merks** [comment]
Sounds related to this:

https://github.com/eclipse-pde/eclipse.pde/issues/130

**Comment by vogella** [comment]
Thanks @merks 

dup of #130
