### ISSUE TITLE
PDE product editor does not retain plugin order in the configuration section

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#167]
Currently plugins are reordered from the XML representation.

**Comment by HannesWell** [comment]
Noticed that as well (a while ago).
The reason is that a HashSet is used to maintain them. I have already a half finished commit locally, so I can take care of this.
But there are a few more flaws in the editor. For example repo-references also sometimes get duplicated.

**Comment by laeubi** [comment]
> But there are a few more flaws in the editor.

One flaw after the other ;-)

> The reason is that a HashSet is used to maintain them

Using a `LinkedHashMap` sound reasonable

> I have already a half finished commit locally, so I can take care of this.

:+1:
