### ISSUE TITLE
Retire some exception environments MANIFEST.MF editor

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#170]
Do we still support of of the listed excecution environments for the BREE?
If not, we should retire the onces not, if yet, we should close this issue.

cc @akurtakov 

![image](https://user-images.githubusercontent.com/139910/174744222-b5aa1d0b-a1bf-480d-869f-d3de1a043d89.png)

**Comment by ruspl-afed** [comment]
Hi @vogella 
What do you mean by "support" here?

**Comment by akurtakov** [comment]
PDE no longer ships api tools definitions for OSGi minumum/CDC. ECJ still supports Java 1.1 or 1.2 not sure. Equinox ships profiles for these https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.osgi . 
So the real question here is should PDE still offer these in various places? Aka does it make sense to develop for e.g. pre-1.5 JVM and do everything function in such cases.

**Comment by vogella** [comment]
> Hi @vogella What do you mean by "support" here?

Do we still support development for all of these excecution environments? See @akurtakov answer.

**Comment by ruspl-afed** [comment]
> So the real question here is should PDE still offer these in various places?

The question is: What will stop working if we remove pre-1.5 JVM support from PDE?

**Comment by jarthana** [comment]
> So the real question here is should PDE still offer these in various places? Aka does it make sense to develop for e.g. pre-1.5 JVM and does everything function in such cases.

When you say "develop for", did you mean the users developing their software or the PDE development? If it's the former, which IMO is what matters, we may not be right people to make that call.

**Comment by vik-chand** [comment]
This is coming from jdt.debug 
In org.eclipse.pde.internal.ui.editor.plugin.ExecutionEnvironmentSection
	```
private Object[] getEnvironments() {
		RequiredExecutionEnvironmentHeader header = getHeader();
		IExecutionEnvironment[] envs = **JavaRuntime.getExecutionEnvironmentsManager().getExecutionEnvironments()**;
		if (header == null)
```

**Comment by vogella** [comment]
Ok, so nothing to do here for PDE.

**Comment by HannesWell** [comment]
What do you think about reversing the order of the list?
Then the new BREEs would be listed more prominent at the top and the old ones 'automatically' go down the list over time.
