### ISSUE TITLE
.exsd Schema file written by PDE: Cannot resolve the name 'serviceFactory'

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#175]
open 
`eclipse.platform.ui\bundles\org.eclipse.ui\schema\services.exsd`
=> the XML language server produces 2 errors:
`src-resolve: Cannot resolve the name 'serviceFactory' to a(n) 'element declaration' component.	services.exsd	/org.eclipse.ui/schema	line 31	Language Servers
`
```
src-resolve.4.2: Error resolving component 'serviceFactory'. It was detected that 'serviceFactory' is in namespace 'http://www.w3.org/2001/XMLSchema', 
but components from this namespace are not referenceable from schema document 'file:///C:/Users/jkubitz/2022-05-09/git/eclipse.platform.ui/bundles/org.eclipse.ui/schema/services.exsd'. 
If this is the incorrect namespace, perhaps the prefix of 'serviceFactory' needs to be changed. 
If this is the correct namespace, then an appropriate 'import' tag should be added to 'file:///C:/Users/jkubitz/2022-05-09/git/eclipse.platform.ui/bundles/org.eclipse.ui/schema/services.exsd'.
	services.exsd	/org.eclipse.ui/schema	line 31	Language Servers
```
is that a "problem" of PDE or Language server?

The issue that developers complain about: as soon as the editor is closed the problem markers disappear, and only appear again when "extension point editor" is opened.

**Comment by jukzi** [comment]
![image](https://user-images.githubusercontent.com/51790620/174982777-12561849-b98c-4c1f-aa2b-09e0f27ba6fc.png)

**Comment by HannesWell** [comment]
I suspect that is a problem of the language server.

**Comment by greg-449** [comment]
I'm getting this error on all the exsd files in my RCP.

It looks to me like the error message is correct and the exsd files written by the schema editor are invalid.

The message is saying `element ref="serviceFactory"` is referencing an element in the XMLSchema namespace when what it is really trying to do is reference an element in the target namespace.

Playing around with this, adding a namespace for the target to the `schema` and specifying it in the `ref` shuts up the message:
```
<schema targetNamespace="xxx.yyy" xmlns:target="xxx.yyy" xmlns="http://www.w3.org/2001/XMLSchema">

...

<element ref="target:serviceFactory"
```
But the rest of Schema editor doesn't understand this.

**Comment by angelozerr** [comment]
As exsd doesn't respect the full specification of XML Schema, I suspect it is the problem, that's why we decide to not validate *.exsd files with LemMinX. See issue https://github.com/eclipse/lemminx/issues/1275

We will release soon lemMinX and once release will be done, WWD could integrate it and you will benefit with this feature.

**Comment by angelozerr** [comment]
I think this issue is the same than https://github.com/eclipse-pde/eclipse.pde/issues/294

**Comment by merks** [comment]
Yes, it's the same issue.  A *.exsd resource doesn't use proper xmlns prefixing and if you try to make the validator happy and the *.exsd doesn't work anymore.  I think you need to disable this to make it stop:

![image](https://user-images.githubusercontent.com/208716/194010395-4a4efa2e-4030-4e99-bc5d-a2256321fa9d.png)

**Comment by jukzi** [comment]
but that would disable all xml checking? why does it even validate .exsd when .exsd is not (fully?) xml?

**Comment by angelozerr** [comment]
> Indeed it would and that's a shame. A *.exsd is fully XML, it's just not fully compliant with schema corresponding to the namespace that it declares. I expect it's validated because is XML content type:

@merks if I understand correctly, you would like to have XML syntax validation for *.exsd files managed by LemMinx?

**Comment by merks** [comment]
Looking at the behavior, this error seems helpful to me.

![image](https://user-images.githubusercontent.com/208716/194021087-88f3d03d-ef34-458e-a696-7e07e170b47a.png)

I doubt that anything that declares itself to be of XML content type will in practice support ill-formed XML such as the above.  And of course the biggest shame is to disable such checking for all XML...

**Comment by angelozerr** [comment]
> Looking at the behavior, this error seems helpful to me.

Ok sorry I though *.exsd files should not validated even for XML syntax error. I create a PR to fix this behavior, see my comment at 
https://github.com/eclipse/lemminx/pull/1308#issuecomment-1269595130

**Comment by angelozerr** [comment]
@merks @greg-449 @greg-449 @HannesWell @jukzi could you install again wwd which has been released and which embeds lemminx which should fix all your problems in pde and tell me if it works as your expectation. Thanks!

**Comment by jukzi** [comment]
Could not reproduce with current oomphed eclipse. org.eclipse.wildwebdeveloper.xml: 1.0.0.202210262109
thanks @angelozerr

**Comment by merks** [comment]
@angelozerr Thanks!  👍
