### ISSUE TITLE
testBug206679_247198 fails since  update to jetty 10.0.11

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#201]
Processing inclusion from feature org.eclipse.help: Bundle org.eclipse.equinox.http.jetty_3.8.100.v20211021-1418 failed to resolve.: Unsatisfied import package org.eclipse.jetty.http_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.server_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.server.handler_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.server.session_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.servlet_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util.component_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util.log_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util.ssl_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util.thread_[10.0.2,11.0.0).

/home/jenkins/agent/workspace/ep425I-unit-cen64-gtk3-java18/workarea/I20220706-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/genericTargets.xml:112: Processing inclusion from feature org.eclipse.help: Bundle org.eclipse.equinox.http.jetty_3.8.100.v20211021-1418 failed to resolve.:
Unsatisfied import package org.eclipse.jetty.http_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.server_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.server.handler_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.server.session_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.servlet_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util.component_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util.log_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util.ssl_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util.thread_[10.0.2,11.0.0).

at org.eclipse.pde.internal.build.tasks.BuildScriptGeneratorTask.execute(BuildScriptGeneratorTask.java:98)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)

**Comment by vik-chand** [comment]
@akurtakov any ideas here?

**Comment by akurtakov** [comment]
I haven't had time to look into it. My first guess is that pde.build doesn't support import of JVM packages like launching didn't support and pde.build (or tests) trims the output so that fact is hidden.

**Comment by HannesWell** [comment]
The test does not fail anymore.
