### ISSUE TITLE
Backport request for https://github.com/eclipse-pde/eclipse.pde/issues/194 to R4_23_maintenance release

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-pde/eclipse.pde#208]
With https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/397 we are upgrading jetty version in R4_23 to 10.0.11. With that we will have #194 appear on R4_23 branch. 

Requesting back port to R4_23

**Comment by vik-chand** [comment]
Fixed using https://github.com/eclipse-pde/eclipse.pde/pull/229
