### ISSUE TITLE
[API Tools] @noextend on an interface seems ignored

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-pde/eclipse.pde#213]
For example https://github.com/eclipse-platform/eclipse.platform.ui/pull/78#issuecomment-1184132749 , it looks like adding a `static final` field on an interface that is marked with `@noextend`+`@noinstantiate` still treats the addition as a possible breakage and requires a bump or an API filter.

**Comment by laeubi** [comment]
@mickaelistria the interface org.eclipse.e4.ui.workbench.UIEvents is marked as noextend/implement, but the embedded type org.eclipse.e4.ui.workbench.UIEvents.UILifeCycle is not. This might be not intentional, but API tools is not to blame here.
