### ISSUE TITLE
[API Tools] should support Declarative Services classpath additions

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#215]
The PDE(!) DS Plugin allows to set a flag to include the annotations without importing them:

**org.eclipse.pde.ds.annotations.prefs**:
```
classpath=true
dsVersion=V1_3
eclipse.preferences.version=1
enabled=true
generateBundleActivationPolicyLazy=true
path=OSGI-INF
validationErrorLevel=error
validationErrorLevel.missingImplicitUnbindMethod=error
```
but correctly fails execution if one do so see for example: https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-210/4/console

**Comment by laeubi** [comment]
This is actually cause by https://github.com/eclipse/tycho/pull/1246

**Comment by HannesWell** [comment]
> This is actually cause by [eclipse-tycho/tycho#1246](https://github.com/eclipse-tycho/tycho/pull/1246)

Can we then close this as invalid?
