### ISSUE TITLE
Removing JUnit 5 Orbit bundles will cause errors for existing projects

### ISSUE THREAD

**Issue by noopur2507** [eclipse-pde/eclipse.pde#226]
After removing Orbit bundles for JUnit 5 [PR#27](https://github.com/eclipse-jdt/eclipse.jdt/pull/27), the existing JUnit 5 clients will see errors as the bundle ids/names are now different.

Examples:

1. Create a plug-in project in a workspace using the 4.24 Eclipse build having JUnit 5 tests and bundle dependencies. Open that workspace with the latest I-Build. The bundles cannot be resolved and we see errors in the test plug-in.

2. Create a Java project in Eclipse 4.24 using JUnit 5 bundles, export it as a JAR, and then import it into the latest I-build. We get these errors.

Need to check if there are other scenarios as well that are impacted.

For this, first, we need to communicate this change to the community. 
- Add N&N entry
- Send a mail to the cross-project mailing list

Possible solutions:
- Provide multi-fix (quick fix) from the Problems view to fix the bundle names
- Have a generic solution at the Equinox level to have a mapping between the old and new plugins.
- any other better suggestions?

**Comment by noopur2507** [comment]
cc @mickaelistria

**Comment by mickaelistria** [comment]
Do I get it right that this is solely a target platform issue? Ie this case happens for projects that do use the current running IDE as target-platform (and don't have a .target that includes eg Orbit's variants of JUnit) ?

**Comment by mickaelistria** [comment]
See https://github.com/eclipse-platform/eclipse.platform.common/pull/53 . As this page is usually referenced from the N&N document, should we duplicate the info in N&N ?

**Comment by noopur2507** [comment]
> Do I get it right that this is solely a target platform issue? Ie this case happens for projects that do use the current running IDE as target-platform (and don't have a .target that includes eg Orbit's variants of JUnit) ?

Yes, that's right. And this is the default in the IDE so many users will get these errors.

**Comment by noopur2507** [comment]
> See [eclipse-platform/eclipse.platform.common#53](https://github.com/eclipse-platform/eclipse.platform.common/pull/53) . As this page is usually referenced from the N&N document, should we duplicate the info in N&N ?

We should still have an N&N entry in the JDT page about JUnit 5 changes and we can add a link to this doc/section in that entry to avoid duplicating the content.

**Comment by mickaelistria** [comment]
> We should still have an N&N entry in the JDT page about JUnit 5 changes and we can add a link to this doc/section in that entry to avoid duplicating the content.

If this is only an issue about target platform, then it's more something to document in PDE N&N. I'm on it.

**Comment by mickaelistria** [comment]
N&N doc added in https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/commit/41afbd049e26be6ccc01e8dd351f59a6da5bef0f
