### ISSUE TITLE
Replace ApiBaseline.getJavaProfilePropertiesForVMPackage()  with TargetPlatformHelper.querySystemPackages(env)

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#228]
It removes the effort in adding system packages.

The following thing should work
- Launch with latest version without the corresponding system package
- Add API baseline.

**Comment by HannesWell** [comment]
Sounds good. This will save use code and also avoids the need to maintain the `-systempackages.profile` files, which makes API forward-compatible automatically.

The only drawback I can currently think of is that the system-packages are not available if the installed VMs have a lower version that the code's EE. But then the code cannot compile and the API analysis is not necessary/possible anyways.

@vik-chand do you work on removing that or should I do that?

**Comment by vik-chand** [comment]
> Sounds good. This will save use code and also avoids the need to maintain the `-systempackages.profile` files, which makes API forward-compatible automatically.
> 
> The only drawback I can currently think of is that the system-packages are not available if the installed VMs have a lower version that the code's EE. But then the code cannot compile and the API analysis is not necessary/possible anyways.
> 
> @vik-chand do you work on removing that or should I do that?

Let me check the scenario for which this was put. If that scenario works, then either you or I could remove.
The scenario is
1) The install should not have system package for Java 19
2) Launch that install with Java 19
3) Add API baseline. ( this should work)
Also system packages should be latest ( as per Java 19)

I will try it out in Y build. Currently Y build is failing else I could have checked this today itself.

**Comment by vik-chand** [comment]
I will take this up in early M3

**Comment by vik-chand** [comment]
I have put the change in Y build. If the testing is uneventful, then I will put the change in master by tomorrow.
