### ISSUE TITLE
Update PDE e4 examples to use Model-Fragment

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#260]
https://www.eclipse.org/eclipse/news/4.20/platform_isv.php introduced the Model-Fragment registration. Maybe we should also update the PDE templates  to use this approach?

**Comment by akurtakov** [comment]
Sounds good. I know nothing about e4 thought :)

**Comment by laeubi** [comment]
@vogella do you like to propose a PR? Never was aware of any template and using the new fragment wizard instead...

**Comment by opcoach** [comment]
Good idea ! I discovered this during my last training in July...  No need to register the fragment as an extension like before ...

**Comment by vogella** [comment]
Please reopen if you plan to work on this.

**Comment by HannesWell** [comment]
> Please reopen if you plan to work on this.

@vogella I suggest we keep this open until this is either fixed or we decide this will not happen (for whatever reason) and then close this as not planned. Personally I think that just closing issues (that are clear tasks/todos like in this case) for just have less open issues does not help much. Issues can be fixed one or two or even 13 years after their creation, see for example like [Bug 325614](https://bugs.eclipse.org/bugs/show_bug.cgi?id=325614). :)
