### ISSUE TITLE
Validation dialog (when started from a launch) should have link/button to edit the launch config

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-pde/eclipse.pde#305]
Often, when I do Run As > Eclipse Application, I get the validation coming in to tell me some requirements are not resolved. In the vast majority of cases, remediation involves getting to the launch config editor to add the required deps.
It would save a lot of clicks and some time and attention if the Validation dialog had a "Edit Launch Configuration" link or button to go directly to the usual remediation place.

**Comment by Dinesh0723** [comment]
Shall we add link/button in Validation dialog that will directly open the current configuration of eclipse application.

**Comment by Dinesh0723** [comment]
@mickaelistria, please confirm if I can go ahead with the proposal as shown in the above screenshot?

**Comment by HannesWell** [comment]
Both points sounds good.

But I want to mention that with the possible automated inclusion of dependencies missing items are more unlikely and if they occure are often a sign of configuration/OSGi-Metadata problems.

Nevertheless adding the suggested link still can be helpful, so please go on.

**Comment by gireeshpunathil** [comment]
a more generic question: are there tradeoffs between a hyperlink versus a regular button?

**Comment by mickaelistria** [comment]
links are supposed to move you someplace else without changing much of the state of the application; buttons are usually more to perform an on the current state of the application without necessarily navigating someplace else.

**Comment by Dinesh0723** [comment]
The Edit launch configuration link in validation dialog directly opens the **Edit launch configuration properties** dialog for the current configuration. Is this ok and shall I go for PR? Please refer the attached video for reference,

https://github.com/eclipse-pde/eclipse.pde/assets/130960675/c222ab24-7d9b-4e18-8999-8bcb6bfe1191

**Comment by iloveeclipse** [comment]
This is nice, however it opens for me not the current launch config but **completely unrelated** launch config (probably last executed?) and that's is more confusing as helpful.

Using I20231220-0750, please fix.

**Comment by Dinesh0723** [comment]
> This is nice, however it opens for me not the current launch config but **completely unrelated** launch config (probably last executed?) and that's is more confusing as helpful.
> 
> Using I20231220-0750, please fix.

I have tested it in Eclipse version 2024-03 (4.31) with build ID I20231220-0750, and it is working fine (opens the current launch configuration every time). Please refer to the attached video,

https://github.com/eclipse-pde/eclipse.pde/assets/130960675/93f74782-54fd-480d-b202-cccbd070852e

**Comment by laeubi** [comment]
@Dinesh0723 please keep in mind that this dialog also can show up when you open a `.product` file and then press the green launch button.

**Comment by mickaelistria** [comment]
@iloveeclipse I also cannot reproduce the issue you describe. Can you please provide finer steps to reproduce?

**Comment by iloveeclipse** [comment]
I have no time trying to reproduce something that was obviously not working properly.
Please check the code and try to create test case that would break it.
I assume one simply has to have few launches, the **last one** returned by `DebugPlugin.getDefault().getLaunchManager()..getLaunches()` is shown in the dialog, not the **current** one.

https://github.com/Dinesh0723/eclipse.pde/blob/a00cb79a8b8686e8b6fd1db1ee359beda7553940/ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/PluginStatusDialog.java#L156

In my case I had a Java process launch started last, after that I've started PDE launch, it showed me bundle validation error and the link opened Java launch started before. The ODE launch was created **before** Java launch, which was created and executed **last**.

**Comment by mickaelistria** [comment]
@iloveeclipse Thanks for those details.
@Dinesh0723 Can you please try fixing this? I imagine a solution can be to add an ILaunch or ILaunchConfiguration argument to the dialog `setInput` method and use it.

**Comment by iloveeclipse** [comment]
@Dinesh0723 : ping.

**Comment by Dinesh0723** [comment]
Should (https://github.com/eclipse-pde/eclipse.pde/pull/1023) this pull request be reopened? Otherwise, I need to create a new branch and make a new pull request?

**Comment by mickaelistria** [comment]
Please create a new branch and PR. There is usually no point in reopening a PR once it's merged.
