### ISSUE TITLE
Remove "Run API analysis parallel to the build job" option from UI preferences

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#307]
IIRC @iloveeclipse planned to remvoe the "Run API analysis parallel to the build job" option from the preferences once this is stable.

Andrey, do you have time to remove it next release?

![image](https://user-images.githubusercontent.com/139910/186105793-9e9d1c42-6007-4231-98ae-33ae4b918aee.png)

**Comment by vik-chand** [comment]
@iloveeclipse  Can you try this for 4.26RC1 or 4.27M1?

**Comment by iloveeclipse** [comment]
had no time, sorry. 
@vogella : can you propose a PR **to remove UI** for setting this preference?
The preference itself is still in use for tests, they need (for simplicity) synchronous execution.
