### ISSUE TITLE
Run/ Debug Configurations tab Plug-ins

### ISSUE THREAD

**Issue by cPecican** [eclipse-pde/eclipse.pde#311]
When I am changing Start Level/ Auto-Start for some plug-ins and apply the changes, after I close and reopening the popup all the changes in the Start Level/ Auto-Start are disappearing.
**This only happens if `Only show selected` is checked.**
If I am not checking the option "Only show selected", then all of the above are working fine.

**Comment by Dinesh0723** [comment]
Could you please let me know the eclipse version.

**Comment by cPecican** [comment]
When I opened the case I was on 2022.06, now I am using 2022.12, but the behavior persist.
![image](https://github.com/eclipse-pde/eclipse.pde/assets/85338228/46510500-bb85-452a-bb10-4739b9a158e0)
Reopening the popup:
![image](https://github.com/eclipse-pde/eclipse.pde/assets/85338228/bf963090-3ea3-4254-8bec-9519d55ece59)

**Comment by mickaelistria** [comment]
Please try upcoming 4.28 release https://download.eclipse.org/eclipse/downloads/drops4/S-4.28RC2a-202306050440/

**Comment by cPecican** [comment]
Still the same behavior.

**Comment by cPecican** [comment]
I've updated my IDE to 2023.06 and still not working.
