### ISSUE TITLE
-nl parameter from product not corretly added to launch configuration

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#316]
If I add -nl de to the product, the -nl is not added to the launch configuration.

It becomes: -os ${target.os} -ws ${target.ws} -arch ${target.arch} -nl ${target.nl} -consoleLog de

Instead of 

-os ${target.os} -ws ${target.ws} -arch ${target.arch} -nl de -consoleLog 

To replicate:

1.) Create new plug-in with RCP and e4 template
2.) Add parameters -nl de to the Program Arguments
3.) Start product -> wrong value in launch

![image](https://user-images.githubusercontent.com/139910/187464436-c55670df-9398-4594-8dde-75c4d98e0007.png)

@vik-chand IIRC you worked on the product to launch configuration a while ago? Can you have a look?

**Comment by vogella** [comment]
Reproducer in https://github.com/vogella/rcp-translations, clone and import and start via com.vogella.translation.product

**Comment by HannesWell** [comment]
This is a regression from https://github.com/eclipse-pde/eclipse.pde/pull/288.

I just created a fix: https://github.com/eclipse-pde/eclipse.pde/pull/317

> If I add -nl de to the product, the -nl is not added to the launch configuration.
> 
> It becomes: -os target.os−ws{target.ws} -arch target.arch−nl{target.nl} -consoleLog de
> 
> Instead of
> 
> -os target.os−ws{target.ws} -arch ${target.arch} -nl de -consoleLog
> 

With the mentioned fix it is actually `-os ${target.os} -ws ${target.ws} -arch ${target.arch} -consoleLog -nl de`, but that should have the same effect.

**Comment by vogella** [comment]
Verfied in Eclipse SDK
Version: 2022-09 (4.25)
Build id: I20220831-1800
OS: Linux, v.5.15.0-46-generic, x86_64 / gtk 3.24.33, WebKit 2.36.6
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.3+7
Java version: 17.0.3

**Comment by HannesWell** [comment]
> Verfied in Eclipse SDK Version: 2022-09 (4.25) Build id: I20220831-1800

Great! And thank you for the report.
