### ISSUE TITLE
144 test failures in pde.build since I20220830-0600

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#318]
144 test failures in pde.build since I20220830-0600

**Comment by vik-chand** [comment]
next build should be fine after the revert

**Comment by iloveeclipse** [comment]
> next build should be fine after the revert

Revert of what? Could you please link to the root cause?

**Comment by vik-chand** [comment]
> > next build should be fine after the revert
> 
> Revert of what? Could you please link to the root cause?

Wrong branch was merged into master for jdt.core erroneously.  See commit in jdt.core repository.

**Comment by merks** [comment]
You mean this one?

https://github.com/eclipse-jdt/eclipse.jdt.core/pull/361

**Comment by vik-chand** [comment]
> You mean this one?
> 
> [eclipse-jdt/eclipse.jdt.core#361](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/361)

yes
