### ISSUE TITLE
org.eclipse.osgi requirement is not added for subclasses of EquinoxLaunchConfiguration

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipse-pde/eclipse.pde#32]
Before the change https://git.eclipse.org/r/c/pde/eclipse.pde.ui/+/186860, the `org.eclipse.osgi` requirement was added automatically to all subclasses of EquinoxLaunchConfiguration. Now this needs to be added manually for every launcher type like:
```
static {
   RequirementHelper.registerSameRequirementsAsFor( "org.eclipse.rap.ui.launch.RAPLauncher", //$NON-NLS-1$
       IPDELauncherConstants.OSGI_CONFIGURATION_TYPE );
}
```
The problem here is that RequirementHelper class is internal.

**Comment by HannesWell** [comment]
Thanks for the report.
I will have a look at this at the weekend. But I think it should be solvable soon.
