### ISSUE TITLE
Remove deprecated contents of org.eclipse.pde.ui.launcher package

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#335]
@jhonnen and @HannesWell can you handle the planned API deletion for PDE?

3. Remove deprecated contents of org.eclipse.pde.ui.launcher package
The following classes from org.eclipse.pde.ui.launcher have been deprecated since 2009 and are scheduled for removal after the September 2022 release. All classes have corresponding replacements in the org.eclipse.pde.launching bundle.
org.eclipse.pde.ui.launcher.AbstractPDELaunchConfiguration
org.eclipse.pde.ui.launcher.EclipseApplicationLaunchConfiguration
org.eclipse.pde.ui.launcher.EquinoxLaunchConfiguration
org.eclipse.pde.ui.launcher.EquinoxPluginsTab
org.eclipse.pde.ui.launcher.EquinoxSettingsTab
org.eclipse.pde.ui.launcher.IPDELauncherConstants
org.eclipse.pde.ui.launcher.JUnitLaunchConfigurationDelegate
org.eclipse.pde.ui.launcher.OSGiLaunchConfigurationDelegate
org.eclipse.pde.ui.launcher.OSGiLaunchConfigurationInitializer
org.eclipse.pde.ui.launcher.PDESourcePathProvider
For further details or to provide feedback on this change, see [bug 564563](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564563).

See eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/removals.html#planned

**Comment by HannesWell** [comment]
This was already done for the September 2022 release via https://github.com/eclipse-pde/eclipse.pde/pull/182.

Not sure if the removal was one release too early or if the documentation set the date too late, but it was done a little bit more than two years after marking it for removal, so I think the time of removal was actually ok.

**Comment by vogella** [comment]
Could you update the removal document in the commons directory? Basically moving the section from "planned deletion" to "deleted API"?

**Comment by HannesWell** [comment]
> Could you update the removal document in the commons directory? Basically moving the section from "planned deletion" to "deleted API"?

Done in https://github.com/eclipse-platform/eclipse.platform.common/pull/73.
