### ISSUE TITLE
org.osgi.service.prefs reported as missing for RCP applications

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#343]
If I create a new RCP application using the org.eclipse.e4.rcp feature and its dependencies, PDE reports org.osgi.service.prefs reported as missing

![image](https://user-images.githubusercontent.com/139910/192289122-91b0698a-4b9c-42a0-bd2d-f49f5677fe5c.png)

@HannesWell is this really missing or just reported incorrectly?

**Comment by HannesWell** [comment]
> @HannesWell is this really missing or just reported incorrectly?

I assume the automatic inclusion of dependencies is enabled in the product and in the launch config?
Is it present in the TargetPlatform?
At least version 1.1.2 (which fits the bundle version range) is present in the current SimRel repo:
https://download.eclipse.org/releases/2022-09/202209141001/plugins/

If you can provide a minimal reproducer with target-platform and product file I can debug the issue.
