### ISSUE TITLE
Rename pde.ui repository to pde

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#35]
pde.ui is a merge of pde.core and pde.ui. I suggest we rename the repo to eclipse.pde.

@vik-chand OK for you? This can be easily done by the foundation and Github will forward the old repo requests to the new one.

I did this with GEF classic without encountering any issues.

**Comment by akurtakov** [comment]
@sravanlakkimsetti FYI as change in aggregator submodules would be required for this.

**Comment by HannesWell** [comment]
Sounds reasonable.
Will this be just a rename of the existing repo so that issues/PR continue to exist just as they are with only a new URL?

**Comment by vogella** [comment]
> Sounds reasonable. Will this be just a rename of the existing repo so that issues/PR continue to exist just as they are with only a new URL?

Just a rename. For https://github.com/eclipse/gef-classic which used to be https://github.com/eclipse/gef-legacy it worked flawless, also existing PR were still intact.

@vik-chand please approve.

**Comment by vik-chand** [comment]
Looks good to me.

**Comment by vogella** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1199

**Comment by HannesWell** [comment]
> Just a rename. For https://github.com/eclipse/gef-classic which used to be https://github.com/eclipse/gef-legacy it worked flawless, also existing PR were still intact.
> 

> https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1199

Thanks!

**Comment by vogella** [comment]
Done

**Comment by vogella** [comment]
PR for aggregator

**Comment by HannesWell** [comment]
Thank you Lars!
Is this task then completed and we can close this?

**Comment by vik-chand** [comment]
I think we are done here. There was a javadoc/releng test failure issue which I have fixed ( hopefully). 

https://github.com/eclipse-platform/eclipse.platform.common/pull/13
