### ISSUE TITLE
Remove "Compute" Dependencies/ "Recompute when feature plugins change" Buttons from Feature-Editor

### ISSUE THREAD

**Issue by HannesWell** [eclipse-pde/eclipse.pde#37]
Adding Plug-ins required by included Plug-ins of a Feature as requirements to a Feature (by clicking the `Compute` in the the `Dependencies` tab) in the Feature-Editor is not necessary. P2/Tycho respectively PDE can derive them from the specifying Plug-ins. Consequently those requirements are just a duplicates, in the best case.

In the worst case the those requirements lead to resolution problems due to conflicting and unclear and/or outdated dependencies. 
Furthermore it is not clear to users if and when they should use the "Compute" Requirements button, so they likely often use it needlessly (at least I did it until I learned it is unnecessary).
Besides that the "Recompute when feature plugins change" check-box seems not to work properly because its state seems not to be persisted correctly.

Therefore the "Compute" Requirements / "Recompute when feature plugins change" should be removed entirely without replacement.
This was first suggested in https://github.com/eclipse-pde/eclipse.pde.ui/issues/26.

**Comment by vogella** [comment]
+1

**Comment by HannesWell** [comment]
The button should simply be removed. Adding a note or alike is not worth the effort. I have this on my TODO list but at the moment not with high priority 

@lppedd are you interested in providing a Pull-Request to remove the button and all functionality only used by that button?

**Comment by lppedd** [comment]
@HannesWell last year I tried setting up an Eclipse development environment (following instructions) but it failed miserably. I'll try again soon.

**Comment by lppedd** [comment]
@merks perfect, thanks! I'll allocate some time for this the following week.
