### ISSUE TITLE
Reference.getParameterList() does not properly find generic types

### ISSUE THREAD

**Issue by merks** [eclipse-pde/eclipse.pde#386]
This method `Reference.getParameterList()` was introduced for by this Bugzilla:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=332767

But it does not properly handle nesting, e.g., 

```
	public List<List<classDefault>> m2() {
		return null;	
	}
```

For this case, the method sees signature `()Ljava/util/List<Ljava/util/List<Lx/y/z/classDefault;>;>;`, will then try to look up the type `java.util.List<Lx.y.z.classDefault`, fail to find it, and not diagnose a problem.   It should return List and classDefault instead.

**Comment by laeubi** [comment]
@merks from your comment at bugzilla

> 
> For example, for a complex case like this with nested generic types:
> 
> ```
> 	public static class X1 {}
> 	public static class X2 {}
> 	public static class X3 {}
> 	public static class X4 {}
> 	
> 	static <T extends X1> T foo(List<Map.Entry<X2, X3>> arg1, List<X4> arg2) {
> 		return null;
> 	}
> ```
> 
> Isn't it the case that all these occurrences of X* be returned (as well as Map.Entry)?

I agree that most likely `X1`, `X2`, `X3`,`X4`, `Map.Entry`, and List has ti be considered when one really likes to verify the generics, for the binary compatibility I think only `List` (and probably `X1`) will be retained as generic types will be erased?!?

**Comment by merks** [comment]
The original issue isn't about binary compatibility it's about leaking types into the API.  Also, as I looked more closely, it's specifically only with respect to leaks from the return type.   I.e., if you have a public method in the API that returns something of a type that cannot be referenced elsewhere (e.g., a package protected class), then it's diagnosed as a problem.  It would seem to me that parameters of such class types also make the method unusable, but that's not diagnosed as a problem (as far as I can tell).
