### ISSUE TITLE
Add a link to github on bugzilla

### ISSUE THREAD

**Issue by Pontesegger** [eclipse-pde/eclipse.pde#391]
When creating a new issue on bugzilla, JDT/Platform/Equinox projects provide a link to Github [1]. PDE should do the same, indicating that bugzilla is deprecated

[1] https://bugs.eclipse.org/bugs/enter_bug.cgi

**Comment by mickaelistria** [comment]
Can you please open a request to webmaster to take care of this via https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues ?

**Comment by ajohnson1** [comment]
Also, please fix the link at https://www.eclipse.org/pde/support/ to point to GitHub instead of 

> Submit bugs using Bugzilla web interface.
> [Bugzilla web interface.](https://bugs.eclipse.org/bugs/enter_bug.cgi?product=PDE)

and the link https://www.eclipse.org/forums/?group=eclipse.platform.pde to instead be https://www.eclipse.org/forums/index.php/f/14/

**Comment by Pontesegger** [comment]
Bugzilla issue reported:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2211

Please open similar tickets for other locations.

**Comment by akurtakov** [comment]
I consider this one done.

**Comment by ajohnson1** [comment]
Thanks
