### ISSUE TITLE
When importing a package, don't use the micro version

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#401]
Currently in PDE when a package is missing, the Quickfix suggest to import the package and then automatically adds the exact version of that package from the target. As micro version should not change anything, it should not be part of the import, so if the package is of version `1.2.3` , the import should have a lower bound of `1.2`

**Comment by alshamams** [comment]
Hi @laeubi ,
I want to take this up. I was trying to reproduce the problem, but could not.

- The quickfix list for missing imports in the source does not include package import suggestion. Can you point me to the workflow of the quickfix that you are referring to?
- Adding an import package in the UI results in insertion of the package in the manifest but doesn't involve quick fix.( Shouldn't the same change be implemented here as well?) Or is this what you intend?

**Comment by laeubi** [comment]
You can use an existing plugin, then remove one of the require bundles / packages and then go to the place where the type is missing, if you then open quickfix you should find suggestion to import a package (maybe a bit down the list even though IMO it should be the first item).

**Comment by alshamams** [comment]
Hi, @laeubi 
I tried recreating the issue as per your suggestion using an existing plugin project creation template and removed a required bundle. I have added the screenshot of possible quick fix suggestions that came up, since I did not see an option to import the missing package in the list.

<img width="674" alt="image" src="https://github.com/eclipse-pde/eclipse.pde/assets/122432113/376ffcd4-c826-4535-83ea-b21dd10f7004">

**Comment by laeubi** [comment]
The following is for `org.eclipse.equinox.frameworkadmin` bundle of P2 repository:

1. go to the manifest and remove `org.eclipse.osgi.util` package import
2. Now you should get an error marker in the Utils class 
![grafik](https://github.com/eclipse-pde/eclipse.pde/assets/1331477/346ee968-7649-469b-b50f-c9cb4dc8a44f)
3. the Quickfix (STRG+1) should suggest to import the package again
![grafik](https://github.com/eclipse-pde/eclipse.pde/assets/1331477/8c93ce29-e34d-4955-9354-4433c7c5fb67)

To see what is described here, one needs to change that version of the package export of bundle `org.eclipse.osgi` for example from `1.1.0` in `1.1.1` in wich case the import will be after apply the quick-fix `1.1.1` while ist should be still `1.1.0` as the micro version is not important.
