### ISSUE TITLE
stale plugins persist in the workspace

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse-pde/eclipse.pde#436]
I have seen this issue in external forums with workarounds, but did not see any issues in this repo or explanations in the docs, so thought I should report here.

Issue: previously created and used plugins continue to be loaded in the newer plugin projects

steps to recreate:
 - create and run a plugin (use templates for example)
 - create another plugin and run.
 - the first plugin is loaded, and is fully usable.
 
I am not explicitly exporting or placing the first plugin in the list of available plugins. So I deem this behaviour undesired.

Any thoughts? thanks in advance! (I am new to this project, so might have missed something obvious)

**Comment by merks** [comment]
Please use [Dicussions ](https://github.com/eclipse-pde/eclipse.pde/discussions) to ask questions.

I expect your Launch Configuration (Run -> Run Configurations... and Run -> Debug Configurations...) has this which is the default

![image](https://user-images.githubusercontent.com/208716/214505964-bdcf4755-8257-497d-b10c-e886c2aa5e7f.png)

So all plug-ins in your workspace will be included in the launch.

**Comment by gireeshpunathil** [comment]
thanks @merks for the explanation! yes, I have that configuration. however, I am having trouble in running with non-default selections. I will test further and open a discussion thread, if need be. thanks again!
