### ISSUE TITLE
Many reload triggers for a target definition file

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#452]
The Target Definition editor triggered during switch to the "Definition" tab a reload of the target platform. I think it would be better to do this only if the user presses the reload or activate button.

**Comment by vogella** [comment]
Also just opening it, triggers a resolution. As this can also be a an expensive operation I would also be better if this only happens on user request.

**Comment by laeubi** [comment]
Open the target platform *is* the user request to resolve it, when should it happen otherwise? There are enough confusing buttons already so I thing we won't need a "resolve now" button.

You can edit the target anyways and this will cancel a running resolve, so basically it would be more suitable to make the Update Site location faster/more smart than punish the Editor for this, using only maven-targets or directory items resolves in seconds...

**Comment by laeubi** [comment]
By the way that's what "Reload" button basically do, it asks the location to refresh, but the IU-Locations do a full contact of all update-sites an each resolve, not only on refresh, I once tried to work around that in P2 and even asked Eclipse Infra to improve http-caching performance but it was rejected because "possible bad things" can happen ...

**Comment by vogella** [comment]
> Open the target platform _is_ the user request to resolve it, when should it happen otherwise? There are enough confusing buttons already so I thing we won't need a "resolve now" button.

Opening the target platform is the user request to edit the file. Similar to edit a pom fie in M2E or switching tabs in the M2E editor. Activating the target platform should be a separate action or only triggered if the user saves the changes.

> You can edit the target anyways and this will cancel a running resolve, so basically it would be more suitable to make the Update Site location faster/more smart than punish the Editor for this, using only maven-targets or directory items resolves in seconds...

**Comment by laeubi** [comment]
> Opening the target platform is the user request to edit the file. Similar to edit a pom fie in M2E or switching tabs in the M2E editor.

Open a pom in the editor "resolves" its dependencies and check for syntax errors, exactly what "resolve" of a target does.

> Activating the target platform should be a separate action

It is, you have to click "Set as active target platform"

> only triggered if the user saves the changes.

Validation on save is not what today developers expect from an IDE, I assume you clearly like the live updates in Java Code editing regarding syntax errors without having to press "save".

As said, the culprit is **one** specific implementation of a target location, that is the `IULocation`, it is not the editors fault that this location has devastating performance.

**Comment by merks** [comment]
There is a difference between loading the target platform and activating it.  The former starts as soon as you open the editor.  It can be slow and expensive, but as @laeubi suggests, you can't provide meaningful feedback about errors in the content without doing that...

**Comment by vogella** [comment]
@laeubi is their a bug to make IULocation faster? Do we know what is slow there?

**Comment by merks** [comment]
It’s loading all the repos and downloading all the artifacts that aren’t already in the current workspace’s pool.  That can take long.

**Comment by vogella** [comment]
> It’s loading all the repos and downloading all the artifacts that aren’t already in the current workspace’s pool. That can take long.

That would explain why it is slow initially not why it stays slows.

**Comment by laeubi** [comment]
I have described some technical details here:
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1039

Some attempts at P2 (not very successful though):
- https://github.com/eclipse-equinox/p2/issues/175
- https://github.com/eclipse-equinox/p2/issues/179
- https://github.com/eclipse-equinox/p2/issues/178
- [Bug 579186](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579186) - Missing p2.index file leads to very undesirable search order in MetadataRepositoryManager
- [Bug 579190](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579190) - p2 should support caching of p2.index file
- [Bug 579187](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579187) - Maintain a "lastmodfied" in IMetadataRepository
- [Bug 578887](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578887) - Optimize Mirror handling

You can also observe this yourself, just use a larger target and open the progress view, when open the target / resolve it then hundreds of request are made to the sites (while mostly these never change), also due how PDE works it is required to download all items even though they might never be actually used.

**Comment by vogella** [comment]
Does not look to me that we can expect progress in p2 in the near future.

I would not mind if I could use Maven dependencies for Eclipse also, but AFAIK we currently do not have a easy way to retrieve a set of plug-ins from Maven.

So the following would become a long list of Maven dependencies:

````
 <locations>
  <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
   <repository location="https://download.eclipse.org/releases/latest"/>
   <unit id="org.eclipse.equinox.sdk.feature.group" version="0.0.0"/>
   <unit id="org.eclipse.platform.sdk" version="0.0.0"/>
  </location>
````

So for now I guess we have to live with a slow Target editor. It is so annoying to me that I currently use code for editing the source while still be able to look at the Overview tab. I use this for example to add exclusions to the dependencies. Use the overview to see which undesired dependencies are added and afterwards to add them in the source tab as exclusions.

**Comment by laeubi** [comment]
You can include a dependency + all transitive ones, and you can include features, but depending on how good the pom is crafted you might or might not get good results.

Beside this it is usually not required to exclude anything (I assume from maven as IU only allows maintain an including list) but if you like you can split the targets and use the target inclusion feature, one for the maven and one for the updatesites, then you can edit both independently.

**Comment by vogella** [comment]
Thanks @laeubi for the tip with the split target file.

For the moment I will continue to use Code for text edits, this way I can easily avoid reloads of the target (which usually triggers Plug-in dependency updates and a Build).
