### ISSUE TITLE
Headless RCP build with PDE does not create correct executable project

### ISSUE THREAD

**Issue by DanielF4** [eclipse-pde/eclipse.pde#469]
Eclipse IDE for RCP and RAP Developers (includes Incubating components)
Version: 2022-12 (4.26.0)
Build id: 20221201-1913

When running a classic headless PDE build with this command line:

"c:\Program Files\Amazon Corretto\jdk17.0.6_10"\bin\java -jar "C:\Projects\softingOTX64\eclipse-rcp-2022-12"/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -application org.eclipse.ant.core.antRunner -buildfile "C:\Projects\softingOTX64\eclipse-rcp-2022-12"/plugins/org.eclipse.pde.build_3.11.400.v20220923-1253/scripts/productBuild/productBuild.xml -Dbuilder=C:\Projects\softingOTX64\Editor\\BuildProject\buildConfiguration\ -Dfile.encoding=UTF-8 -Dbatch.BD=C:\Projects\softingOTX64\Editor\\BuildProject\buildDirectory -Dbatch.eclipse="C:\Projects\softingOTX64\eclipse-rcp-2022-12" 

the build ends with "BUILD SUCCESSFUL", however there are several problems:

(1) In the resulting zip, eclipse.exe and ini (or in my case OtxEditor.exe/ini) are missing.
    No error message or hint, why.

(2) In the config.ini, in osgi.bundles=, the entry for the equinoxlauncher 

        org.eclipse.equinox.launcher@4,\

    is missing.
    (org.eclipse.equinox.launcher.win32.win32.x86_64 is present)

    I investigated a bit, and think, this is done deliberately by this java code:

        org.eclipse.pde.internal.build.ProductGenerator, printAllBundles()

        if (BUNDLE_OSGI.equals(id) || BUNDLE_EQUINOX_LAUNCHER.equals(id))
            continue;

    I guess, the idea is to re-add this entry at a later point, however I could not find out, where point that would be and why it does not happen.

(3) In my MANIFEST.MF (Bundle-RequiredExecutionEnvironment: JavaSE-XX), I set the version to JavaSE-11. I get these error messages:
    [eclipse.generateFeature] Some inter-plug-in dependencies have not been satisfied.
    [eclipse.generateFeature] Bundle org.eclipse.cdt.core.native:
    Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-17
    Host plug-in JavaSE_0.0.0 has not been found.
    ...
    
    I guess, I can ignore these, but 
    - They are confusing. 
    - They undermine our "no errors no warnings" policy.
    - Other, more important warnings/errors might be concealed by these errors.
    
    Also, I'm wondering, how these bundles with required Java 17 are created in the first place: If I set JavaSE-17 in my own MANIFEST.MF,
    the build shows the same same error message for my bundle:
    
    [eclipse.generateFeature] Bundle otxeditor:
    [eclipse.generateFeature]       Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-17
    [eclipse.generateFeature]       Host plug-in JavaSE_0.0.0 has not been found.
    
    and the build aborts here with FAIL.

Using the interactive RCP Export from the Eclipse IDE, everything is fine, but I need an automated headless build.
I attached the build.properties and an ant log on verbose level.
[productBuild.zip](https://github.com/eclipse-pde/eclipse.pde/files/10720079/productBuild.zip)
[build.zip](https://github.com/eclipse-pde/eclipse.pde/files/10720082/build.zip)

**Comment by akurtakov** [comment]
Overall, pde.build is in deep maintenance state aka "as long as it works" according to me and I would strongly recommend you to look into supported alternatives like https://github.com/eclipse-tycho/tycho for reproducible builds. Alternatively, you may decide to look into the issue yourself and propose a patch in a PR.

**Comment by laeubi** [comment]
@DanielF4 I can also only recommend to migrate your build to Tycho, pdebuild is likely missing some latest features when using it with recent platform builds.

If it is crucial to your business you can find dedicated support options for Tycho here:
https://github.com/eclipse-tycho/tycho#getting-support

**Comment by DanielF4** [comment]
In this case, please document clearly on the eclipse page (e.g. [here: help.eclipse.org](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_product_build.htm))
that "pde.build is in deep maintenance state" and might be broken and that other ways like Tycho are recommended.

**Comment by akurtakov** [comment]
This has been discussed in 2016(!) https://wiki.eclipse.org/Eclipse/PMC/Minutes_2016 March 29, 2016 notes but we clearly failed at putting proper note. I'll do that in some place but help would be more than welcome as always.

**Comment by laeubi** [comment]
I think the most valuable solution would be to simply remove pde-build from the documentation to not confuse new users.
Existing user either knows about it or use Tycho anyways.

**Comment by laeubi** [comment]
`devenv.exe` --> Tycho

You just need a single `pom.xml `(unless https://github.com/eclipse-tycho/tycho/issues/38 is finished):

https://tycho.eclipseprojects.io/doc/master/StructuredBuild.html

**Comment by DanielF4** [comment]
Ok, I'll try that. Thank you for your quick reaction. 

In your own interest, at least put a note on the website, to avoid time consuming discussions like this.

"Existing user either knows about it..."
That is true in my case, I'm currently migrating from eclipse_oxygen3, where pde.build worked.

**Comment by laeubi** [comment]
> That is true in my case, I'm currently migrating from eclipse_oxygen3, where pde.build worked.

That was release five years ago now, 20 releases later things obviously have slightly changed :-)
So I think its good to take the opportunity to also modernize your build :+1:
