### ISSUE TITLE
Move spies to dedicated Feature?

### ISSUE THREAD

**Issue by HannesWell** [eclipse-pde/eclipse.pde#472]
### Discussed in https://github.com/eclipse-pde/eclipse.pde/discussions/415

<div type='discussions-op-text'>

<sup>Originally posted by **HannesWell** November 28, 2022</sup>
As part of their migration to PDE the E4 spies have been added to the `org.eclipse.pde` feature:
https://github.com/eclipse-pde/eclipse.pde/blob/fc645e8682da8e853f21451e9833cabd9918337e/features/org.eclipse.pde-feature/feature.xml#L162-L216

Consequently everybody that uses the `org.eclipse.pde` feature now gets them installed if it is wanted or not.
Since the spies are not a core functionality of PDE I think it would be good to move them to a dedicated feature (for example `org.eclipse.pde.spies`) so that one can choose to install them in a product or not.

@vogella and @opcoach, you were the main drivers behind the migration, what do you think?</div>

**Comment by laeubi** [comment]
Why is `org.eclipse.tools.layout.spy` part of PDE? The description says " Plug-in Menu Spy" but I have no clue what a "menu plugin" should be?

Beside that it seems reasonable to having a "spy" feature .

**Comment by HannesWell** [comment]
> Why is `org.eclipse.tools.layout.spy` part of PDE? The description says " Plug-in Menu Spy" but I have no clue what a "menu plugin" should be?
> 

No idea. This happened before my time.
Maybe @vogella knows this?
