### ISSUE TITLE
Apitools: Apianalysis never finds issues if 'Bundle-ClassPath: foo.jar' is used

### ISSUE THREAD

**Issue by sratz** [eclipse-pde/eclipse.pde#473]
Consider
```
Bundle-ClassPath: foo.jar
```

If an API compatibility issue is introduced in one of those classes, it is never found.

This is because `org.eclipse.pde.api.tools.internal.model.BundleComponent` extracts `foo.jar` directly into the temp directory:
```
/tmp/foo.jar
```
It does this twice, once for the baseline and once for the current version to be compared, overwriting the previous one.
As a result, both `ArchiveApiTypeContainer`s point to the same file.

Fix: Always create a temp parent directory with a unique name and extract into this:
```
/tmp/api2738173812738123/foo.jar  #baseline
/tmp/api9238923496693495/foo.jar  #current
```

**Comment by akurtakov** [comment]
It would be nice if you can provide a PR (ideally with test ) fixing this issue as this area of the code hasn't got much attention lately.

**Comment by akurtakov** [comment]
Unfortunately the new test failed in  I-builds see https://download.eclipse.org/eclipse/downloads/drops4/I20230214-1800/testresults/html/org.eclipse.pde.api.tools.tests_ep427I-unit-cen64-gtk3-java19_linux.gtk.x86_64_19.html :
```
Cannot invoke "org.eclipse.pde.api.tools.internal.provisional.model.IApiBaseline.getApiComponent(String)" because "baseline2" is null

java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.api.tools.internal.provisional.model.IApiBaseline.getApiComponent(String)" because "baseline2" is null
at org.eclipse.pde.api.tools.model.tests.ApiBaselineTests.testIdenticalNestedJarFileNamesAreHandledCorrectly(ApiBaselineTests.java:232)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
```

**Comment by iloveeclipse** [comment]
@sratz : could you please check the new test, if that is a test or production code issue and provide a fix accordingly?

**Comment by sratz** [comment]
> @sratz : could you please check the new test, if that is a test or production code issue and provide a fix accordingly?

Hmm, strange.
The test runs just fine on PDE CI instance:
https://ci.eclipse.org/pde/job/eclipse.pde/job/master/lastBuild/testReport/org.eclipse.pde.api.tools.model.tests/ApiBaselineTests/testIdenticalNestedJarFileNamesAreHandledCorrectly/

I wonder what's different on the I-Build run?

**Comment by sratz** [comment]
OK, got it: I-build releng CI executes tests based on packaged bundle .jars, PDE CI instance based on the source repo.

Forgot to add the newly added test resources to `build.properties` so they were never packaged in the `.jar`.

Fix: #476

**Comment by iloveeclipse** [comment]
Thanks, merged. Not closing yet, just waiting confirmation from the next build.

**Comment by iloveeclipse** [comment]
Works fine in https://download.eclipse.org/eclipse/downloads/drops4/I20230215-1800/testResults.php
