### ISSUE TITLE
[mac][win] URI is not hierarchical / Intermittent failure in 1 platform (testTwoVersionsOfSameBundleBundlesInfo,testTwoVersionsOfSameBundleConfigIni)

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#480]
org.eclipse.pde.ui.tests.launcher.PluginBasedLaunchTest | testTwoVersionsOfSameBundleBundlesInfo | Error | URI is not hierarchical                                                                           java.lang.IllegalArgumentException: URI is not hierarchical                                                  	at java.base/java.io.File.<init>(File.java:420)                                                  	at  org.eclipse.pde.ui.tests.launcher.PluginBasedLaunchTest.testTwoVersionsOfSameBundleBundlesInfo(PluginBasedLaunchTest.java:883)                                                  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)                                                  	at  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)                                                  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)                                                  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)                                                  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)                                                  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)                                                  	at

**Comment by laeubi** [comment]
This can also be seen here:
https://github.com/eclipse-pde/eclipse.pde/runs/12359056671
