### ISSUE TITLE
Dark mode in e4 example application not working (on Windows)

### ISSUE THREAD

**Issue by Mailaender** [eclipse-pde/eclipse.pde#485]
On Windows 10 in the Eclipse IDE for RCP and RAP developers create a sample app using:
> File - New - Plugin Project - Create rich client application? (x) Yes - Eclipse RCP Application

![image](https://user-images.githubusercontent.com/756669/220722144-1e8bda1c-6e33-43aa-9a0d-b2a8682d746f.png)

Windows is dark, Explorer is dark, Eclipse is dark, the example application isn't. Not sure how to fix it.

**Comment by merks** [comment]
You'd need to create a much richer application that installs/include the theming support and then also configure the default theme to be the dark theme.  Perhaps this post helps:

https://stackoverflow.com/questions/70714166/how-to-include-eclipse-themes-in-an-eclipse-rcp-application
