### ISSUE TITLE
Autocomplete for build.properties

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#503]
Currently there is no auto-completion for `build.proeprties` files in the source tab.

**Comment by gireeshpunathil** [comment]
@laeubi - @alshamams and I would like to investigate this. having a quick look at the auto-completion feature elsewhere, I see there are three parts to it:

 - auto-complete a partially written properly
 - provide the specification of the property as a help text
 - provide a list of potential values to the fully qualified property
 
I wonder whether:

 - do all 3 make sense here? 
 - should all 3 go in one PR?

**Comment by laeubi** [comment]
Of course it is good to help the user as much as possible, so it depends a bit on the property itself, e.g. `additional.bundles` property might offer autocompletion for available bundles in the target state if the user asks for completion of the value.

As the very minimum "auto-complete a partially written properly" should be added, while others might be provided in separate PRs but this is at your own choice.

**Comment by gireeshpunathil** [comment]
@laeubi - PR raised; pls have a look when you get time. thanks!
