### ISSUE TITLE
ArchiveApiTypeContainer memory leak

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#510]
After editing hundrets of Manifests in the Platform workspace eclipse got stuck in Garbage collection. GC could not free any memory but 2GB limit was reached. 
![image](https://user-images.githubusercontent.com/51790620/225611870-705d799e-19d3-4dd3-9f45-cd3aa10ce6de.png)
Everything got extremly slwo and i had to restart eclipse.
i took a heapdump, but unfortnuatly it is so big that VisualVm seems to be unable to compute the gc root. Feels like there is a lot memory stuck in the ZIpFileSystem:
![image](https://user-images.githubusercontent.com/51790620/225613999-873d2836-6edd-47ef-b6d8-6c1fe85011c5.png)
![image](https://user-images.githubusercontent.com/51790620/225613140-a1bb0836-3778-45bc-8b1d-471e989007ef.png)
I took a JDK Mission Control memory allocation sampling during my work, and that reveals ZIpFileSystem is used during API analysis in PDE's 
org.eclipse.pde.api.tools.internal.model.ArchiveApiTypeContainer$ArchiveApiTypeRoot.getContents():105

![image](https://user-images.githubusercontent.com/51790620/225614528-548cc9b8-4d68-4987-b841-7eaf8903f5c5.png)

**Comment by jukzi** [comment]
@merks 
i guess the problem is that org.eclipse.pde.api.tools.internal.model.ArchiveApiTypeContainer.getLocation() creates FileSystems without ever closing it (#357).

**Comment by laeubi** [comment]
@jukzi [JProfiler](https://www.ej-technologies.com/products/jprofiler/overview.html) should be able to work with large heapdumps (you can get a 30day trial).

**Comment by jukzi** [comment]
as you can see in the screenshots there are  340 ZipFileSystem instances - so it's not always the same.

**Comment by iloveeclipse** [comment]
A, OK, so it is not jrt system as I've assumed, but one for each bundle in the target I assume. This is most likely similar to the problem I saw in JDT, where a zip FS was created only to create a `Path` object: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/a6e2bf82e35ba9868130c213f634801f3d9df30a

The fix should be similar.

**Comment by jukzi** [comment]
yet i am not sure if this is the one and only leak.
I loaded the dump in yourKit, and thats estimates to DelaDataTree - may  be also a problem in the autobuilder
![image](https://user-images.githubusercontent.com/51790620/225633183-3998f65e-7d44-4ef6-892a-314094511336.png)
![image](https://user-images.githubusercontent.com/51790620/225634193-80a99c80-c8b4-4483-af29-5b9c7a0ddcd7.png)

@laeubi maybe you can take a look in the heapdump with the tool of your choice:
heapdump-1678962587054.zip
https://securetransfer.ssi-schaefer.com/download/cc296b3f-41ca-42e2-be2d-70376aa1ea29 (670 MB)

**Comment by jukzi** [comment]
Also JMK says memory is rather distributed among classes:
![image](https://user-images.githubusercontent.com/51790620/225640109-cc7a1373-a30d-49d2-b5d5-a5f74202bf69.png)
but on the other side when i filter for PDE it shows huge amount of memory used:
![image](https://user-images.githubusercontent.com/51790620/225640546-64a40863-7b92-4476-9530-bf00fdec92a3.png)

**Comment by laeubi** [comment]
If I look at the biggest object there is a `org.eclipse.core.internal.dtree.DeltaDataTree` that occupies > 700 MB of retained size.:

![grafik](https://user-images.githubusercontent.com/1331477/225647597-925241f5-91d2-45af-8caa-f36da49fa419.png)

**Comment by laeubi** [comment]
ZifFIleSystem itself looks quite innocent with a retained size of 32 MB
ArchiveApiTypeRoot retains 127 MB but has > 22.000 instances and retained in the ApiModelCache with claims to use a LRU caching aproach...

**Comment by merks** [comment]
@jukzi  You're referring to the calls to getJarFileSystem which says `The caller should not close returned {@link FileSystem} as it might be shared with others.`?  Yes, it's "only" used to create a Path but it's a Path within the zip to access the contents of files within the zip.  I expect that a full API analysis would involve many hundreds of jars that are in the API baseline...

**Comment by jukzi** [comment]
> @jukzi You're referring to the calls to getJarFileSystem

@merks no, i was concerned about the `java.nio.file.FileSystems.newFileSystem()` which creates a new File System every time.
However i now think it would create a JrtFileSystem and not a ZipFileSystem, so it was not the cause of this issue (still feels wrong)

i am closing this issue as the DeltaDataTree think was improved and yet i have not seen this issue again.
