### ISSUE TITLE
arbitrary behavior for export package dialog

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse-pde/eclipse.pde#534]
steps to reproduce:

 - create a plugin project
 - open design editor
 - select `runtime` and click add
 - toggle the `Show non-java packages` a couple of times
 - repeat this with selecting and deselecting items in the list
 - watch the behavior of `Add` button

I see arbitrary behaviors for the `Add` button, w.r.t being enabled / disabled.

**Comment by vik-chand** [comment]
Nice catch! That's a bug. I can recreate it too

**Comment by gireeshpunathil** [comment]
relevant code: https://github.com/eclipse-pde/eclipse.pde/blob/91ab8626d037671ea7d5a7009db6378d3eeae46d/ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/editor/plugin/ExportPackageSection.java#L383-L434

I am unable to locate the code pertinent to the button and its selection change callback, so not sure if this is an in-built behaviour of the `ConditionalListSelectionDialog` class or not.
