### ISSUE TITLE
BREE not complete in the MANIFEST.MF editor

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#543]
To test:

Import project org.eclipse.core.commands from platform.ui into your WS

Open MANIFEST editor, select Overview and press Add.

All good.

![image](https://user-images.githubusercontent.com/139910/228810480-f38f0058-467b-4623-8c78-5de3bb74549c.png)

Now remove the existing entry and press Add again.

Not good.

![image](https://user-images.githubusercontent.com/139910/228810635-81f1fc5c-f101-4721-9d3b-04d1aa556ccb.png)

@HannesWell @laeubi  did we change something here recently?

**Comment by vogella** [comment]
And now I cannot reproduce anymore.....

**Comment by HannesWell** [comment]
> @HannesWell @laeubi did we change something here recently?

Not really. But I have to admit that I don't really understand what the problem was you were facing?
