### ISSUE TITLE
Add onboarding support for PDE perspective

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#557]
We should also add onboarding support similar to the resource perspective.

See https://github.com/eclipse-platform/eclipse.platform.ui/issues/633

I would suggest:

Ctrl+1
Show Keybindings (Maybe, not sure if that is really a killer one)
New (for the new Wizard)

And maybe "New Plug-in project", not sure

@HannesWell @laeubi which commands would you like to see?

**Comment by vogella** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/676#issuecomment-1491774438 for screenshots.

**Comment by laeubi** [comment]
The usual shortcuts are
- New Plugin Project
- New Feature Project
- New Product Definition 
- New Target Definition

I don't think that "New (for the new Wizard)" is good for anything as it is usually overcrowded with lots of stuff unrelated to plugin development.

Also there are Template Project Wizards, that would be maybe even more useful for users than starting something completely new... but that's not limited to PDE. Currently they are only shown as a very last step to the user in the creation wizards.

**Comment by HannesWell** [comment]
Christoph's list looks good to me.

> Also there are Template Project Wizards, that would be maybe even more useful for users than starting something completely new... but that's not limited to PDE. Currently they are only shown as a very last step to the user in the creation wizards.

AFAICT you can usually select a template in the end of for example the New Plugin Project wizard. So that would automatically be covered.

**Comment by vogella** [comment]
@BeckerWdf can you help with the background image?

**Comment by laeubi** [comment]
> AFAICT you can usually select a template in the end of for example the New Plugin Project wizard. So that would automatically be covered.

I first need to enter a lot of stuff (and can depending on my selection select an example), a more user centric way would be to first select an example:

- create a service
- create an E4 Application
- create a Menu handler
- ....

then I'm asked for the example details and maybe review the project details.

**Comment by BeckerWdf** [comment]
> @BeckerWdf can you help with the background image?

Sure.

**Comment by vogella** [comment]
Looks like we do not have individual commands for the PDE new commands. AFAICS the quick access also adds entries for the new wizard links but they are not available as individual commands. So I start with only the Quick Access link and a guiding text that DnD is support as we do in JDT and resource perspective. @BeckerWdf could add a image so that we have already a minimal display for the PDE perspective.
