### ISSUE TITLE
PDE Javadoc issue in I20230405-1800

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#565]
https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800/compilelogs/pde.doc.user.javadoc.txt

../../../eclipse.pde/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/RequiredPluginsClasspathContainer.java:18: error: package aQute.bnd.build does not exist
import aQute.bnd.build.Project;
                      ^
../../../eclipse.pde/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java:16: error: package aQute.bnd.build does not exist
import aQute.bnd.build.Container;
                      ^
../../../eclipse.pde/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java:17: error: package aQute.bnd.build.Container does not exist
import aQute.bnd.build.Container.TYPE;
                                ^
../../../eclipse.pde/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java:18: error: package aQute.bnd.build does not exist
import aQute.bnd.build.Project;
                      ^
../../../eclipse.pde/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java:19: error: package aQute.bnd.build does not exist
import aQute.bnd.build.Workspace;
                      ^
../../../eclipse.pde/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java:20: error: package aQute.bnd.osgi does not exist
import aQute.bnd.osgi.Constants;
                     ^
../../../eclipse.pde/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java:21: error: package aQute.bnd.osgi does not exist
import aQute.bnd.osgi.Processor;
                     ^
../../../eclipse.pde/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java:48: error: cannot find symbol
	private static Workspace workspace;

**Comment by laeubi** [comment]
I'll take a look, as the javadoc build is a bit special it might be that it requires an additional requirement.

**Comment by laeubi** [comment]
@vik-chand can you tell where the javadoc build is located?

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/.github/wiki/Javadoc-validation#expected-flow - I've tried to reverse engineer the build in context of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/484

Here the bnd library should be added to build classpath in  [bundles/org.eclipse.pde.doc.user/pdeOptions.txt](https://github.com/eclipse-platform/eclipse.platform.common/blob/70a7900e544c925cc7a82c9145b38dbc5f0d6620/bundles/org.eclipse.pde.doc.user/pdeOptions.txt)

**Comment by laeubi** [comment]
Okay thanks I already feared it is related to that stuff ... I'll put this on my list of build issues that need to be reworked.

**Comment by laeubi** [comment]
I also have now requested the github checks plugin so we can get javadoc issues reported with Github PRs as well:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2920

**Comment by HannesWell** [comment]
> I also have now requested the github checks plugin so we can get javadoc issues reported with Github PRs as well:
> 
Thanks for that.

If the javadoc generation can be revived and simplified, wouldn't it them make sense to move https://github.com/eclipse-platform/eclipse.platform.common/tree/master/bundles/org.eclipse.pde.doc.user into this repo? And to do the same with the other doc bundles and the correpsonding repo so that the platform.common repo can become obsolete as well?

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.common/pull/137 with the fix.

**Comment by iloveeclipse** [comment]
Fixed in https://download.eclipse.org/eclipse/downloads/drops4/I20230408-1800
