### ISSUE TITLE
standard OSGi plugin creation settings mutates the creation wizard

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse-pde/eclipse.pde#566]
steps to recreate:
1. project -> plugin project
2. select OSGi standard type
3. finish
4. create another plugin project
5. this time select Eclipse as the target type
6. the `next` button is now disabled, disallowing to create plugins from templates
7. clean / change the workspace to restore the original behaviour

probably related : https://github.com/eclipse-pde/eclipse.pde/pull/550 

/cc @laeubi

**Comment by laeubi** [comment]
I have looked into this and the problem seem when "Generate OSGi Metadata automatically" is checked, so a workaround is to first uncheck that option and then switch to "Eclipse" project type, will now look into it why it is considered even when not selected...

**Comment by vik-chand** [comment]
Let's fix this in 4.28M2
