### ISSUE TITLE
Different label and missing shortcut for "Run As > JUnit Plug-in Test"

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#579]
![image](https://user-images.githubusercontent.com/51790620/232470327-b7dabc9f-300e-42ef-853c-24b366260130.png)
currently eclipse shows me "Run as {Test-Name}" instead of Run As "JUnit Plug-in Test" 

Version: 2023-06 (4.28)
Build id: I20230413-1800

I hope that is not Intended. Run As "JUnit Plug-in Test"  + Keyboard binding was better!

**Comment by jukzi** [comment]
for curiosity the keyboard binding is still shown in the preferences with old name:
![image](https://user-images.githubusercontent.com/51790620/232471159-fa612576-e79b-4f49-b814-296b74fe96c0.png)

**Comment by iloveeclipse** [comment]
This is supposed to ba a feature, see https://github.com/eclipse-platform/eclipse.platform.debug/pull/122

However, this feature has no explanation how the actual improvement should look like / which benefits it has over the old state or what kind of bug it fixes.

@laeubi , @mickaelistria : could you please:

1) Explain the actual feature
2) If **this** is a bug at all or a feature?
3) If this is a bug - can it be fixed or the [feature](https://github.com/eclipse-platform/eclipse.platform.debug/pull/122) should be reverted?
4) If this is not a bug - please add some N&N explaining the change.

**Comment by mickaelistria** [comment]
Nothing is broken; Run As > JUnit Plug-in Test and others still work well and drive to the same result. Let's avoid alarming issue titles and try to be more descriptive, this will give better and faster results, with less stress.

Expanding shortcuts to launches is indeed a feature.

The benefit of this feature is that if a project has launch shortcuts that resolve to existing launch configs (can be multiple ones), then the launch configs are expanded and shown directly and user can directly pick the interesting one, and if there is only one, the user directly knows which launch is actually going to run. This is pretty comfortable when doing differential test analysis (ie I set up 2 launch configs for the same project, but with different deps or settings); or when a project can be bound to multiple launch configs used frequently (typically Maven launch configs are in this category when a project can run different Maven commands according to the goal).
Many plugins (m2e, buildship...) used to work around this issue by adding menu entries directly for some launches; however it appeared that the current LaunchShortcut2 APIs was intended in 1st place to allow resolution of shortcuts to particular launch and that it is done in the Launch toolbar, so it makes sense to apply it as well to context-menu.

The current behavior is not a bug and is intended, and serves well the desired goals and boosts productivity, at least for me as I use it all day long.
I do not plan to revert it nor would welcome a revert based on the current feedback which is not critical. However, we can maybe improve it to better fit the expectation and remove confusion, eg label could become "<shortcut name>: <launch name>" or "<launch name> (<shortcut name>)" if it seems better to most people.

I will write a N&N entry about it.

**Comment by laeubi** [comment]
> Explain the actual feature

As mentioned in the PR `ILaunchShortcut2` interface was not considered before by the context menu, now it does and allows what is described in the API (for example used in https://github.com/eclipse-m2e/m2e-core/pull/1309):

> This interface allows a launch shortcut to override the framework's resource and launch configuration resolution for selections (and active editors).

> If this is a bug at all or a feature?

At least PDE thinks that the already existing run configuration of the the test is a better choice than the default choice of the framework, and it seems obvious for me to offer that to the user.

if I remember correctly @mickaelistria has suggested as an alternative to show **both** the default and the "better ones".

> If this is a bug - can it be fixed or the https://github.com/eclipse-platform/eclipse.platform.debug/pull/122 should be reverted?

As per the functionality, I think its not a bug, but now we see what the implementation provides but previously was hidden, so it might be a bit surprising here but not wrong.

**Comment by szarnekow** [comment]
I wonder how this works with screenreaders. Do these usually "read" the icons or would a visually impaired developer no longer be able to distinguish a unit test from a main from a plugin test (assuming eventually all these launch shortcuts would consistently show the file/class name)?

**Comment by laeubi** [comment]
> This seems to add credit to the proposal about changing the label to also show the launch shortcut name together with the launch name.

As said, Eclipse forbid to have two launch configs that have the same name, and it could get quite lengthy then, I would then think its better to show the default item + additional ones below, that should be clear enough.

**Comment by szarnekow** [comment]
> As said, Eclipse forbid to have two launch configs that have the same name,

I might not really get it: The label is changed to the test-class as of now. If that would be done consistently, it would be the same label for plug-in and regular unit tests, no?

**Comment by mickaelistria** [comment]
> The label is changed to the test-class as of now

Not exactly, it's changed to the existing launch configuration name; which is created and derived from the test-class one 1st run of the action; if one has another "plain" jUnit launch config for the test class, it would have a different name; if generated, it's likely the classname suffixed by `(1)` (which is not great either)

**Comment by laeubi** [comment]
> I might not really get it: The label is changed to the test-class as of now. If that would be done consistently, it would be the same label for plug-in and regular unit tests, no?

You can try it out :-)

Here I started the same test twice one as Junit and once as Junit Plugin Test, the second one gets a `(1)` added and I can't name both items the same afterwards:

![grafik](https://user-images.githubusercontent.com/1331477/232489497-ee4538b7-f436-46c3-9d98-1b888bfcb6ee.png)

**Comment by mickaelistria** [comment]
I suggest https://github.com/eclipse-platform/eclipse.platform.debug/pull/127 to at least fix the label issue (shortcut is not in the scope of this patch at the moment). I don't think a lengthy label is a real issue in practice.

**Comment by szarnekow** [comment]
This ticket is still about this menu, right?

https://user-images.githubusercontent.com/51790620/232470327-b7dabc9f-300e-42ef-853c-24b366260130.png

**Comment by laeubi** [comment]
At laest its messy to have a Unit Test with a main that I execute as JUnit / Plugin / Java Main at the same time, I probably can also try to execute it as an Eclipse Application and as an OSGi Framework and even as a PHP test case ... But that's really far from what one should expect here...

**Comment by laeubi** [comment]
> This ticket is still about this menu, right?

Yes, but you brought up the screenreader part, so for me the question is, are you really concerned about screenreaders (and that's what leads to the other menu where no one seem to care about them), or is it just a false flag and you wanted to actually express something else (I have no idea) ...

So if one thinks (for whatever reason) there should ALWAYS be `JUnit Plug-in Test` in the menu, It could be adjusted to always show the default and show the additional ones as additional item, that is very similar to the run menu that uses a sub-menu for that purpose (what is something I'd like to avoid).

This would (hopefully) satisfy @jukzi and @mickaelistria demands and probably also screenreader users (even though no one here actually using a screenreader).

**Comment by szarnekow** [comment]
Nails it. Thank you for the summary, @mickaelistria
