### ISSUE TITLE
Update PDE perspective icon to look like the new onboarding icon

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#583]
The onboarding icon of PDE look much nicer, we should also update the perspective icon. 

@BeckerWdf WDYT?

Maybe we could dare to use gray-scaled icons also here? Or would that clash with the other Windows95 style icons?

**Comment by laeubi** [comment]
> Maybe we could dare to use gray-scaled icons also here? Or would that clash with the other Windows95 style icons?

1. we have the [style guide that recommends how to design icons](https://eclipse-platform.github.io/ui-best-practices/#icons)
> The icons should have a clean elegant feel with rich but subtle color and lighting
2. On they system color scheme (what uses a grey background) gray on gray is really hard to read
3. Given the "enormous" default size of 16x16 pixels, it is already hard to distinguish the icons **with** colors, without them we can also simply switch to a grey rectangle for all of them as its then nearly impossible to understand them

**Comment by BeckerWdf** [comment]
> > Maybe we could dare to use gray-scaled icons also here? Or would that clash with the other Windows95 style icons?
> 
> 1. we have the [style guide that recommends how to design icons](https://eclipse-platform.github.io/ui-best-practices/#icons)
> 
> > The icons should have a clean elegant feel with rich but subtle color and lighting
> 
> 2. On they system color scheme (what uses a grey background) gray on gray is really hard to read
> 3. Given the "enormous" default size of 16x16 pixels, it is already hard to distinguish the icons **with** colors, without them we can also simply switch to a grey rectangle for all of them as its then nearly impossible to understand them

I agree. We should stick to the style guide.
Once we have "icon packs" we may experiment with gray scale icons..

**Comment by BeckerWdf** [comment]
> we should also update the perspective icon.

What do you have in mind. I think the perspective icon is ok and nothing needs to be changed on it.
Remember on 16x16 pixels you cannot add much detail.

**Comment by merks** [comment]
Given the same underlying image of the perspective icon is used in many other places in the IDE, in my opinion it doesn't make a lot of sense to change it...
