### ISSUE TITLE
back-porting Use the actual system-packages from the JVM for Product/Site export #284 to 4.23

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse-pde/eclipse.pde#624]
Context: recently jetty bundles were upgraded in response to security findings. When this was backported to 4.23, launch / export operations (anything that involved PDE) started to fail with reason similar to: `Unsatisfied import package java.io_0.0.0`

steps to simulate the issue:

 - create a simple plugin project - from a template.
 - open the manifest, and add `Import-Package: java.io` to it
 - save it and export it (as deployable plugins)

an error as shown below appears, and the export fails.

![image](https://github.com/eclipse-pde/eclipse.pde/assets/6447530/e12ef787-4c3d-4534-b194-2fd70765a81a)

I have performed `git bisect` to determine that [this commit](https://github.com/eclipse-pde/eclipse.pde/commit/ea34245635594625ba7a6dbbd84fe35046009b4e) will fix the issue.
I see [Validation error when launching child eclipse](https://github.com/eclipse-pde/eclipse.pde/issues/194) and [Fix system package launch validation](https://github.com/eclipse-pde/eclipse.pde/pull/221) from last year that have gone into 4.23, but [Use the actual system-packages from the JVM for Product/Site export](https://github.com/eclipse-pde/eclipse.pde/pull/284) does not look like. Unfortunately, I am unable to back-port this, as I see the pde-build repos have moved, and I see only pre-built jars and classes for the source, and I don't understand how to meaningfully back-port this.

any suggestions are appreciated!

/cc @HannesWell @vik-chand

**Comment by laeubi** [comment]
The "Export Plugins" has always had different issues and it seems no one really maintains this., so I would recommend to use Tycho instead to build your bundles / plugins.

**Comment by gireeshpunathil** [comment]
thanks @laeubi - is this supported by the IDE? I mean, are there UI driven wizards to perform tyco builds? or this has to be done manually in the command line?

**Comment by laeubi** [comment]
You can use m2eclipse or you can add a shortcut to the externals tools menu.

**Comment by HannesWell** [comment]
> You can use m2eclipse or you can add a shortcut to the externals tools menu.

While I agree with Christoph that building Plugins, Features, Products, etc. is done best with Tycho+Maven, using Tycho also requires setting up a corresponding Maven+Tycho build (i.e. at least a root `pom.xml`). If you have done that you can use m2e as described by Christoph to run the build.

> I have performed `git bisect` to determine that [this commit](https://github.com/eclipse-pde/eclipse.pde/commit/ea34245635594625ba7a6dbbd84fe35046009b4e) will fix the issue.
> I see [Validation error when launching child eclipse](https://github.com/eclipse-pde/eclipse.pde/issues/194) and [Fix system package launch validation](https://github.com/eclipse-pde/eclipse.pde/pull/221) from last year that have gone into 4.23, but [Use the actual system-packages from the JVM for Product/Site export](https://github.com/eclipse-pde/eclipse.pde/pull/284) does not look like.

Yes those are probably the changes to address your problem.

> Unfortunately, I am unable to back-port this, as I see the pde-build repos have moved, and I see only pre-built jars and classes for the source, and I don't understand how to meaningfully back-port this.

The pde.build repo still exists: https://github.com/eclipse-pde/eclipse.pde.build
As part of the merge only the master branch has been cleared, but the repo is still active (not archived) to allow maintanance back-ports like in your case.
There is already a [`R4_23_maintenance` branch](https://github.com/eclipse-pde/eclipse.pde.build/tree/R4_23_maintenance), so you can just create a PR against that branch with the commit from this repo.

But I don't know how the maintenance branches are build, does this happen on EF-infra (I have never seen that), do you build it by yourself internally at IBM?

**Comment by gireeshpunathil** [comment]
thanks @HannesWell - I will try the backport approach following your guidance.

> But I don't know how the maintenance branches are build, does this happen on EF-infra (I have never seen that), do you build it by yourself internally at IBM?

Yes, we have infra to build and distribute versions internally - to meet custom LTS requirements from consumers. But we keep things only at the binary level, so there is no fork - the source is always this.

**Comment by HannesWell** [comment]
I think this is now completed -> Closing.
