### ISSUE TITLE
Provide support for copying the location of a bundle or feature to the clipboard

### ISSUE THREAD

**Issue by merks** [eclipse-pde/eclipse.pde#676]
For orbit-simrel, when authoring maven location dependencies with BND instructions, one wants to quickly review the contents of the wrapped bundle that's produced during target resolution:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/maven-bnd

It would be very convenient to be able to quickly determine the location of a bundle to inspect that specific jar:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/0caa5dc8-a355-417b-83c3-e34384d1c8e4)

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/90826b62-cfe4-409f-a9c0-e4094ac02dad)

One way to use this then is Alt  F  .  Ctrl-V Enter, so open an editor, which could be the system editor but also works for the BND editor, which is a really great formatted view of the MANIFEST.MF:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/85058400-f8ec-4d7f-bf4b-8b2d60b2c81e)

**Comment by laeubi** [comment]
Just in case if you activate the target and search in the target platform state for your bundle you can also double-click to jump to the bundle directly.
