### ISSUE TITLE
Bnd files are wired to PDE Editor even if file assocsiactions are correct set

### ISSUE THREAD

**Issue by maho7791** [eclipse-pde/eclipse.pde#690]
Eclipse 4.28

When using Bndtools all bnd files are now defaulted to the PDE Editor. 
The files assiciations are correct set to use the Bdntools-Editor. There is also no entry in the file associations, that say that the PDE Editor is used.
I suggest to use the PDE Editor for bnd files only if the PDE nature is present. Bndtools has an own nature, for this the corresponding editors should be used.

**Comment by merks** [comment]
I think this is a duplicate of 

https://github.com/eclipse-pde/eclipse.pde/issues/672

Maybe you can answer the unanswered question on that issue?
