### ISSUE TITLE
Support for automatic manifest generation: Syntax highlighting in bnd files

### ISSUE THREAD

**Issue by mikerumpf** [eclipse-pde/eclipse.pde#701]
Currently the pde.bnd tab has no kind of syntax highlighting.

This makes reading and maintaining the content hard.

(Maybe this could be reused from the bndtools editor which offers that feature already.)

**Comment by laeubi** [comment]
> (Maybe this could be reused from the bndtools editor which offers that feature already.)

Sadly the BndEditors syntax highlight is tightly coupled to BndTools i asked @juergen-albert about that already but until now there is no progress in this regard.

**Comment by laeubi** [comment]
I'm currently looking into maybe providing a Language Server for BND Syntax:
- https://github.com/bndtools/bnd/issues/5833

@mickaelistria do you know how one would integrate LSP into Eclipse Source Pages in this case?

This is currently using `org.eclipse.pde.internal.ui.editor.MultiSourceEditor.addSourcePage(String)` that extends `TextEditor` but should probably need `ExtensionBasedTextEditor` for LSP support, can you probably help here?

**Comment by mickaelistria** [comment]
Yes, the trick is to make the Source page use ExtensionBasedTextEditor instead of just TextEditor; then all LSP or TM4E configuration should work. It's similar to what was done in m2e.
I don't think I can dedicate time to that work at the moment, sorry.

**Comment by laeubi** [comment]
Okay then I need to check if we can do this for the BND part at least, thinking a bit further `MANIFEST.MF` is similar thing that might be handled by a LS....

**Comment by mickaelistria** [comment]
Every text file format should be handled by a LS.

**Comment by laeubi** [comment]
> Yes, the trick is to make the Source page use ExtensionBasedTextEditor instead of just TextEditor

I'm currently try that out but found that `ExtensionBasedTextEditor` is actually internal API, is this intentional?

**Comment by mickaelistria** [comment]
When creating the generic editor, we tried to remain protective and to make API as little as possible, so didn't export most of its content. Now that there are clear needs from accessing this class, I think it would make sense to make it more officially public.

**Comment by laeubi** [comment]
> When creating the generic editor, we tried to remain protective and to make API as little as possible, so didn't export most of its content. Now that there are clear needs from accessing this class, I think it would make sense to make it more officially public.

What I noticed is that there are mostly two ways:

1. The official one using extension point and having stand alone editor
2. source pages in form editors

I therefore wonder if one can have a public (final) `ExtensionBasedTextEditorFormPage` that implements `IFormPage`? That would then be not to open in case of API but will allow this kind of usage even more easy (as currently one needs som tricks to configure the form). I'm just not sure where one can best place this ...

**Comment by mickaelistria** [comment]
> I therefore wonder if one can have a public (final) ExtensionBasedTextEditorFormPage that implements IFormPage?

I'm afraid it would add new requirements to org.eclipse.ui.forms from the generic editor. However, it's very likely that some people want to build minimal RCPs with editor but without forms, so I don't think org.eclipse.ui.genericeditor is the right host for this.
Is there some other bundle in Platform that already requires generic editor and forms already and that could include this particular page?

**Comment by laeubi** [comment]
> Is there some other bundle in Platform that already requires generic editor and forms already and that could include this particular page?

Thats what I meant, somwhere else that already requires generic editor (or can) and requires (or can) Forms framework...

**Comment by laeubi** [comment]
@mickaelistria I poked around a bit and surprisingly it seems that only PDE is really using the generic editor (I found some extensions in debug.ui and teams.ui) ... so there currently seems not really anything that can act as a host, one might can think about `org.eclipse.ui.genericeditor.forms` bundle even though it would be mostly contain one class for now, what do you think?

**Comment by mickaelistria** [comment]
If form depends on plain editor, then I think it'd be OK to also make it depend on generic editor.

**Comment by merks** [comment]
Consumers building minimal RCP applications might think differently, but they're not here to share their personal opinions.

**Comment by mickaelistria** [comment]
In any case, my former suggestion wouldn't work as org.eclipse.ui.forms does only depend on SWT and theme stuff, not on edtors. Adding dependency to editors there would be way beyond the purpose of forms.

**Comment by laeubi** [comment]
> Consumers building minimal RCP applications might think differently,

TextEditor is not compatible with minimal RCP application anyway because they depend on eclipse.ui / workbench :-)
