### ISSUE TITLE
Support for automatic manifest generation: Feature request: BND templates for newly created bundles

### ISSUE THREAD

**Issue by mikerumpf** [eclipse-pde/eclipse.pde#704]
Maybe a bit fancy for now, but when creating a new bundle with automatic manifest generation it would be very helpful to set up the bnd file from a set of preconfigured (project specific) templates filling in some default settings and commonly used dependencies.

For example a user could choose an e4 template which would automatically set up the necessary build path with the common eclipse/swt buildpath.

Creating and maintaining those templates would have to be done by the developers of course.

**Comment by laeubi** [comment]
@mikerumpf actually PDE already support such things

![grafik](https://github.com/eclipse-pde/eclipse.pde/assets/1331477/2d897d52-722f-4f8f-ab5f-16c8d40b921c)

but currently there are no templates for automatic manifest projects, new templates can be contributed with `org.eclipse.pde.ui.pluginContent` extension:

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Freference%2Fextension-points%2Forg_eclipse_pde_ui_pluginContent.html

to be shown it needs to have the flag `bnd` set (that seems missing from the documentation right now), so there are two options:

1. If it is general useful (like E4, basic setup, a specific test framework) it should be contributed directly to PDE
2. if it is more specific to your company, you can develop an own plugin

So maybe you can try this out and even provide a PR or give some hints about what specific setups you like to see here provided by default.
