### ISSUE TITLE
Eclipse 2023-09 M2 does not accept Let's Encrypt certificates as trusted for P2 updates

### ISSUE THREAD

**Issue by minduch** [eclipse-pde/eclipse.pde#715]
Issue is present in Eclipse 2023-09 M2 and JustJ Java 17.0.8 (plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.8.v20230801-1951/jre/bin) on Windows 11.

I don't know if it's the JVM that does it or Eclipse (IDE).

When checking for updates, the two attached dialog boxes are shown: Let's Encrypt cerificate is not trusted (or its root certificate).

<img width="272" alt="Screenshot lets-encrypt not secure" src="https://github.com/eclipse-pde/eclipse.pde/assets/28196566/f1e85606-d470-4bc4-bfce-6fbe7b0ceb7b">

<img width="170" alt="Screenshot lets-encrypt not secure - details" src="https://github.com/eclipse-pde/eclipse.pde/assets/28196566/816f05b4-b022-4d70-bf27-a03a9f93f95c">

**Comment by minduch** [comment]
Perhaps this issue is in the wrong place (eclipse.pde)?
If so, can somebody move it to the appropriate place?

**Comment by merks** [comment]
This dialog will come up for **any** website other than ones already specified/confirmed as trusted as described here:

https://eclipse.dev/eclipse/news/4.28/platform.php#trusted-authorities

The information about the certificate of the host is presented just like in a browse where you can view details about your secure https connection, including details about the certificate used for that connection.   If you get as far as this dialog, then the Java runtime did trust the certificate itself and you do have a secure connection.  That doesn't mean you should **necessarily** trust artifacts coming from that site; anyone can easily host a secure site that serves up bad things.

Note that the jars at that site are signed and are recognized as signed---I just tested that---so there is no problem here.
