### ISSUE TITLE
DS Annotations processor updates the MANIFEST.MF file in a unfriendly way, in regards to a source versioning system.

### ISSUE THREAD

**Issue by nport** [eclipse-pde/eclipse.pde#74]
The attached picture shows the result of a build. Nothing is changed in the source code, just the Eclipse version. On the right Eclipse Oxygen, on the left Eclipse 2022-03, both on Windows 10.

![DSManifestCompare](https://user-images.githubusercontent.com/6675853/166956401-352a379a-7d78-4704-add6-861111f5806c.PNG)

The ServiceComponent manifest header has been moved inside the MANIFEST.MF file, but the header value is the same. So the diff tool shows a difference, but there are no semantic changes in the manifest. 
Even if the ServiceComponent header value was not the same it would be better not to change the header position, but just update its content.

This is a general rule that should be applied while updating the MANIFEST.MF file.

This second picture shows that even in the case the ServiceComponent manifest header position is not changed, it is the order of the DS xml files that is changed after the build. On the left (Eclipse 2022-03) the order is alphabetical. 

![DSManifestCompare1](https://user-images.githubusercontent.com/6675853/166956521-6c9e2d90-3e6f-4225-92be-23e259646498.PNG)

As a general rule the pre-existing order should be preserved.

I am using tycho to build my workspace from the command line but these changes appeared after a rebuild inside eclipse.

**Comment by nport** [comment]
Just noticed that one of the above issues is the result of an explicit bugfix of bug 573557, as described in class [DSAnnotationCompilationParticipant.java](https://github.com/eclipse-pde/eclipse.pde/blob/b8fdc05299682d27de59e466ff74d2e7d05b47d3/ds/org.eclipse.pde.ds.annotations/src/org/eclipse/pde/ds/internal/annotations/DSAnnotationCompilationParticipant.java#L14).

In my opinion the xml files ordering must apply only when the Service-Component header is not present in the MANIFEST.MF. If this header is already present and the update must preserve the current xml files ordering, in particular if no changes in the xml file list is necessary.

**Comment by akurtakov** [comment]
@laeubi as you did the bugfix mentioned, what do you think?

**Comment by vogella** [comment]
After the initial change from @laeubi the order should be stable afterwards, right? Or does it still changes after the intial sorting?

**Comment by laeubi** [comment]
This is a mixture of two issues:

1. previously the order of the items was random, so there often where changes even if everything is the same, this is fixed now but triggers a change if the order was previously random and one could only recommend to accept that change for the version control to have consistent order in the future or revert/delay/assumeunchanged the file if it is absolutely necessary. 
2. PDE always adds headers at the end of the manifest file I have proposed a way to prevent this but haven't yet had time to work on it https://bugs.eclipse.org/bugs/show_bug.cgi?id=576798#c4

**Comment by nport** [comment]
> This is a mixture of two issues:

Yes, you are right

> 
> 1. previously the order of the items was random, so there often where changes even if everything is the same, this is fixed now but triggers a change if the order was previously random and one could only recommend to accept that change for the version control to have consistent order in the future or revert/delay/assumeunchanged the file if it is absolutely necessary.

The point here is that the MANIFEST.MF (and by the way the xml too) was changed during the build even if there was no changes in the source code.

What I have to do if it happens on plugins that have a stable version number? Do I have to commit the new manifest and increment the revision and release a new bundle? I have about 30 plugins in this situation.
In my opinion, to guarantee stable builds,  derived files (and in this case, from the point of view of the component list, the MANIFEST.MF is a derived file) MUST not be changed, if nothing is changed in the source code.
Some issues may arise also if different developers are using different Eclipse versions on the same project.

So, I would suggest to update (reorder) the Service-Component header content only if a component has been created/renamed/deleted inside the workspace.

> 2. PDE always adds headers at the end of the manifest file I have proposed a way to prevent this but haven't yet had time to work on it https://bugs.eclipse.org/bugs/show_bug.cgi?id=576798#c4

I did some tests. I created a new plugin project in Oxygen.3. 

1.	I created package org.acme.bundle1, imported package _org.osgi.service.component.annotations_ and exported package _org.acme.bundle1_. In this package I created _ComponentC_ and _ComponentB_.  This is the resulting MANIFEST.MF:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Bundle1
Bundle-SymbolicName: org.acme.bundle1
Bundle-Version: 1.0.0.qualifier
Automatic-Module-Name: org.acme.bundle1
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Export-Package: org.acme.bundle1
Import-Package: org.osgi.service.component.annotations;version="1.3.0"
Bundle-ActivationPolicy: lazy
Service-Component: OSGI-INF/org.acme.bundle1.ComponentC.xml,
 OSGI-INF/org.acme.bundle1.ComponentB.xml
```

2.	I moved the Service-Component header in a different position and then created component _ComponentD_. This is the resulting MANIFEST.MF:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Bundle1
Bundle-SymbolicName: org.acme.bundle1
Bundle-Version: 1.0.0.qualifier
Service-Component: OSGI-INF/org.acme.bundle1.ComponentC.xml,
 OSGI-INF/org.acme.bundle1.ComponentB.xml,
 OSGI-INF/org.acme.bundle1.ComponentD.xml
Automatic-Module-Name: org.acme.bundle1
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Export-Package: org.acme.bundle1
Import-Package: org.osgi.service.component.annotations;version="1.3.0"
Bundle-ActivationPolicy: lazy
```

As you can see even if a new component descriptor was added to the list. the DS Annotations processor has not changed the `Service-Component` header position.

3.	I imported the project in Eclipse 2020-03 and forced a rebuild (Project - Clean..). The MANIFEST.MF didn’t change:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Bundle1
Bundle-SymbolicName: org.acme.bundle1
Bundle-Version: 1.0.0.qualifier
Service-Component: OSGI-INF/org.acme.bundle1.ComponentC.xml,
 OSGI-INF/org.acme.bundle1.ComponentB.xml,
 OSGI-INF/org.acme.bundle1.ComponentD.xml
Automatic-Module-Name: org.acme.bundle1
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Export-Package: org.acme.bundle1
Import-Package: org.osgi.service.component.annotations;version="1.3.0"
Bundle-ActivationPolicy: lazy
```

4.	I added another an additional component, _ComponentA_. This is the resulting MANIFEST.MF:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Bundle1
Bundle-SymbolicName: org.acme.bundle1
Bundle-Version: 1.0.0.qualifier
Service-Component: OSGI-INF/org.acme.bundle1.ComponentA.xml,
 OSGI-INF/org.acme.bundle1.ComponentB.xml,
 OSGI-INF/org.acme.bundle1.ComponentC.xml,
 OSGI-INF/org.acme.bundle1.ComponentD.xml
Automatic-Module-Name: org.acme.bundle1
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Export-Package: org.acme.bundle1
Import-Package: org.osgi.service.component.annotations;version="1.3.0"
Bundle-ActivationPolicy: lazy
```

The Service-Component header xml are now alphabetically ordered. 

5.	Changed by hand the order of the xml files list in the MANIFEST.MF and restarted Eclipse. The order was not changed after the restart:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Bundle1
Bundle-SymbolicName: org.acme.bundle1
Bundle-Version: 1.0.0.qualifier
Service-Component: OSGI-INF/org.acme.bundle1.ComponentA.xml,
 OSGI-INF/org.acme.bundle1.ComponentD.xml,
 OSGI-INF/org.acme.bundle1.ComponentC.xml,
 OSGI-INF/org.acme.bundle1.ComponentB.xml
Automatic-Module-Name: org.acme.bundle1
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Export-Package: org.acme.bundle1
Import-Package: org.osgi.service.component.annotations;version="1.3.0"
Bundle-ActivationPolicy: lazy
```

Some comments:
* The Service-Component header position was never changed even after and update of the xml files list.
* The Service-Component header content was updated only if a modification in the list was necessary (a new component was created). The ordering took place only in this case.

So everything behaves as expeted. It is not clear to me why, in some circumstances, the Service-Component header is moved or reordered, even if the project was not modified at all. It happened to me when the I opened the workspace.

**Comment by laeubi** [comment]
> The point here is that the MANIFEST.MF (and by the way the xml too) was changed during the build even if there was no changes in the source code.

Most probably this happens when there *are* changes but in the end the *result* might look the same, e.g. when you have some build errors then currently the component.xml is removed, if you fix those it is later added back again (with probably different content).

> So, I would suggest to update (reorder) the Service-Component header content only if a component has been created/renamed/deleted inside the workspace.

That would require a lot of changes internally and I don't see much benefit from that given that is only helps in rare cases and one could just commit the new order once and in the old version there would have been changes with non deterministic order anyways.

> I created a new plugin project in Oxygen.3.

Oxygen is 5(!) years and upgrading from such an old release is likely to have some changes.

> I imported the project in Eclipse 2020-03 and forced a rebuild (Project - Clean..). The MANIFEST.MF didn’t change

As I said, rebuilding does not change anything, there are only certain action that trigger a change

> The Service-Component header xml are now alphabetically ordered.

That's exactly what is expected here

> So everything behaves as expeted. It is not clear to me why, in some circumstances, the Service-Component header is moved or reordered, even if the project was not modified at all.

See above, this sometimes happens when there is an intermediate state where actually the header was *removed* and added back later.

**Comment by nport** [comment]
> > The point here is that the MANIFEST.MF (and by the way the xml too) was changed during the build even if there was no changes in the source code.
> 
> Most probably this happens when there _are_ changes but in the end the _result_ might look the same, e.g. when you have some build errors then currently the component.xml is removed, if you fix those it is later added back again (with probably different content).
> 

The project was already imported in 2023-03 (see below) since a couple of weeks and worked on it. I reopened it and this suddently these changes appeared. I didn't change many of the involved plugins since one year.

I still was not able to reproduce this behaviour. This is similar to what is currently happening. The component xml files of certain projects (not all) sometime gets regenererated (in particular at Eclipse startup). The content is  the same, but I see a change because of bug that I reported some time ago: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565294 

> > So, I would suggest to update (reorder) the Service-Component header content only if a component has been created/renamed/deleted inside the workspace.
> 
> That would require a lot of changes internally and I don't see much benefit from that given that is only helps in rare cases and one could just commit the new order once and in the old version there would have been changes with non deterministic order anyways.
> 

I can imagine, but consider the use case where someone opens an old project with a new Eclipse version... It is really weird to see all the MANIFEST.MF file suddently change without any reason.
In any case it seems that you already perform some checks in the DSAnnotationCompilationParticipant class so probably is somewhere else. It is up to you to close this issue. If I collect additional information I will let you know.

> > I created a new plugin project in Oxygen.3.
> 
> Oxygen is 5(!) years and upgrading from such an old release is likely to have some changes.
> 

In my above examples I used Oxygen just because it is a pretty older version in respect to 2022-03. My working workspace was already upgraderd to version 2022-03 without any issue.

I used Oxygen since last year and was working great. I upgraded it a newest version to something 2019-12 (or something like this) just because the OSGi launch configurations format was changed to let it more friendly with the versioning system. Then I upgraded again to newest versions because the Maven target type was added to the target platform. Conversely the target platform after Oxygen release is working worst because sometime if I start Eclipse while I am not connected to internet, Eclipse starts to update the target platform (I don't know why!) during the build (unsuccessfully since it cannot download any bundle), and the result is that my whole workspace remains in a state where all the projects are in error because they cannot be built. But this is another isssue ;-).

> > I imported the project in Eclipse 2020-03 and forced a rebuild (Project - Clean..). The MANIFEST.MF didn’t change
> 
> As I said, rebuilding does not change anything, there are only certain action that trigger a change
> 
> > The Service-Component header xml are now alphabetically ordered.
> 
> That's exactly what is expected here
> 
> > So everything behaves as expeted. It is not clear to me why, in some circumstances, the Service-Component header is moved or reordered, even if the project was not modified at all.
> 
> See above, this sometimes happens when there is an intermediate state where actually the header was _removed_ and added back later.
