### ISSUE TITLE
testPublishAndRunSimpleProduct fails since I20220503-1930

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#75]
Probably related to pde.build repo  merged into pde repo.

The following error occurred while executing this line: /Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/build.xml:94: The following error occurred while executing this line: /Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/templates/headless-build/customTargets.xml:13: The following error occurred while executing this line: /Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/productBuild/allElements.xml:23: The following error occurred while executing this line: /Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/genericTargets.xml:112: Processing inclusion from feature org.eclipse.pde.build.container.feature: Bundle headless_1.0.0 failed to resolve.: Missing required plug-in org.eclipse.core.runtime_0.0.0.

/Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/productBuild/productBuild.xml:45: The following error occurred while executing this line:
/Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/build.xml:94: The following error occurred while executing this line:
/Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/templates/headless-build/customTargets.xml:13: The following error occurred while executing this line:
/Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/productBuild/allElements.xml:23: The following error occurred while executing this line:
/Users/genie.releng/workspace/ep424I-unit-mac64-java17/workarea/I20220503-1930/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/genericTargets.xml:112: Processing inclusion from feature org.eclipse.pde.build.container.feature: Bundle headless_1.0.0 failed to resolve.:
Missing required plug-in org.eclipse.core.runtime_0.0.0.

at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:582)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)

**Comment by iloveeclipse** [comment]
@vogella : could you please provide a fix for the test fail?

**Comment by akurtakov** [comment]
Another (and more likely) reason to investigate is direct usage of osgi bundles in Equinox which we have seen needed adjustments in various places.

**Comment by vogella** [comment]
> @vogella : could you please provide a fix for the test fail?

Sorry no, I don't see how this can be related to the move and have no knowledge about the usage of the pde build. I also would guess that is more related to the Equinox changes but still would have no idea how the PDE build works.

**Comment by vogella** [comment]
Thanks @akurtakov for working on this.

**Comment by vik-chand** [comment]
Awesome @akurtakov
