### ISSUE TITLE
Target file - Remove the need to specify a 0.0.0 version

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#757]
Currently lots of my target files so not specify a specific version, e.g.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target-platform">
	<locations>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/releases/latest"/>
			<unit id="org.eclipse.equinox.compendium.sdk.feature.group" version="0.0.0"/>
			<unit id="org.eclipse.equinox.core.feature.feature.group" version="0.0.0"/>
		</location>
	</locations>
</target>
```
Would be nice if we could leave out version="0.0.0" in the file and use 0.0.0 as default if not specified in the file.

**Comment by HannesWell** [comment]
Looks like this is a recurring topic: https://github.com/eclipse-pde/eclipse.pde/discussions/405

But I agree with you, I also often had the impression that it is unnecessary. And it looks like relatively simple to implement in `IULocationFactory`. Of course Tycho needs to be adapted as well, but it also should be similar simple.

@laeubi's suggestion to also support this in the UI also seems reasonable to me that one can select that as well.
