### ISSUE TITLE
ClasspathUpdaterTests fail on Java 21

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#764]
See https://download.eclipse.org/eclipse/downloads/drops4/I20230922-0140/testresults/html/org.eclipse.pde.ui.tests_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html

```
Classpath entry for JavaSE-17 is missing

java.lang.AssertionError: Classpath entry for JavaSE-17 is missing
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.pde.ui.tests.classpathupdater.ClasspathUpdaterTest.findClasspathEntry(ClasspathUpdaterTest.java:202)
at org.eclipse.pde.ui.tests.classpathupdater.ClasspathUpdaterTest.assertClasspathAttribute(ClasspathUpdaterTest.java:174)
at org.eclipse.pde.ui.tests.classpathupdater.ClasspathUpdaterTest.test_ChangeSourceAttachment(ClasspathUpdaterTest.java:139)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:276)
```

**Comment by HannesWell** [comment]
@haubi can you have a look at this?
If I select a JDK 20 (I have 21 not yet available) as default JVM the test still passes, so I assume the only JDK available in the workspace must be greater 17 in order to reproduce this failure.

**Comment by iloveeclipse** [comment]
See errors reported by API tooling on https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1439 and https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1436.

They both run on Java 21 on Jenkins and both show same API errors, all reported on enums defined in JDT.

As I've wrote on https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1436, I suspect a problem with classpath resolving in API tooling.

It looks like if the API baseline would see java.lang.Enum from Java 8 or 11 in the **current** API (why???) and compare it with java.lang.Enum from Java 17 **in the API baseline** where it **additionally** implements Constable (since Java 12).

So it would be as if PDE is not able to recognize Java 21 as valid JDK and fails back to Java 11 (or 8). 
This test complains that `Classpath entry for JavaSE-17 is missing` which is the reason why I'm assuming we have a bug in PDE.

**Comment by laeubi** [comment]
> It looks like if the API baseline would see java.lang.Enum from Java 8 or 11 in the current API (why???) 

It is possible that the baseline is still at Java 11 because the bundle was not bumped before the switch to Java 17 ([baseline repo](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/c2b94f8c87b72fb94f72285417f91bbe88d8bdf4/eclipse-platform-parent/pom.xml#L143C32-L143C102) is https://download.eclipse.org/eclipse/updates/4.29/R-4.29-202309031000/) ... or Java 17 could not be mapped and then JDT uses an older JDK, but @vik-chand is the API tools expert here.

> So it would be as if PDE is not able to recognize Java 21 as valid JDK

Just to be clear PDE delegates all work to "recognize" JDKs to JDT ;-)

What I could think about is that maybe API tools are used here before the Java 21 support (it uses currently https://download.eclipse.org/eclipse/updates/4.30-I-builds/ ) *or* we need to raise a version range somewhere in PDE so it is forced to use a more recent JDT version.

**Comment by HannesWell** [comment]
I'm not sure if this is relevant, but there are some places where Java-17 is hard-coded.
But it could be that this is only used as fall-back and never really executed in this case.

https://github.com/eclipse-pde/eclipse.pde/blob/a6601a59dbb0384bb241f4c0ec4dff470f4d2363/apitools/org.eclipse.pde.api.tools.tests/src/org/eclipse/pde/api/tools/model/tests/TestSuiteHelper.java#L405-L412

And here it is even Java-1.6 ...
https://github.com/eclipse-pde/eclipse.pde/blob/a6601a59dbb0384bb241f4c0ec4dff470f4d2363/apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/util/Util.java#L1976-L1983

**Comment by iloveeclipse** [comment]
> support for Java-21 should be there as soon as JDT supports it.

The **JDT tests** run & work on Java 21, so obviously there is some support. The question is, at which place something goes wrong. 

I will create dedicated ticket for API tooling, if JDT API tooling problems are different to these test fails.

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-pde/eclipse.pde/issues/771.

> Actually it should just use the available JDT version

To be sure, I'm going to bump all dependencies in PDE.

**Comment by vik-chand** [comment]
Like @haubi , tests pass for me locally. Note I have launched eclipse with J21 ( instead of just changing jre)

<img width="548" alt="image" src="https://github.com/eclipse-pde/eclipse.pde/assets/99390647/83773e39-7dce-42fb-9018-ee6613a1e61f">

**Comment by vik-chand** [comment]
However I did find 2 issues ( thats why reduced test case above)
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-3"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-6"
Error while logging event loop exception:
Exception in thread "Worker-7" Exception in thread "Worker-10" java.lang.OutOfMemoryError: Java heap space
Logging exception:
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Exception in thread "Java indexing" java.lang.OutOfMemoryError: Java heap space
Exception in thread "WorkbenchTestable" org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
```
and duplicates
<img width="462" alt="image" src="https://github.com/eclipse-pde/eclipse.pde/assets/99390647/8ef0e9e2-5b10-4480-92bc-7485ab0afb8b">

**Comment by iloveeclipse** [comment]
Still failing : https://download.eclipse.org/eclipse/downloads/drops4/I20231106-1800/testresults/html/org.eclipse.pde.ui.tests_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html

Any chance someone look into that for 4.30?

**Comment by iloveeclipse** [comment]
> Any chance someone look into that for 4.30?

I've checked that again. What I see is that I can reproduce it locally if starting Eclipse with Java 21 & **forbid** JVM autodetection job (which automatically found & added Java 17 in the test instance). So starting test with `-DDetectVMInstallationsJob.disabled=true` I see the test fail. I will push a fix once I understand what the test **actually** want to test (has nothing to do with JKava 17 or 21 at all, except hard-coded Java 17 version).
