### ISSUE TITLE
missing adding of required dependencies in product content with plugins and features

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse-pde/eclipse.pde#766]
the capability is available individually, so should be straightforward to provide this when those are combined?

<img width="144" alt="Screenshot 2023-09-23 at 10 08 49 AM" src="https://github.com/eclipse-pde/eclipse.pde/assets/6447530/2e23d3b9-f444-404a-a6cf-5dd615d14162">
<img width="130" alt="Screenshot 2023-09-23 at 10 09 01 AM" src="https://github.com/eclipse-pde/eclipse.pde/assets/6447530/56882e98-5283-461b-902f-9c656d90f8e7">
<img width="132" alt="Screenshot 2023-09-23 at 10 09 12 AM" src="https://github.com/eclipse-pde/eclipse.pde/assets/6447530/80e07eab-9a13-4ea8-8d5a-d9aaf10c5a6d">

legend: product configuration IU content tab, when product configuration is (a) - with plugin alone, (b) - with feature alone, (c) - with plugins and features

**Comment by HannesWell** [comment]
That is on purpose as mentioned in https://github.com/eclipse-pde/eclipse.pde/pull/291#issuecomment-1304925967.
Adding dependencies to products explicitly is not really helpful as discussed in https://github.com/eclipse-pde/eclipse.pde/discussions/331.
Actually I would like to remove them for all types of Products. It is currently only blocked because Product exports from the workspace don't add requirements automatically like Products build with Tycho. The workspace export first has to be reworked to use the P2-Director directly.

**Comment by gireeshpunathil** [comment]
@HannesWell - thanks for bringing the context. I should admit I did not follow some of the deeper level conversations especially those in #331.

I had a client who wanted to migrate their large application, and this button proved to be critically helpful in filling all the gaps in terms of dependencies. they were originally using command line PDE build that threw number of obscure errors, and I recommended them to open the product in the IDE, use this button and all the problems vanished!

are you saying that the dependent artefacts will be anyways included in the build, so the build errors are false positives? how? sorry, I am unable to follow that part. is it possible to explain to me with an example or something?

thanks again!

**Comment by laeubi** [comment]
>  they were originally using command line PDE build that threw number of obscure errors, and I recommended them to open the product in the IDE, use this button and all the problems vanished!

PDE Build most likely don't work on mixed products anyways. The best would be fro them to migrate to [Tycho](https://github.com/eclipse-tycho/tycho), there is also [commercial support for Tycho](https://github.com/eclipse-tycho/tycho#getting-support) just in case.

> are you saying that the dependent artefacts will be anyways included in the build, so the build errors are false positives? how? sorry, I am unable to follow that part. is it possible to explain to me with an example or something?

PDE Build is effectively unmaintained for a long time. Tycho is used these days (also to build platform itself) and always includes strictly required dependencies.

**Comment by HannesWell** [comment]
> are you saying that the dependent artefacts will be anyways included in the build, so the build errors are false positives? how? sorry, I am unable to follow that part. is it possible to explain to me with an example or something?

If Products are build with Tycho requirements are always added, but the pde.build ANT tasks don't do that AFAIK, but I have never used them. I second Christoph's suggestion to migrate to Maven+Tycho, if possible.

**Comment by HannesWell** [comment]
> @HannesWell - thanks for bringing the context. I should admit I did not follow some of the deeper level conversations especially those in #331.
> 
The main problem is that requirements can easily become obsolete but nothing informs you about that because if added to the product a requirement effectively becomes 'primary' content of the product that a user explicitly state is wanted in the product and later one can only assume that it was added as dependency.

A general Problem of adding requirements to mixed products is also the question how to add them, as Features or as bundles? As bundles would be simpler but leads to many more entries. If it should be the minimum of Feature plus Bundles this can become a bit more difficult to compute. It is doable, but not easy.
And last but not least it would even more buttons to the UI that already has many.

**Comment by gireeshpunathil** [comment]
> PDE Build most likely don't work on mixed products anyways. The best would be fro them to migrate to Tycho, there is also commercial support for Tycho just in case.

thanks. what level of support PDE provides to tycho? for example, I don't see a UI based builder, editor or compiler for the tycho build descriptor.

**Comment by laeubi** [comment]
> what level of support PDE provides to tycho? for example, I don't see a UI based builder, editor or compiler for the tycho build descriptor.

You use the PDE UI and then run/build with maven, so there is no specific "Tycho UI".

**Comment by HannesWell** [comment]
> > what level of support PDE provides to tycho? for example, I don't see a UI based builder, editor or compiler for the tycho build descriptor.
> 
> You use the PDE UI and then run/build with maven, so there is no specific "Tycho UI".

Yes, you can say that PDE is the UI to develop and define Eclipse Plugin projects and Features, Products, P2-repos, etc. while Tycho (plus Maven) is the command line tool do build Plugins, Features, Products, P2-Repos etc.
The PDE Build ANT tasks serve the same purpose as Tycho+Maven and it is also possible to export/build Plugins, Features, etc. directly from the workspace, but Tycho has definitively the best support for PDE's latest capabilities.

There is also a tutorial from @vogella about Tycho: https://www.vogella.com/tutorials/EclipseTycho/article.html and you can of course just look how Eclipse itself building its projects.

**Comment by gireeshpunathil** [comment]
thanks for all the links and pointers @HannesWell and @laeubi . this is really useful.

Do you think a `tycho + maven` abstraction in the PDE makes sense? i.e, PDE UI providing a wizard / builder that generates a build descriptor for tycho? (my understanding is that one needs to hand-code the xml)

**Comment by laeubi** [comment]
> Do you think a tycho + maven abstraction in the PDE makes sense? i.e, PDE UI providing a wizard / builder that generates a build descriptor for tycho? (my understanding is that one needs to hand-code the xml)

You can use pomless + structured build layout then you only need one configurator pom to configure the tycho plugins:

https://tycho.eclipseprojects.io/doc/latest/StructuredBuild.html

**Comment by HannesWell** [comment]
> > Do you think a tycho + maven abstraction in the PDE makes sense? i.e, PDE UI providing a wizard / builder that generates a build descriptor for tycho? (my understanding is that one needs to hand-code the xml)
> 
> You can use pomless + structured build layout then you only need one configurator pom to configure the tycho plugins:
> 
> https://tycho.eclipseprojects.io/doc/latest/StructuredBuild.html

We could consider to provde an Maven archetype for Tycho that creates the usual project strucutre with a Plugin and Feature project a target-platform and a Product or category.xml. But of course there could be multiple variants that could be of interest, so it could be some work to set that up.

**Comment by gireeshpunathil** [comment]
thanks for the clarifications, closing.
