### ISSUE TITLE
Duplicated log entries in the Error log view

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#773]
Started latest 4.30.0.I20230927-1800 build, did pull from github and saw this **duplicated** session and **duplicated** entries:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/964108/6c72c4b6-6911-40d4-bcd6-b715a26ba71a)

The log file itself looks OK:

```
!SESSION 2023-09-28 09:31:42.466 -----------------------------------------------
eclipse.buildId=4.30.0.I20230927-1800
java.version=21
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /data/4x_platform_workspace -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.892
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.Chain has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.893
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.ChainType has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.894
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.ChainType has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.894
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.ChainType has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.894
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.ChainElement has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.894
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.ChainType has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.894
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.ChainType has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.900
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.correction.SerialVersionHashOperationDisplayCore has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:44.902
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.ChainType has no API description

!ENTRY org.eclipse.pde.api.tools 1 0 2023-09-28 09:35:51.699
!MESSAGE Visible type org.eclipse.jdt.internal.ui.text.correction.IProblemLocationCore has no API description
```

**Comment by gireeshpunathil** [comment]
@iloveeclipse - I see duplicated lines as well as sections. which one is the issue?

**Comment by iloveeclipse** [comment]
> which one is the issue?

Not sure what do you mean by that. Both - duplicated lines **and** duplicated sessions are bad.

**Comment by gireeshpunathil** [comment]
> duplicated lines and duplicated sessions are bad.

that is what I thought too, but your this comment: `The log file itself looks OK:` made me think that you are stating that the log file content (duplicated lines in it) is as expected, and problem is only with the duplicate sections - which confused me.

**Comment by iloveeclipse** [comment]
I have no steps, but I would start looking at the places where a "Session" object is being created in the view - this looks like not properly synchronized, so we create & add two of these.

In my case I assume I've had logs reported by multiple different jobs simultaneously, so must be a "classic" MT issue.

**Comment by iloveeclipse** [comment]
Closing this one, as the problem is not PDE related. Created https://github.com/eclipse-platform/eclipse.platform.ui/issues/1245
