### ISSUE TITLE
Maven archetype for Tycho

### ISSUE THREAD

**Issue by alshamams** [eclipse-pde/eclipse.pde#778]
Refs: https://github.com/eclipse-pde/eclipse.pde/issues/766

I plan to work on this by building it in phases:
Phase 1: A rudimentary archetype:
 - a menu item (tycho project) under the top level new project
 - an associated wizard that receives basic input
 - a builder that creates necessary folder structure
 - a builder that generates pom.xml from the user input

Phase 2: add plugins views
Phase 3: add feature views
Phase 3: add other views

Please let me know what you think about the approach!

**Comment by laeubi** [comment]
Archetypes are already supported my m2e project:

- https://github.com/eclipse-m2e/m2e-core

But whats missing is creating an archetype at Tycho itself:

- https://github.com/eclipse-tycho/tycho
- https://maven.apache.org/guides/mini/guide-creating-archetypes.html

so there is actually no need to add new UI at all or project types and/or views...

**Comment by alshamams** [comment]
Closing this issue, as I plan on creating an archetype in Tycho project.
