### ISSUE TITLE
IU location queries ALL knwon artifact repositories

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#793]
I just stumbled over `org.eclipse.pde.internal.core.target.P2TargetUtils.useAdditionalLocalArtifacts()` that always returns true.

This results in PDE **always** contacting all and every update-site known and even some additional places, this is very time consuming and especially annoying if there is one password protected site somewhere as P2 then always ask for a password even if the site itself is never used in the target!

**Comment by merks** [comment]
From the name, it sounds like the intent is to make more known local artifact repositories available which could save time versus loading from the internet.  But even that is somewhat questionable...

**Comment by laeubi** [comment]
Yeah I don't plan to work on this at the moment but though it was good to document as there are sometimes complains (e.g. @vogella ) that target resolution is slow in PDE.

**Comment by merks** [comment]
It's definitely a good find!!

**Comment by vogella** [comment]
> sometimes complains (e.g. @vogella ) that target resolution is slow in PDE.

I have not met a client who has otherwise... ;-)

**Comment by merks** [comment]
I'll close this in favor of https://github.com/eclipse-pde/eclipse.pde/issues/881 which discusses the technical details.
