### ISSUE TITLE
Creation of a plugin project with Eclipse as target throws errors if automatic metadata generation option is left unchecked

### ISSUE THREAD

**Issue by alshamams** [eclipse-pde/eclipse.pde#798]
Steps to recreate:
 - Create a plugin project.
 - Select 'Generate OSGi metadata automatically' in the 'target to run with' option
 - Finish
 - Create another plugin project
 - Select Eclipse in the 'target to run with' option
 - Select a standard plugin template
 - Finish
This results in plugin creation error:
Cannot invoke "org.eclipse.pde.core.plugin.IPluginModelBase.getPluginBase()" because "model" is null

**Comment by alshamams** [comment]
I plan on taking this issue up as soon as possible.

**Comment by laeubi** [comment]
> This results in plugin creation error:
Cannot invoke "org.eclipse.pde.core.plugin.IPluginModelBase.getPluginBase()" because "model" is null

Can you add the full stack trace for reference here?
