### ISSUE TITLE
Cannot stop JUnit 5 tests execution

### ISSUE THREAD

**Issue by trancexpress** [eclipse-pde/eclipse.pde#832]
To reproduce, run a JUnit 5 test case and try to stop the tests execution via the JUnit view stop button. E.g. import the project from the attached archive: [TestJunit5Abort.zip](https://github.com/eclipse-pde/eclipse.pde/files/13191028/TestJunit5Abort.zip)

See also this screen recording: 

https://github.com/eclipse-pde/eclipse.pde/assets/24752155/db1c67d4-c9a9-4128-b97c-e967cf0a9b24

Judging from this, maybe its not possible to stop the JUnit 5 tests using JUnit 5 API? https://github.com/junit-team/junit5/issues/1880

**Comment by iloveeclipse** [comment]
@SarikaSinha : any ideas here?
It is surprising for me to see such a basic feature is not implemented (if that is https://github.com/junit-team/junit5/issues/1880), but might be we can have some workaround in the IDE?

@trancexpress : not sure it belongs to PDE, is there a reason you didn't reported it for jdt.ui?

**Comment by SarikaSinha** [comment]
Yes, I have observed it. We can terminate from Console only.

**Comment by laeubi** [comment]
I'm not sure if it is really related to JUnit5, but also noticed in the past that sometimes if I'm **debugging** a test and terminate it there, JUnit still thinks it is alive or if I terminate it on JUnit side the Debugging session still persistst, so I can second @SarikaSinha that usually killing the test from console view works best...

**Comment by mickaelistria** [comment]
+1, it's been that way forever as far as I recall. IIRC, I had started to investigate that many years ago, and the difference in that the Debug view calls `stop` on the debug target, which the console view calls `destroy` on the process. On would expect that stopping the debug target manually would cascade to destroying the process, but it's not the case here.

**Comment by iloveeclipse** [comment]
`+1` to what? To current behavior?

**Comment by mickaelistria** [comment]
+1 as an ambiguous intent to tell "I notice this behavior too and interpret it as an issue".

**Comment by trancexpress** [comment]
> @trancexpress : not sure it belongs to PDE, is there a reason you didn't reported it for jdt.ui?

I'm not sure either, JDT UI prints this on the console of the launched process: `>STOP`

I'm yet to find where this is handled. I assume the launched process, and so PDE. I'm not sure though.

**Comment by trancexpress** [comment]
Please continue discussion on: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/889
