### ISSUE TITLE
PDEState.querySystemPackages(IVMInstall, IExecutionEnvironment) pass a jar location instead of a jvm install location

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#839]
`org.eclipse.pde.internal.build.site.PDEState.querySystemPackages(IVMInstall, IExecutionEnvironment)` currently construct a path to a jar like this:

`/opt/java/jdk-11.0.8/lib/jrt-fs.jar`

this has the problem that JDT created a new cache entry even if it already has loaded `/opt/java/jdk-11.0.8/`

In the context of
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1526

this creates even higher memory consumption.

**Comment by laeubi** [comment]
It seems that there is even special handling for this but currently leads to duplicate data:
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1532

**Comment by HannesWell** [comment]
It looks like this is fixed with https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1532.
Please re-open if that was a false assumption.
