### ISSUE TITLE
Migrate Event spy to pde ui 

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#85]
From https://bugs.eclipse.org/bugs/show_bug.cgi?id=579407
"It seems that we forgot to migrate the event spy as expected in [bug #498252](https://bugs.eclipse.org/bugs/show_bug.cgi?id=498252)

I reopen a bug to trace it.

If you are using Eclipse 2022-03 and you need it, it is available on my update site here : https://www.opcoach.com/repository/2021-12-E4Spies/"

**Comment by opcoach** [comment]
Ok, this bug will be only for the pure migration without any change regarding the jdt dependency or other UI enhancements...

**Comment by vik-chand** [comment]
The 2 failures are

testDelete_projectWithChangedBundleRoot
testProducts_productAddedToDeriveFolderNestedInSrcFolder

**Comment by opcoach** [comment]
Are the N&N still on this repo : ssh://xxxxxxxxx@git.eclipse.org:29418/www.eclipse.org/eclipse/news ?

**Comment by akurtakov** [comment]
This created 6 new warnings in the nightly build https://download.eclipse.org/eclipse/downloads/drops4/I20220510-1800/testResults.php#PluginsErrors . Detailed at https://download.eclipse.org/eclipse/downloads/drops4/I20220510-1800/compilelogs/plugins/org.eclipse.pde.spy.event_1.0.0.v20220510-1429/@dot.html

**Comment by vik-chand** [comment]
Warning is now fixed by @akurtakov

**Comment by vik-chand** [comment]
> Are the N&N still on this repo : ssh://xxxxxxxxx@git.eclipse.org:29418/www.eclipse.org/eclipse/news ?

@opcoach 
Can you add the location of event spy? Also a snap of location or spy or both event spy would help.
