### ISSUE TITLE
Add a version for a newly created product configuration file

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#851]
I think we should add a default version like 1.0.0 to a newly created product. AFAIK Tycho pomless builds require a version.

![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/c6f3273d-1c69-4617-88be-ed7b68ab5952)

**Comment by HannesWell** [comment]
Sounds good.
Do you want to provide a PR?

**Comment by vogella** [comment]
> Sounds good. Do you want to provide a PR?

yes
