### ISSUE TITLE
Combine "Update and Refresh" button on the target platform editor

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#852]
After > 10 years of using PDE target editor I still do not know the difference of "Update" and "Refresh" on the target editor.

Can we combine these buttons and just do both if the user presses these instead of having two similar named buttons?

![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/46f341a6-6a8c-4107-9c59-599a8f71e162)

cc @HannesWell

**Comment by laeubi** [comment]
> After > 10 years of using PDE target editor I still do not know the difference of "Update" and "Refresh" on the target editor.

`Update` - updates to the latest available version of that location
`Refresh` - throw a way any cached content and initiate a reload

> Can we combine these buttons and just do both if the user presses these instead of having two similar named buttons?

They do different things that make no sense to combine as one usually don't want to have both actions.

**Comment by merks** [comment]
Note that Update enables/disables based on the selection and also note that the buttons are already self-documenting:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/50f76192-70cf-41be-8845-b0daa4985142)

**Comment by vogella** [comment]
Thanks for the replies and the hints.

**Comment by vogella** [comment]
Btw. if version="0.0.0" is used, Update does nothing. I guess this is fine, but one of the reason why I did not know what this button is supposed to be doing, as I prefer to use 0.0.0 in my target files.

**Comment by laeubi** [comment]
> Btw. if version="0.0.0" is used, Update does nothing. 

`0.0.0` already means latest version, one *might* want to replace it with a fixed version but actually `0.0.0` is a bit of a hidden hack and not officially supported e.g. in the UI at all.

**Comment by merks** [comment]
I actually didn't know about the Update button at all and have been manually fixing things, e.g., when there are new EMF versions.  I will try this button in the future when updating the Platform target platform...

I've just now been working on feature for Oomph targlets which can generate a *.target where one can run into the exceptional case that one needs more than one version of a given symbolic name.  In that case one must specify a version (because otherwise you get the highest version not both versions), which is annoying because if an updated version becomes available, one must Update the version in the *.target (or regenerate the target platform in the targlets case).  I just wanted to point out that 0.0.0 does not always just work...

**Comment by vogella** [comment]
> I actually didn't know about the Update button at all and have been manually fixing things,

Great to hear that I'm not the only veteran that did miss knowledge about these buttons. :-)

**Comment by laeubi** [comment]
You can always use a target-file-reference and has the "older" version defined there, then you can update all other versions if you like in the main target.

As you noted already "Update" is actually context sensitive, you can even have update for an individual item (even though I'm not sure if IU locations implement that yet).

**Comment by HannesWell** [comment]
> I just wanted to point out that 0.0.0 does not always just work...

That's right.
But usually one does not have main interest in two Version of the same Plugin/Feature.
But of multiple different Versions of a bundle are required due to version ranges, the Planner can handle this.
But at least to me it happend very rarely that I needed to define two versions of my 'root' IUs.

**Comment by merks** [comment]
I really have two such issues in the BIRT target platform and hence I implemented the following so that the generator produces a correct result without hand modification of that generated result:

https://github.com/eclipse-oomph/oomph/issues/40

But I digress and I am hijacking this issue. 😱

**Comment by vogella** [comment]
What does "Reload Target Platform" do in this context? My assumption always have been that is does the same as "Update". Is that correct? If yes, can we name it the same.

Currently we seem to offer three ways of updating the target platform:

* Update
* Refresh
* Reload Target Platform

**Comment by merks** [comment]
I think this was already answered:

https://github.com/eclipse-pde/eclipse.pde/issues/852#issuecomment-1788559909

To be even more explicit:

With **update**, if I have say version 1.0.0.xxx specified explicitly, it will change to version 1.1.0.x.  E.g., I use this when I update the EMF or Orbit URL and there are new/updated versions.  **It will edit the file.**

The **refresh** it will just load the site and if there are 0.0.0 versions it will maybe get a new latest.  **It will not edit the file.**

I'm not sure to which Reload you are referring.  The one in the preferences?

**Comment by vogella** [comment]
If you look at the first screenshot, right top corner you see the new option which I think we did not discuss so far. It is the link in the form, which is "Activate" if the target is not active.

**Comment by laeubi** [comment]
> What does "Reload Target Platform" do in this context? My assumption always have been that is does the same as "Update". Is that correct?

No, all it does is throw away your "Active Targetplatform State" and set the current target platform (again).

**Comment by merks** [comment]
FYI, mine looked like this because it's no the active one:

![image](https://github.com/user-attachments/assets/37c4cf4d-6a22-40fc-9f9d-5631bf68efce)

**Comment by merks** [comment]
The issue subject suggesting to `Combine "Update and Refresh"` seems like a no go for the reasons explained, i.e., one is an editing operation the other is not.

**Comment by HannesWell** [comment]
> > What does "Reload Target Platform" do in this context? My assumption always have been that is does the same as "Update". Is that correct?
> 
> No, all it does is throw away your "Active Targetplatform State" and set the current target platform (again).

Yes. It's like the similar Code-Mining action displayed in the Source tab.
But if it isn't clear, we should add a tool-tip to the action.

**Comment by merks** [comment]
Tool tips are a good idea. 👍
