### ISSUE TITLE
Update the product editor text for exporting

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#859]
Currently each product definition file "advocates" the Eclipse Product export wizard, see sceeenshot. I suggest that we remove this section, it is not very common that files list the "preferred way to get exported" and as we know PDE export is not well-maintained.

![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/33bf975b-d257-49ab-acae-f9d9e7fd1ac6)

WTYT  @HannesWell and @laeubi?

**Comment by iloveeclipse** [comment]
Please leave the link, it is handy to use.

**Comment by vogella** [comment]
> Please leave the link, it is handy to use.

You still have the export button on the same page.

**Comment by iloveeclipse** [comment]
But it is harder to find. What is the point of removing something that just works?

**Comment by HannesWell** [comment]
I have no strong opinion in any direction.
So I would be fine to keep it.

> > Please leave the link, it is handy to use.
> 
> You still have the export button on the same page.

That's right, but for example the Run/Debug Button is duplicated in the form and rop-bar as well.

**Comment by laeubi** [comment]
> as we know PDE export is not well-maintained.

@vogella I'll take care of upgrading the PDE export and have created:
- https://github.com/eclipse-pde/eclipse.pde/issues/862

feel free to mention this issue in any existing one that shows any problem.

**Comment by vogella** [comment]
Great news @laeubi fixing the UI export is even better then updating the text.
