### ISSUE TITLE
Add support for Eclipse-BundleShape in Manifest-Editor

### ISSUE THREAD

**Issue by HannesWell** [eclipse-pde/eclipse.pde#864]
The PDE Manifest-Editor should support the `Eclipse-BundleShape` header similiar to how it for example supports `Bundle-ActivationPolicy`.

In the Overview page there should be a check-box labeled with `Unpack this plug-in during installation` or similar.
And when it is checked the `Eclipse-BundleShape; dir` should be added. Unchecking it can simplify remove the header, since `jar` is the default.
The check-box should have a tool-tip indicating that this option is usually not required, only if the code relys on that embedded resources are available as files directly.

This is a follow-up on https://github.com/eclipse-pde/eclipse.pde/issues/730.

**Comment by laeubi** [comment]
Instead of a checkbox it would be better to have a drop down (or Radiobuttons) with

- default
- jar
- directory

see
- https://github.com/eclipse-equinox/p2/issues/358

for why one would explicitly configure the "default", also I'm not sure if it is really "Unpack this plug-in during installation" if one just installs it into OSGi (@tjwatson ?) I think this is only performed by P2.

**Comment by tjwatson** [comment]
> for why one would explicitly configure the "default", also I'm not sure if it is really "Unpack this plug-in during installation" if one just installs it into OSGi (@tjwatson ?) I think this is only performed by P2.

Isn't the default value simply not specifying the header at all?  The framework pays no attention to this header, so it must be p2 that does anything with it.

**Comment by laeubi** [comment]
> The framework pays no attention to this header, so it must be p2 that does anything with it.

That's what I mean, therefor I find "Unpack this plug-in during installation" a bit misleading, and maybe not suitable for the main Manifest tab at all...

**Comment by alshamams** [comment]
Hi,
I intend to take up this issue.
