### ISSUE TITLE
Unable to resolve target contents with current nightly build

### ISSUE THREAD

**Issue by ptziegler** [eclipse-pde/eclipse.pde#867]
A short explanation of our setup:

Because we need to access some of the internal classes, we have rebundled the [GlazedLists](https://mvnrepository.com/artifact/com.glazedlists/glazedlists/1.11.0) jar, which we host on an internal Maven repository and which is added to our target-platform definition via m2e.
Our definition also contains the NatTable extensions for GlazedLists, which is added via a p2 repository.

Up until (and including)  the 4.30 M1, this definition was able to resolve without any problems. But with the recent nightly build, I now get the following error:

```
No repository found containing: osgi.bundle,ca.odell.glazedlists,1.11.0.v20220504
session context was:(profile=TARGET_DEFINITION:resource:/TargetPlatform/target-platform.target, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
```
![image](https://github.com/eclipse-pde/eclipse.pde/assets/70652978/0148249f-c86e-4960-88ed-12e461585166)

I think the main problem is that there are two glazedlist bundles inside the classpath, the latter being contributed by the Eclipse itself:

ca.odell.glazedlists 1.11.0.v20220504 (Maven)
ca.odel.glazedlists 1.11.0.v20190926-1838 (p2)

Up until the M1, the Eclipse used the p2 artifact to resolve its dependencies. But due to some recent changes, it now uses the Maven artifact instead. However, p2 doesn't support Maven artifacts, which is what leads to this exception.

Any idea what caused this issue or how this could be fixed? My guess is that the Maven artifact now takes priority, because its qualifier is lexicographically "higher" than the p2 artifact, but I don't understand why this is suddenly a problem.

**Comment by laeubi** [comment]
@ptziegler can you try to include `<unit id="ca.odel.glazedlists" version="1.11.0.v20190926-1838">` in your target? It seems you are using an "open" version that always resolves to highest version.

**Comment by merks** [comment]
If you repackage it and use the same bundle name as this, it seems likely to cause problems:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/c1780c53-7c72-42eb-9354-d59879ef2306)

Where exactly this thing hosted?  Have any iplab issues been involved?

**Comment by ptziegler** [comment]
@laeubi 
> can you try to include <unit id="ca.odel.glazedlists" version="1.11.0.v20190926-1838"> in your target?

That worked, thanks!

@merks 
> Where exactly this thing hosted? Have any iplab issues been involved?

It's in our company-internal repository, so no other issues or anything like that have been involved.

**Comment by ptziegler** [comment]
I think it's safe to say that #207 is the reason for this new behavior. 😅 
> Just a assume a Directory/Maven/... location that contains a newer version of a dependency then this might be chosen instead of the one from the P2 sites (even though it is there!) and then you not have both but only one version (the one from the Directory/Maven/...) in the target in contrast of two before.

> That is a valid point. Though one can have more specific ranges if one needs/wants two versions of some specific thing, and one can specify exact unit versions if one really want exactly a specific version.

> So yes, it's definitely possible that someone might be annoyed, and might complain about any behavior change.

(I suppose that's me...)

Having the "same" version is probably an edge case, but I'm happy with @laeubi's solution. Though I find it weird that PDE then rejects the Maven artifact, even if it has the same (technically even more) capabilities.

**Comment by laeubi** [comment]
> Though I find it weird that PDE then rejects the Maven artifact, even if it has the same (technically even more) capabilities.

P2 has a concept of `Metadata Repositories` (what are used here from maven and say there is an IU with a higher version) and `Artifact Repositories`  (currently not used here) where it then complains that it can't find the higher version it previously resolved.

In combination with using an (not officially supported) `0.0.0` versioned unit that is overlayed by another target location this leads to the mentioned problem.

You might want to open an issue for that with a small example (or even better testcase) so we can fix that.

**Comment by merks** [comment]
@ptziegler 

That's a relief!  👍

**Comment by ptziegler** [comment]
I'm closing this one as the original issue has been resolved. I'll create a separate issue for when a `0.0.0` version is used.
