### ISSUE TITLE
How to register two model fragments via Model-Fragment and current wizard override existing entry

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#896]
Is it possible to register two model fragments with the MANIFEST based solution which I think @laeubi did implement?

If I use the wizard to create a new fragment.e4xmi fragment, I get:

```
Model-Fragment: fragment.e4xmi
```

If I use the wizard to create another new fragment2.e4xmi fragment, the existing entries get overriden:

```
Model-Fragment: fragment2.e4xmi
```

It is possible to register two fragments? I tried:

```
Model-Fragment: fragment.e4xmi, fragment2.e4xmi
```
with and without line-break but this did not work.

**Comment by laeubi** [comment]
I don't think it is implemented, but technically it would be possible to implement.

Please note that this actually is a feature of platform.ui:
https://eclipse.dev/eclipse/news/4.20/platform_isv.php#register-model-fragment

Beside that I only reviewed it and added the wizard :-)

One question of course would be why one want two (or more) fragments in the same bundle, is there any benefit? I find the inital setup quite cumbersume, e.g. adding imports of foreign elements to reference so usually don't like to repeat that step multiple times, so maybe the better alternative would be to simply disable the wizard if there is already a fragment extension.

**Comment by vogella** [comment]
I think it is fine to not support to fragments via MANIFEST.MF header, as such requirements could be fulfilled with the extension point registration. A warning / error message would be nice, if an entry already exists.

**Comment by vogella** [comment]
Closing as WONTFIX for now
