### ISSUE TITLE
Unable to load p2 dependencies from nested target files

### ISSUE THREAD

**Issue by pzi-dsa** [eclipse-pde/eclipse.pde#90]
I'm currently trying to create a modular target file where I use a base file, which is shared among all projects, and then add additional dependencies for each project individually.
However, I noticed that there seems to be issues resolving p2 dependencies from the base file.
Example:
![image](https://user-images.githubusercontent.com/92990747/167854896-9d3b0f5f-3ecb-436f-85e9-17053f234a27.png)

Both nested target files are identical and contain log4j, once referenced via the Orbit update site and once via Maven Central. The only difference is that one is named _child.target_, while the other is named _nested.target_.
Child1/2:
![image](https://user-images.githubusercontent.com/92990747/167854790-baf7ec17-d826-4d39-b9d5-aa1e14ee54ce.png)

Those errors also show up on the latest integration build for 4.24.

**Comment by vogella** [comment]
@pzi-dsa does it work with Tycho? Can you share an example target file which shows the problem?

**Comment by vogella** [comment]
@laeubi you implemented both, can you have a look?

**Comment by laeubi** [comment]
First it would help to attach the target file that creates the problem, second I don't fully understand what the error is e.g. what is the expected behaviour?
Just in case please note that you need to reload the target whenever one of the childs change, this will not be detected automatically.

**Comment by pzi-dsa** [comment]
> what is the expected behaviour?

I would assume that the p2 artifacts from both embedded target files are added to the classpath. It's not a problem when both are identical. But effectively, all bundles provided by Child 2 are unavailable.

Reloading the embedded files, the parent file and any other combination doesn't resolve the problem.

**Comment by laeubi** [comment]
Does this also happen if they *are* different? It might be that pde is filtering stuff when it is already there?

**Comment by laeubi** [comment]
As it works with the maven type it seems not be directly specific to m2e or the nested target, I fear one needs to debug this to get more details, @pzi-dsa do you like to take a look?
The interesting part should be at org.eclipse.pde.internal.core.target.TargetReferenceBundleContainer.getTarget(IProgressMonitor) that is where it loads the target that is referenced and simply return its content.

**Comment by pzi-dsa** [comment]
It seems like the problem shows up while trying to load the artifacts from the target file. The error message is normally ignored, but this is the corresponding stacktrace:
```
org.eclipse.core.runtime.CoreException: Problems loading repositories
	at org.eclipse.pde.internal.core.target.IUBundleContainer.cacheIUs(IUBundleContainer.java:304)
	at org.eclipse.pde.internal.core.target.IUBundleContainer.synchronizerChanged(IUBundleContainer.java:370)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.notify(P2TargetUtils.java:879)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.synchronize(P2TargetUtils.java:811)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:403)
	at org.eclipse.pde.internal.core.target.TargetReferenceBundleContainer.getTarget(TargetReferenceBundleContainer.java:110)
	at org.eclipse.pde.internal.core.target.TargetReferenceBundleContainer.resolveBundles(TargetReferenceBundleContainer.java:45)
	at org.eclipse.pde.internal.core.target.AbstractBundleContainer.resolve(AbstractBundleContainer.java:96)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:424)
	at org.eclipse.pde.internal.ui.editor.targetdefinition.TargetEditor$TargetChangedListener$1.run(TargetEditor.java:607)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Unable to locate installable unit org.eclipse.swtbot.eclipse.feature.group 3.1.0.202106041005
```
After looking at the IUs which are actually available to the profile, I got the following list:
 - org.apache.log4j.source=org.apache.log4j.source 1.2.15.v201012070815
 - org.apache.log4j=org.apache.log4j 1.2.15.v201012070815
 - org.eclipse.pde.core.target.source.bundles=org.eclipse.pde.core.target.source.bundles 1.0.0

Which is weird, given that by that time, I had already removed log4j from the target file. I then deleted the _org.eclipse.pde.core_ directory in the _,metadata_ folder and after restarting, it successfully loaded the artifacts.
![image](https://user-images.githubusercontent.com/92990747/168029882-8a22b831-beb8-411c-87dd-392579a86260.png)

My current assumption is this: The IUs of the target file are cached locally. And when using nested target files, there is the possibility that the cache is not properly updated. The Eclipse then tries to resolve the new dependencies against an outdated cache, causing the exception.

**Comment by laeubi** [comment]
> The error message is normally ignored

Do you see an opportunity to make the target resolution fail in such a case instead silently(?) ignore that?

> My current assumption is this: The IUs of the target file are cached locally. And when using nested target files, there is the possibility that the cache is not properly updated. T

That is possible but the IU location and P2 stuff is kind of mystery :-)
Probably someone with more knowledge an that area could give a hint how to refresh that cache? There is a "refresh" action in the target, maybe this must be invoked as part of a Nested Target refresh as well?

**Comment by pzi-dsa** [comment]
> Do you see an opportunity to make the target resolution fail in such a case instead silently(?) ignore that?

I don't think there's an easy way to propagate the exception upwards. But the exception should at least show up in the error log. I have created the corresponding [pull request](https://github.com/eclipse-pde/eclipse.pde/pull/95)

**Comment by pzi-dsa** [comment]
I think I found the cause of the problem. Those lines in the _contentsChanged_ method of the _TargetEditor_ class are called when I click the reload button in the IDE:
```
// delete profile
try {
	P2TargetUtils.forceCheckTarget(getTarget());
	P2TargetUtils.deleteProfile(getTarget().getHandle());
} catch (CoreException e) {
	PDEPlugin.log(e);
}
getTarget().resolve(monitor);
if (monitor.isCanceled()) {
	return Status.CANCEL_STATUS;
}
// Don't return any problems because we don't want an error dialog
return Status.OK_STATUS;
```
I.e. only the target profile of the parent is deleted, but none of the children. As a quick fix, I then adapted the _reload_ method of the _TargetReferenceBundleContainer_ class:

```
public void reload() {
	if (targetDefinition != null) {
		try {
			P2TargetUtils.forceCheckTarget(targetDefinition);
			P2TargetUtils.deleteProfile(targetDefinition.getHandle());
		} catch (CoreException e) {
			PDECore.log(e);
		}
	}
	targetDefinition = null;
}
```

And with this, the target platform is able to correct itself, after reloading.
Given that this is not a very elegant solution, what would be a better way to resolve this?

**Comment by laeubi** [comment]
If it works... why not ;-)

Beside that, a target location can be adapted to the types used in the content editor and then one could trigger the appropriate methods on those items, so you at least do not need to copy the code and just trigger what would be triggered in an editor as well.

The relevant method should be `org.eclipse.pde.ui.target.ITargetLocationHandler.reload(ITargetDefinition, ITargetLocation[], IProgressMonitor)` and the location should be adaptable to it.

**Comment by HannesWell** [comment]
@pzi-dsa can you verify with the next I-build of 4.25 aka. 2022-09 if the issue is fixed with that change?

**Comment by pzi-dsa** [comment]
I tried it with I20220609-1020 and the problem no longer shows up. Even with the corrupted workspace, the error corrected itself after closing and re-opening the target editor.

Thanks you all for your feedback!
