### ISSUE TITLE
Bogus "Plug-in reference '...' cannot be resolved" warnings

### ISSUE THREAD

**Issue by merks** [eclipse-pde/eclipse.pde#915]
Oomph's workspace was warning free but with the current I-Build it has this bogus warning::

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/24357816-06e8-4e3d-9d4d-7f112640b2e7)

One can even double click on the included plugin to navigate to it.

I think this is a regression perhaps related to removal of support for some of the properties.

**Comment by laeubi** [comment]
Just in case can you try remove the fragment property if it fix the warning?

**Comment by merks** [comment]
Unfortunately not:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/bab95d8b-b655-487a-bd6d-4dea30165bb5)

**Comment by merks** [comment]
We see the same problem in the SDK's own workspace too:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/208716/c2fd64b6-8d7b-44c9-acff-c1cf49d09ac1)

**Comment by HannesWell** [comment]
Fixed with https://github.com/eclipse-pde/eclipse.pde/pull/916.
