### ISSUE TITLE
An internal error occurred during: "Load Target Platform". 'void org.eclipse.m2e.pde.target.MavenFeaturePlugin.setFragment(boolean)'

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#920]
With latest I-Build and the M2E tooling from the 2023-12 update site, I see the following error (in a client environment).

```

java.lang.NoSuchMethodError: 'void org.eclipse.m2e.pde.target.MavenFeaturePlugin.setFragment(boolean)'
	at org.eclipse.m2e.pde.target.MavenFeaturePlugin.<init>(MavenFeaturePlugin.java:31)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.generateFeature(MavenTargetLocation.java:218)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.resolveArtifacts(MavenTargetLocation.java:173)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.resolveBundles(MavenTargetLocation.java:157)
	at org.eclipse.pde.internal.core.target.AbstractBundleContainer.resolve(AbstractBundleContainer.java:97)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:385)
	at org.eclipse.pde.core.target.LoadTargetDefinitionJob.runInWorkspace(LoadTargetDefinitionJob.java:123)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


An internal error occurred during: "Load Target Platform".
'void org.eclipse.m2e.pde.target.MavenFeaturePlugin.setFragment(boolean)'

```

@merks @HannesWell I think I saw you guys working on a similar issue. Maybe this is already solved already with latest M2E update site (can't test at the moment with the client as he has other priorities).

**Comment by merks** [comment]
Clearly not a PDE problem.   I appears to be fixed by this:

https://github.com/eclipse-m2e/m2e-core/commit/fcf4ebbd1df04b2e1329e7957f5e264ec9f96689

**Comment by vogella** [comment]
Thanks @merks 

Would be good if M2E could update its 2023-12 contribution with this patch @HannesWell otherwise I assume lots of people will see this error (if they using the M2E tooling together with their target platform).

**Comment by merks** [comment]
SimRel contributions for M3 are due by tomorrow and even then those won't be in a train repository, other than staging, until Friday...

**Comment by merks** [comment]
The point wasn't that you can't find the source, but that's it super easy to copy and paste a qualified name from a stack trace and find the source for any Eclipse project.  Anyway, it's just an FYI, not telling you to do more work!

**Comment by laeubi** [comment]
I probably should have made the m2e target locations a payed feature then if it is "too much" to take a few minutes to look for the right repository to report a problem 😠

So who pays "us" for moving the falsely reported problems (wrong repository) to the right direction checking if its already fixed? How could we ask other reporters to carefully check where to report problems if long-time committer simply don't care? Just wondering ...

**Comment by vogella** [comment]
> The point wasn't that you can't find the source, but that's it super easy to copy and paste a qualified name from a stack trace and find the source for any Eclipse project. Anyway, it's just an FYI, not telling you to do more work!

Thanks, appreciated. Oomph tooling is not always installed in my client installations, hence this very nice and easy way is not always available to me.

**Comment by vogella** [comment]
> How could we ask other reporters to carefully check where to report problems if long-time committer simply don't care? 

This is very insulting. I care that is why I sacrifice my time to report.

In this case the target editor showed a problem in calling a M2E method. So without having the time to invest in detail, the error could have been in both. I also agree that M2E would have been to more logical choice but cc @HannesWell (who implemented the removal of the fragment) I was hoping that he would know if that is still an issue or not without too much effort on his side.

**Comment by HannesWell** [comment]
> Would be good if M2E could update its 2023-12 contribution with this patch

I plan to update the m2e contribution tomorrow evening.
In the meantime you can use the m2e-snapshots:
https://download.eclipse.org/technology/m2e/snapshots/latest/
