### ISSUE TITLE
Project 'org.eclipse.pde.ds.tck' is missing required source folder: 'tck/OSGI-INF/impl-src'

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#958]
When settting up a oomphed workspace it results in error:
![image](https://github.com/eclipse-pde/eclipse.pde/assets/51790620/62a86efe-5a08-4374-8bdd-cd26bfa1bd75)

**Comment by jukzi** [comment]
Oomphing workspace did work a month ago

**Comment by merks** [comment]
I'll await @laeubi before committing such a change...

**Comment by merks** [comment]
I might as well create a PR, so if this is good like this, we can get it checked in faster...
